### ISSUE TITLE
Footer overlap with navbar

### ISSUE THREAD

**Issue by elias-soykat** [documenso/documenso#1010]
### Issue Description

![image](https://github.com/documenso/documenso/assets/76895393/2fe4202d-75f0-4436-932b-85fbef95f74d)

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rohit-saluja** [comment]
@elias-soykat  not able to replicate this issue.
