### ISSUE TITLE
API token deletion not reflected in cache until page reload

### ISSUE THREAD

**Issue by ashrafchowdury** [documenso/documenso#1011]
### Issue Description

After deleting the API token, the token still persists in the cache. Despite the deletion process, the token remains accessible until the page is manually reloaded. This inconsistency poses a potential security risk.

Also, the 'Token expiration date' field is not clear after successfully creating the API token.

### Steps to Reproduce

1. Log in to the app,
2. Navigate to the settings or profile section where API tokens are managed.
3. Create a new API token.
4. Then delete that API token.
5. Notice that the deleted token is still accepted and functional.
6. Manually reload the page to remove the token from the display

### Expected Behavior

The API token should be immediately removed from the cache after successfully deleting it from the database.

### Current Behavior

The API token remains accessible and functional even after deletion until the page is manually reloaded.

### Screenshots (optional)

https://github.com/documenso/documenso/assets/87828904/187c5565-d2c5-42b0-b698-5c978045076a

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome, Edge

### Version [e.g., 2.0.1]

Latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by ashrafchowdury** [comment]
**I would like to work on this issue if it gets approved.**

**Comment by dguyen** [comment]
Thanks, assigned it to you :)

**Comment by ashrafchowdury** [comment]
> @ashrafchowdury are you working on this?

Yes.

**Comment by rushatgabhane** [comment]
Hey, @ashrafchowdury it's been almost two months since you were assigned. How's it looking? Do you need help?

**Comment by rushatgabhane** [comment]
I'd love to work on this issue if that's okay. I aim to complete it in 3 days

**Comment by ElTimuro** [comment]
@ashrafchowdury are you actively working on this? Otherwise I'm reassigning tomorrow..

**Comment by ashrafchowdury** [comment]
> @ashrafchowdury are you actively working on this? Otherwise I'm reassigning tomorrow..

I'm really sorry for the late reply @ElTimuro, I not working on this issue currently feel free to assign someone else.

Again, I apologize for not taking any action on it.

**Comment by ElTimuro** [comment]
@ashrafchowdury it's fine, thanks for letting me know

**Comment by cchirag** [comment]
Can I work on this?

**Comment by ElTimuro** [comment]
- @cchirag if @rushatgabhane declines you can have it
- @rushatgabhane, since you asked first, do you still want to do this?

**Comment by rushatgabhane** [comment]
@ElTimuro looks like @cchirag already raised a PR 😅

**Comment by cchirag** [comment]
Hey @rushatgabhane, sorry for picking up the task. The fix seemed straightforward and we had not heard from you in 4 days. But, I guess you can review my PR and maybe share it with us if you have a better approach.

**Comment by rushatgabhane** [comment]
@cchirag don't worry about it, it's no problem : )

**Comment by cchirag** [comment]
Thanks man @rushatgabhane . @ElTimuro can you please review the PR.
