### ISSUE TITLE
Signatures moved/rotated from original placement

### ISSUE THREAD

**Issue by premiare** [documenso/documenso#1015]
### Issue Description

After placing the boxes for the two signees, once the document has been signed and completed the signatures, emails and dates are rotated -90 degrees.

### Steps to Reproduce

Place boxes in an order like below:

![image](https://github.com/documenso/documenso/assets/64188227/7cd7bbad-1625-4517-be37-a5c38490ec42)

### Expected Behavior

Expect to see the signatures, emails and dates to maintain their position as shown in the preview before sending the request to sign.

### Current Behavior

All selected fields are rotated -90 degrees as shown below:

![image](https://github.com/documenso/documenso/assets/64188227/73239143-f8f6-48fb-ab0e-fcf0e7db331d)

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Brave

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
fix it pls 😬

**Comment by premiare** [comment]
I'm finding it hard to find time to work on this issue, so I'll open it up again

**Comment by ShubhamSingal07** [comment]
Is this issue resolved? i cant reproduce it

**Comment by ElTimuro** [comment]
- @premiare Since you let it go, @ShubhamSingal07 can take a look
- Reassigning

**Comment by ShubhamSingal07** [comment]
@premiare i think this issue is resolved already, can you please confirm if you are still facing it?

**Comment by premiare** [comment]
Looks resolved to me, might have been fixed internally

**Comment by ecatjacoti** [comment]
Issue occured on my tests:
- docker deployment based on    image: documenso/documenso:latest
- both original and signed document attached

[constat-accident-fr-unsigned.pdf](https://github.com/user-attachments/files/16011194/constat-accident-fr-unsigned.pdf)
[constat-accident-signature-rotated.pdf](https://github.com/user-attachments/files/16011196/constat-accident-signature-rotated.pdf)
<img width="1332" alt="Screenshot-during-template-creation" src="https://github.com/documenso/documenso/assets/126815865/7022ae76-8a34-4f52-93e2-d71b84d0b104">
