### ISSUE TITLE
Subdomains in Advanced

### ISSUE THREAD

**Issue by ThcDelux3** [documenso/documenso#1016]
### Issue Description

![Screenshot 2024-03-10 172710](https://github.com/documenso/documenso/assets/25651512/a7f05f83-8390-486d-98dc-0357c3cec7ab)
![subdomain](https://github.com/documenso/documenso/assets/25651512/eacbf5e4-b074-40a2-91e9-215e274d6b7b)
![www](https://github.com/documenso/documenso/assets/25651512/d7081656-6684-4d5e-93c1-9a69041c83e9)

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

Latest

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ThcDelux3** [comment]
Root domain: Works
WWW.: Works
custom subdomain: does not work!

**Comment by adithyaakrishna** [comment]
@ThcDelux3 Thanks for reporting this, will send a fix for it ASAP :)

**Comment by rohit-saluja** [comment]
@adithyaakrishna  I tried to resolve this issue not good with regex is this correct 
![image](https://github.com/documenso/documenso/assets/33275954/f42d1dfa-86de-4106-9353-bbbf4d0e6cb0)

**Comment by ThcDelux3** [comment]
Have a look at: https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url
