### ISSUE TITLE
Admin Panel: Document super delete

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#1020]
Currently a document can't be deleted from Documenso permanently, this is done intentionally since even if an owner deletes a document the recipients still have a partial stake in it and thus should always be able to view it on Documenso.

That said bad actors may use the system and send documents that are spam or designed to trick users, self-hosters may also have also have sent a slew of testing documents which they now want to clean up as they move to production.

Instead of doing this manually in the database which is high risk and prone to error we should offer a way to delete the document within the current admin panel. This should require a confirmation before deletion can take place.

Requirements:
- Add a button to the `admin/documents/[id]` page to super delete the document
- Have the button trigger a dialog prompting for confirmation of deletion
- **Optional:** Email the document owner letting them know that their document was removed (maybe state a reason?)

**Comment by rohit-saluja** [comment]
can I work on this

**Comment by rohit-saluja** [comment]
created a [pr](https://github.com/documenso/documenso/pull/1023) for this.
