### ISSUE TITLE
Empty team state required

### ISSUE THREAD

**Issue by Gautam-Hegde** [documenso/documenso#1021]
### Feature Description

- Instead of displaying `UserSettingsTeamsPageDataTable` when no teams have been created, which leads to a bug in `DataTablePagination`, we can have a new `EmptyTeamState` 

https://www.loom.com/share/484e0d5250e04b27a2c2eef116d62a62?sid=931abc1c-c6d5-4d97-a853-62fefaa8b432

### Proposed Solution

![chore ets](https://github.com/documenso/documenso/assets/85569489/3c92ca05-025c-49c6-8fc8-c45cf0a4e3ac)

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [x] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Hi!

What's this pagination bug you're referring to?

**Comment by Gautam-Hegde** [comment]
It shows **page 1 of 0** without any teams

**Comment by dguyen** [comment]
I think it's better to fix that instead, since the table is searchable and we have skeletons

**Comment by Gautam-Hegde** [comment]
I was considering this because it would maintain consistency, as documents and templates also utilize that empty state component.

**Comment by dguyen** [comment]
Yeah those are rendered on the server so there's no loading UI associated with them.

Whereas the data for this component is being loaded on the client side, so we _currently_ prefer to not have any empty state like that.
