### ISSUE TITLE
Command Menu Fails to Close on First 'Escape' Click; Requires Second Click for Closure

### ISSUE THREAD

**Issue by deepgolani4** [documenso/documenso#1032]
### Issue Description And Repro steps

Open the Command menu with ⌘+K.

When clicking "Escape" for the first time.
<img width="1237" alt="Screenshot 2024-03-17 at 8 04 18 PM" src="https://github.com/documenso/documenso/assets/54791570/69805381-d750-4183-b9b4-7eb08b95e005">

Clicking "Escape" a second time closes the command menu.

### Expected Behavior

The command menu should close upon the first press of the "Escape" key.

### Operating System [e.g., Windows 10]

MAC OS 17.1

### Browser [e.g., Chrome, Firefox]

Arc (Chromium based browser)

### Version [e.g., 2.0.1]

1.33.0

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Looks like this is due to two command windows opening instead of the one which is weird. Happy to have you work on it!

**Comment by deepgolani4** [comment]
@Mythie, I accidentally unassigned this task from myself.
 Could you please assign it back to me? 
 Thank you
