### ISSUE TITLE
TRPCClientError: We were unable to sign this field. Please try again later.

### ISSUE THREAD

**Issue by paligiannis** [documenso/documenso#1038]
### Issue Description

I have established an new docker instance and running in under a reverse proxy. Everything works correctly but there is issue after trying to sign a document. A error rises. 

### Steps to Reproduce

1. Deploy docker containers with the production configuration
2. Adding p12 files to /opt/documenso/cert.p12 by running
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj /CN=domain.com
openssl pkcs12 -export -in cert.pem -inkey key.pem -out myfile.p12 -name "Alias of cert"
3. Navigate and upload file
4. Sign it

### Expected Behavior

Uploading the file and sign it without problems

### Current Behavior

It throughs an error 

### Screenshots (optional)

<img width="1097" alt="Screenshot 2024-03-19 at 7 49 41 PM" src="https://github.com/documenso/documenso/assets/10850092/4dcf72d6-bcd7-4ddd-adce-dad1155ca7f1">

### Operating System [e.g., Windows 10]

Mac OS

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

v1.5.3-rc.1

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by paligiannis** [comment]
In the meantime, things I tried but no luck with the same problem to persist.

1. Recreating all the required files with the commands bellow
2. openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
3. used the phrasekey: taxes
4. openssl pkcs12 -export -out cert.p12 -inkey myKey.pem -in cert.pem
5. then I chmod 777 the cert.p12 file
6. Logged in to container console and check if it was accessible. After chmod the file it was accessible by the container
7. Redeployed my server with the new envs changing the following:
``` NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH = /opt/documenso/cert.p12 ```
``` NEXT_PRIVATE_SIGNING_PASSPHRASE = taxes ```

**Comment by paligiannis** [comment]
In the meantime, what I also tried but with no luck.

1. Recreating all the required files with the commands bellow from the let's encrypt certificates by navigating to ``` /etc/nginx/ssl-certificates  ```
2. Updating env file paths for the generated p12 file
3. Reading about [generating a p12 file from existing certs](https://stackoverflow.com/questions/63195304/difference-between-pem-crt-key-files). Also using [this url for info](https://community.letsencrypt.org/t/creating-a-pkcs-12/157883).
4. chmod the certs recursively so the container can access p12 generated from this command ``` openssl pkcs12 -export -in docs.domain.com.crt -inkey docs.domain.com.key -out cert.p12 ```
5. Confirming that the file is accessible from the container sh terminal
6. Reloading and redeploying the server
7. Issue persists

**Comment by paligiannis** [comment]
Completely my bad. [Everything for the solution is on signing.md](https://github.com/documenso/documenso/blob/main/SIGNING.md), I thought it was a file to be ignored then I read the contents.

**Comment by Mythie** [comment]
Hey awesome to know that you were able to resolve this yourself ❤️

**Comment by curiousgeorgios** [comment]
@paligiannis can I ask how you went about solving this? I've followed the same steps as signing.md and have the cert files generated but still no luck...
