### ISSUE TITLE
S3 storage Path

### ISSUE THREAD

**Issue by Hexcah** [documenso/documenso#1048]
### Issue Description

Hi,
I'm testing Documenso on Docker, but I have a problem with S3 storage,
I have a minio in version `2023-03-24T21:41:23Z` And when I try to upload a document via Documenso, I get an error, because it points to https://documenso.minio.domain.com/3/xxxxxxxxxxxx/my-pdf.pdf instead of something like https://minio.domain.com/documenso/xxxxxxxxxxxx/my-pdf.pdf (documenso is my bucket name).
Can you enlighten me a little here? 

### Steps to Reproduce

Production docker compose, `image: documenso/documenso:v1.5.3-rc.1`
S3 Storage, minio `2023-03-24T21:41:23Z`

```bash
# [[STORAGE]]
# OPTIONAL: Defines the storage transport to use. Available options: database (default) | s3
NEXT_PUBLIC_UPLOAD_TRANSPORT="s3"
# OPTIONAL: Defines the endpoint to use for the S3 storage transport. Relevant when using third-party S3-compatible providers.
NEXT_PRIVATE_UPLOAD_ENDPOINT="https://minio.domain.com"
# OPTIONAL: Defines the region to use for the S3 storage transport. Defaults to us-east-1.
NEXT_PRIVATE_UPLOAD_REGION="unknown" # Not set in Minio
# REQUIRED: Defines the bucket to use for the S3 storage transport.
NEXT_PRIVATE_UPLOAD_BUCKET="documenso"
# OPTIONAL: Defines the access key ID to use for the S3 storage transport.
NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID="xxxxxxxxxxx"
# OPTIONAL: Defines the secret access key to use for the S3 storage transport.
NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
``` 

### Expected Behavior

Being able to change bucket_name/URL order? 🥲

### Current Behavior

Can't

### Operating System [e.g., Windows 10]

Linux Mint 21.3

### Browser [e.g., Chrome, Firefox]

Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0

### Version [e.g., 2.0.1]

v1.5.3-rc.1

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [x] I want to work on creating a PR for this issue if approved

**Comment by elosi** [comment]
:+1:

**Comment by Hexcah** [comment]
Perhaps to look at the `aws-sdk/client-s3` library and the `s3ForcePathStyle` parameter?

**Comment by Hexcah** [comment]
Thanks for the speed, it works perfectly 👌

**Comment by jasjastone** [comment]
Hello @Mythie
Sorry to bother you, but am running minio on localhost(docker to be specific) and the end point URL is http://192.168.1.149:9000 the ip is the ip of my local computer and minio is accessible on the web and i have created a bucket name documenson but in documenson doesn't seems to work

here is the example request to **http://localhost:3000/api/v1/documents**
{
  "title": "Testing title",
  "externalId": "1234",
  "recipients": [
    {
      "name": "James",
      "email": "james@example.com",
      "role": "SIGNER"
    },
    {
      "name": "Stivie",
      "email": "stivie@example.com",
      "role": "SIGNER"
    }
  ],
  "meta": {
    "subject": "Testing",
    "message": "Test docu",
    "timezone": "Etc/UTC",
    "redirectUrl": "http://127.0.0.1:8000/app/sign-request",
    "signingOrder": "PARALLEL"
  },
  "authOptions": {
    "globalAccessAuth": "ACCOUNT",
    "globalActionAuth": "ACCOUNT"
  },
  "formValues": {}
}
return this response

{
  "message": "An error has occured while uploading the file"
}
here is the documenson variables for s3 on env
"NEXT_PUBLIC_UPLOAD_TRANSPORT=s3",
"NEXT_PRIVATE_UPLOAD_ENDPOINT=http://192.168.1.149:9000",
"NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE=true",
"NEXT_PRIVATE_UPLOAD_REGION=unknown",
"NEXT_PRIVATE_UPLOAD_BUCKET=documenso",
"NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID=documenson@123",
"NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY=documenson@123",

Your guidance is appreciated
