### ISSUE TITLE
[DOC-31] Register/ Login with Google

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#106]
* Allowing different Auth-Providers reduces friction in all instances of Documenso
* Google should be among the first to be implement for it's widespread use 

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-31](https://linear.app/documenso/issue/DOC-31/register-login-with-google)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-31](https://linear.app/documenso/issue/DOC-31/register-login-with-google)</sub>

**Comment by dephraiim** [comment]
@ElTimuro @Mythie I want to take this

**Comment by Mythie** [comment]
Sounds good! You should be able to follow https://next-auth.js.org/providers/google for the general implementation and then work on the styling within the login/register pages.

Be sure to follow google's branding guidelines, they're pretty lax and allow modifications as required: https://developers.google.com/identity/branding-guidelines
