### ISSUE TITLE
contribution to this project

### ISSUE THREAD

**Issue by edward7770** [documenso/documenso#1073]
### Describe the improvement you are suggesting in detail

Hello, I am Edward, and a full stack developer. I just saw project about hosting your github project on upwork. so I want to contribute to this project. I can start working right noe, if you let me know. I look forward to hearing from you. Thank you

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [ ] I have searched the existing issues and improvement suggestions to avoid duplication.
- [ ] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Hey, welcome! You can look into how to contribute here

https://github.com/documenso/documenso/blob/main/CONTRIBUTING.md
