### ISSUE TITLE
Adding time to the document table

### ISSUE THREAD

**Issue by kodermax** [documenso/documenso#1077]
### Feature Description

I suggest adding the time information to the document table.

![image](https://github.com/documenso/documenso/assets/590985/e98d0f79-88bb-4933-850c-3d21e4167a94)

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by rushatgabhane** [comment]
hey, i would like to work on this if this feature is accepted

**Comment by ElTimuro** [comment]
@rushatgabhane makes sense, you got it

**Comment by rushatgabhane** [comment]
PR is up! https://github.com/documenso/documenso/pull/1123
