### ISSUE TITLE
[Bug] Old data is passed to the trigger function

### ISSUE THREAD

**Issue by kodermax** [documenso/documenso#1088]
document Data.data contains a non-final signed file.

https://github.com/documenso/documenso/blob/fc70f78e617ad192fc5c482b6f89f885311d37bb/packages/lib/server-only/document/seal-document.ts#L158

**Comment by catalinpit** [comment]
Good catch! Thanks!

I could swear I updated the doc before sending it, but it seems it's only done in `packages/lib/server-only/document/complete-document-with-token.ts` and `packages/lib/server-only/document/send-document.tsx`.

Will fix this.

**Comment by catalinpit** [comment]
@kodermax can you actually tell me what issue did you encounter, please? How did you figure that it contains a "non-final signed" file?
