### ISSUE TITLE
Ctrl + K opens double command menu

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#1093]
- Opening the search/ jump to command window via CTRL + K opens it twice
- Doing it by clicking on the search bar doesn't

https://github.com/documenso/documenso/assets/1309312/23650890-487a-4912-b7e7-25eff9a12433

**Comment by dguyen** [comment]
Already been worked on here

https://github.com/documenso/documenso/issues/1032

**Comment by ElTimuro** [comment]
neat wasnt aware :)
