### ISSUE TITLE
[DOC-230] Signature Workflow

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#112]
* Signatures never exist in a vacuum
* The workflow around the signature is an important part of the domain
* Recognizing that we want Documenso to support flexible workflow types to enable all kinds of real-life flow
* Some fundamental types and rules for workflows are: Signing order, Parallel or sequential signing
* Defining Subsitue signer for a step in the workflow

This feature will heavily integrate with the team inbox

**Comment by daallgeier** [comment]
These workflows will be a pre-requisit for many organisations out there to complete a switch.

**Comment by ElTimuro** [comment]
Moved to Q1, but a roles could be a possibility for EOY

**Comment by harkiratsm** [comment]
Are we moving in the direction of managing the actions of each recipient?

![image](https://github.com/documenso/documenso/assets/71957674/bb7acb37-d920-44e1-b7ba-11b5c079937d)

**Comment by ElTimuro** [comment]
@harkiratsm we already merged the roles into main 👀 rescoping this to advanced workflows using ordering

**Comment by ElTimuro** [comment]
Rescoping to advanced workflows and moving to longterm roadmap

**Comment by yl-chow** [comment]
Was looking forward to having this feature as it is a crucial part for our organisation. Hope this gets prioritised again.

**Comment by ElTimuro** [comment]
> Hey guys, bumping this up since it is a very interesting feature that is worth prioritising. Mostly the Parallel or sequential signing.

noted. Any particular use cases for each? would love to learn

**Comment by ElTimuro** [comment]
- Thanks for sharing 🙏
- The sequential case makes sense
- Parallel is what we currently have, and interesting question is, if combining the two makes sense or if that's just too complex: e.g. 1 persons signs, then 1 approves, then 3 people do things in parallel

**Comment by ElTimuro** [comment]
- Yes, sequential should be the first thing to be released, since it's the most impactful and common I would expect

**Comment by Mythie** [comment]
We now support parallel, sequential and signing orders! 

Docs need an update though 🥵
