### ISSUE TITLE
[DOC-229] Embeddable React Components/ iFrame Embedding

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#115]
## Requirements
* * Ready-to-use components to embed and integrate will be a core pillar of Documenso's tech stack
* Ready-to-use, beautiful react components can be integrated into web apps
* Native android and iOS comments are possible if the demand is there
* Basics iFrame can be used for simpler scenarios
* Accessible via NPM
* White-labeled and seamless on your site
* Template Enabled: Generate a new Document Instance for the template associated with the component on the fly, when the user signs it

## Potential user voices
- https://discord.com/channels/1132216843537485854/1265687690188165130/1265689531496140921

**Comment by ElTimuro** [comment]
High Priority since sales relevant

**Comment by ThcDelux3** [comment]
Planned release date on this? When this works i have 100 usecases for Documenso. Really important USP.

**Comment by ephraimduncan** [comment]
Hi, @ThcDelux3, this has been released. You can read the blogpost on it here:

https://documenso.com/blog/introducing-embedding

**Comment by ElTimuro** [comment]
Closing as we are doing whitelabel part seperate and this is done
