### ISSUE TITLE
private dependencies

### ISSUE THREAD

**Issue by thebadking** [documenso/documenso#1166]
### Issue Description

<img width="569" alt="image" src="https://github.com/documenso/documenso/assets/53491595/ed4295d2-6f3a-4bc0-91a6-a959c63a8c58">

I'm trying to test locally to run the web and I can't install the dependencies as they seem to be stored privately somewhere...

### Operating System [e.g., Windows 10]

Any

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey there, they're part of the monorepo. You should be able to just use `npm run d` to get setup locally provided you're on Node >= 18 😄
