### ISSUE TITLE
Copy signing link to send to recipients

### ISSUE THREAD

**Issue by TaylorHo** [documenso/documenso#1169]
### Describe the improvement you are suggesting in detail

Actually, as I could see in the Dashboard, I can only re-send the email for recipients to sign the document. It would be great to have an option to copy the signing link to send directly to the recipient.
This improvement is a way to avoid the default emails going to Span (it happened to me).
The copy link option could be in the document submenu.

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by TaylorHo** [comment]
Oh, I found the option now, I need to click in the signer email to copy the link. It's nice to have an option for this, but I also suggest having this same option in the submenu, since it's easiest to find this information there - it's the place where people look into it.

What do you guys think of it?

**Comment by dguyen** [comment]
Hey, sorry for the delayed response

That's a good idea, we'll ask our designer work on this and will try get it in soon

**Comment by myspace20** [comment]
Hello, I would like to work on this feature.

**Comment by TaylorHo** [comment]
Go ahead @myspace20, I haven't done anything on it yet, and I think that @dguyen hasn't either.

**Comment by myspace20** [comment]
Okay

**Comment by ephraimduncan** [comment]
Closing this as you can currently do that with the current version.
