### ISSUE TITLE
[DOC-262] [DOC-234] Simple Electronic Signature (SES) - eIDAS Level 1 Compliance

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#118]
<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-234](https://linear.app/documenso/issue/DOC-234/simple-electronic-signature-ses-eidas-level-1-compliance)</sub>

<sub>[DOC-262](https://linear.app/documenso/issue/DOC-262/[doc-234]-simple-electronic-signature-ses-eidas-level-1-compliance)</sub>

**Comment by dephraiim** [comment]
🚀 🚀
