### ISSUE TITLE
Enhance User Experience by Moving Dark Mode/Light Mode Toggle to the Top

### ISSUE THREAD

**Issue by Chetan0724** [documenso/documenso#1187]
### Describe the improvement you are suggesting in detail

The dark mode/light mode option is available at the bottom after users visit the entire site. For a better experience, please provide this option at the top.

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Hello! 

Thanks for the suggestion, but we currently have no plans to move the toggle to the top since we believe that using the user's system preference as the default is sufficient to not require the toggle in a predominant position.
