### ISSUE TITLE
[DOC-227] Document Templates

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#121]
* Similar types often documents are often sent more than one time therefore it makes sense to reduce the recurring effort to create those documents
* A basic template would define: An uploaded Document, some fixed signers, some fixed fields
* Templates should be usable via UI and later via API
* This mechanism will later tie in with the open document template library: https://github.com/documenso/backlog/issues/3

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-227](https://linear.app/documenso/issue/DOC-227/document-templates)</sub>

**Comment by WYNNGATE** [comment]
Ditto
