### ISSUE TITLE
Custom Text field with predefined label/caption

### ISSUE THREAD

**Issue by Rainson12** [documenso/documenso#1230]
### Feature Description

As a Signer I would like to know what I should enter in the `Custom Text` field as it always is presented as `Text`. For example, should I enter my Company name? My Position? My cars license plate?

### Use Case

A common scenario is to ask for the Title/Position of the Signer (eg. CEO/VP etc.). When now sending a request for Signing it will show `Signature` and `Text` where as the User doesnt know what the `Text` stands for. This is especially usefull when defining templates.

Currently it looks like:
![image](https://github.com/user-attachments/assets/57a81c75-90d7-42d6-ae36-7f4891d57042)

Instead it should look like this:
![image](https://github.com/user-attachments/assets/fc1bdbda-75b8-4f62-8ead-575269044954)

### Proposed Solution

When adding a custom text field, also define a caption what will be shown to the user/signer. This way the user knows what has to be entered in such field. 

### Alternatives (optional)

Configure / Define static fields in an administration interface. Like one for `Position` or `Title`. 

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Rainson12** [comment]
Seems that there is already a branch: https://github.com/documenso/documenso/tree/feat/more-field-types
and PR https://github.com/documenso/documenso/pull/1141 for this although I couldn't find any issue. I will close this for now

**Comment by ElTimuro** [comment]
@Rainson12 This was on our internal roadmap, as we like to tackle core features via the core team. Still great thinking. It's been a while, advanced fields will land very soon.
