### ISSUE TITLE
update docker/production/compose.yml

### ISSUE THREAD

**Issue by TSP-Dev** [documenso/documenso#1258]
### Issue Description

docker compose file docker/production/compose.yml it's not updated in relation, at least, to new background job features.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Docker should be syncing correctly with releases
