### ISSUE TITLE
Field data is not shown when editing templates

### ISSUE THREAD

**Issue by matevz-spacapan** [documenso/documenso#1259]
### Issue Description

When editing template fields, all data of each already present field should show everything that was previously saved in it, however these fields all appear empty.
If editing is cancelled, the data is still shown when sending templates for signing.

### Steps to Reproduce

1. Create a template
2. Create some field, e.g. text/checkbox/radio button and fill it with data
3. Save the template
4. Edit the template (go to the fields step)
5. Observe all fields have no data from step 2

### Expected Behavior

Fields should show all data associated with them when editing templates

### Current Behavior

For all field types the optional data (i.e. labels, placeholders, checkbox/radio button data,...) is not visible when **editing template fields**.

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

127.0.6533.72

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by mittalsam98** [comment]
I would love to pick this up if approved
