### ISSUE TITLE
Error: Failed to send the confirmation email

### ISSUE THREAD

**Issue by mnbro** [documenso/documenso#1264]
### Issue Description

Hi,

I 've just deployed a new instance of documenso but Im not able to send any email(not even the confirmation email).

I receive the next error:

`[JOBS]: Job send.signup.confirmation.email failed Error: Failed to send the confirmation email
    at u (/app/apps/web/.next/server/chunks/267.js:1:19105)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/app/apps/web/.next/server/chunks/267.js:1:14158)
    at async /app/apps/web/.next/server/chunks/267.js:1:10229`

Here are my SMTP settings:

      NEXT_PRIVATE_SMTP_TRANSPORT: "smtp-auth"
      NEXT_PRIVATE_SMTP_HOST: "smtp.sendgrid.net"
      NEXT_PRIVATE_SMTP_PORT: 587
      NEXT_PRIVATE_SMTP_SECURE: "true"
      NEXT_PRIVATE_SMTP_USERNAME: "apikey"
      NEXT_PRIVATE_SMTP_PASSWORD: "xxxx"
      NEXT_PRIVATE_SMTP_FROM_NAME: "XXXX"
      NEXT_PRIVATE_SMTP_FROM_ADDRESS: "XXXXX"

I've tried also with other mail providers and also with different ports/TLS on/off but I get the same error. 

Is there something obvious that I'm missing?

### Steps to Reproduce

Create a new "Sign-up"

### Expected Behavior

I should be able to send an email.

### Current Behavior

No email is being sent.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by viniciusbrun-dev** [comment]
Hello! I have the same problem and couldn't solve it so far. Any other ideas?

**Comment by lhjt** [comment]
I had this issue - turns out I was missing the `NEXT_PRIVATE_SMTP_SECURE=true` in my environment variables. Hope this might work for you @viniciusbrun-dev

**Comment by mngsgoncalves** [comment]
I'm not able to send the confirmation e-mail as well - the password recovery one works just fine.
