### ISSUE TITLE
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH should have the default value of /opt/documenso/cert.p12

### ISSUE THREAD

**Issue by mnbro** [documenso/documenso#1265]
https://github.com/documenso/documenso/blob/909c38f47e9cc2e852d78ca7f6187d8659d866cf/packages/signing/transports/local-cert.ts#L32

If `NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH` is empty the above line determines the default location, so a new/fresh install will fail even if in the documentation is specified the [next](https://docs.documenso.com/developers/self-hosting/how-to#:~:text=NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH,documenso/cert.p12)

**Comment by binary-amigo** [comment]
Hello, Can you assign this to me. Looking for a first contribution in the org.

**Comment by ephraimduncan** [comment]
@binary-amigo I'll go ahead and assign this to you
