### ISSUE TITLE
No Signing emails send because docker container doesn't reach NEXT_PUBLIC_WEBAPP_URL

### ISSUE THREAD

**Issue by david-loe** [documenso/documenso#1289]
### Issue Description

Since signing emails are send via backgroud jobs, no signing emails are send any more.
_Using resend works, because this is no background job._

Figured out that my container doesn't reach NEXT_PUBLIC_WEBAPP_URL. But no Error is thrown...

### Steps to Reproduce

1. Setup production documenso by docker compose
2. Add document
-> no email send and no error thrown

### Expected Behavior

Email send or at least an error

### Current Behavior

no email, no error

### Operating System [e.g., Windows 10]

Docker

### Version [e.g., 2.0.1]

1.6.1

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by david-loe** [comment]
#1258 maybe related 🤷‍♂️

**Comment by david-loe** [comment]
My Container sits behind a apache reverse proxy, and querying the `NEXT_PUBLIC_WEBAPP_URL` results in a loopback-problem (Hairpin NAT).
Possible Solution would be to introduce a new ENV variable like `NEXT_PRIVATE_INTERNAL_WEBAPP_URL` which is the same as `NEXT_PUBLIC_WEBAPP_URL` by default. This url will than be used every time the container wonts to make request to itself.

**Comment by apsinghdev** [comment]
@david-loe I faced the same issue. To fix that I have to run `npm run dx:up` along with other commands of manual setup.

**Comment by RobertPosluszny** [comment]
Confirming we are having the issue as well with Nginx proxy manager. With NEXT_PUBLIC_WEBAPP_URL set to our public URL, we are unable to send signup emails. With NEXT_PUBLIC_WEBAPP_URL set to the internal "http://localhost:3000" address it will send properly but then users are unable to confirm their email because the verify email URL is set to localhost and not the public URL.
