### ISSUE TITLE
New user not redirected to `/dashboard`

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#131]
- When a user creates a new account on the `/signup`, the user should be redirected to the `/dashboard` on completion
- A logged-in user is able to access `/signup` and `/login`. Logged In users should be redirected to the `/dashboard`
- When a user is logged in, they can create another user account, whilst logged in.

**Comment by ElTimuro** [comment]
Oh, you are right, but should detect the login state and redirect to dashboard.
