### ISSUE TITLE
Visiting a Deleted Document Signing link leads to Server Side Error

### ISSUE THREAD

**Issue by Nneji123** [documenso/documenso#1387]
### Issue Description

While testing I was deleting old contracts that were not signed so as to not fill up the month quota on the free plan. I noticed if I go to my emails and click on the the now deleted document signing link, the page displays an application server side error. 

Would be better if it was a 404 error.

### Steps to Reproduce

Create a document and add signees.
Delete the document before signing.
Go to email and click on document signing link.

### Expected Behavior

The expected behavior would be for the user to see a 404 error page.

### Current Behavior

Throws Application server side error

### Screenshots (optional)

https://github.com/user-attachments/assets/133d01cb-a6ed-4cd8-a9f0-6cb0fab3424f

### Operating System [e.g., Windows 10]

Android

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

Latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by dguyen** [comment]
Thanks for finding this!
