### ISSUE TITLE
Optional text fields are still required

### ISSUE THREAD

**Issue by jsbrain** [documenso/documenso#1389]
### Issue Description

Even though text fields are not set to required, for filling out a document with a text field still requires to click and fill each field to continue. This even happens when adding a pre-filled value to a field.

### Steps to Reproduce

Add a text field to any document

### Expected Behavior

Text field not marked as required will not require input

### Current Behavior

Text field not marked as required does require input

### Version [e.g., 2.0.1]

1.7.1-rc.3

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by catalinpit** [comment]
Hey @jsbrain, thanks for reporting this. I'll pick this next!
