### ISSUE TITLE
Certificate path mismatch

### ISSUE THREAD

**Issue by ificiana** [documenso/documenso#1397]
### Issue Description

I followed https://docs.documenso.com/developers/local-development/signing-certificate to generate a local p12 file and placed it at `/apps/web/resources/certificate.p12` but it failed to sign the document (I also made sure to delete the example cert.p12)

Then after some digging into the source code I found that the default place the service looks for is at `/opt/documenso/cert.p12`.

Is this a bug in the guide or did I miss something? 
Thanks in advance, cheers

### Version [e.g., 2.0.1]

Latest source code

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by dguyen** [comment]
Sorry for the delayed response, are you still having issues with this?

Assuming you're running this locally without docker, you can use the `NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH` path to set where your certificate is

The documentation is a bit outdated, we will update it shortly

**Comment by ificiana** [comment]
@dguyen Thanks for the response. In our project, we ended up using the `NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS` variable instead of a p12 file.
