### ISSUE TITLE
Signing order incorrect (nobody can sign)

### ISSUE THREAD

**Issue by matevz-spacapan** [documenso/documenso#1398]
### Issue Description

If you use a template and select the "Send document" checkbox, the signing order is not correctly applied, and nobody seems to be able to sign the document.
If I then edit the document, the signing order will be different from what is in the template.
Reordering the order after initially sending the document doesn't correct it either.

### Steps to Reproduce

1. Create a document template with two or more people
2. Go to the template list and select the Use template option
3. Select the Send document checkbox
4. Create and send

### Expected Behavior

The signing order should be correctly applied.

### Current Behavior

The signing order is not the same as in the template. Nobody can sign the document (everyone sees the wait for your turn error).

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

129.0.6668.101

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ephraimduncan** [comment]
Hello @matevz-spacapan, I've attempted to reproduce the issue you reported by following the steps you provided, but I've been unsuccessful in both the production environment and on the main branch.

- Which version of Documenso are you currently using? You mistook the question for the browser version 😄
- Are you self-hosting the application, or using a hosted instance?
- Have you encountered any specific error messages related to this issue?

**Comment by matevz-spacapan** [comment]
Hey, @ephraimduncan! I'm running a self-hosted Docker instance on the [latest tag](https://hub.docker.com/layers/documenso/documenso/latest/images/sha256-e32e1f8f4eca489b57a37dd53b0455bad023912fa4e82e7bc9f9b4d0c302725a?context=explore). I didn't see any errors in the console or logs.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ArbiterGR** [comment]
Same issue on my installation as well. I'm using a self hosted instance too. I see there's a PR for this issue. Would it be possible to get it merged before 1.7.2 stable?

**Comment by dguyen** [comment]
The fix is merged into main, and will be released in the next rc and stable release
