### ISSUE TITLE
[Docker Image] release candidates get tagged as latest

### ISSUE THREAD

**Issue by david-loe** [documenso/documenso#1404]
### Issue Description

I just noted that my documenso instance is running a rc version, I just pulled the `documenso/documenso` image and was expecting to get the latest stable release.

### Steps to Reproduce

`docker pull documenso/documenso`

### Expected Behavior

rc images should not be tagged as latest!

### Screenshots (optional)

![grafik](https://github.com/user-attachments/assets/c68316bb-6372-48fd-98be-f876438872e7)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by david-loe** [comment]
@dguyen what is missing to merge the pull request #1405 ?
