### ISSUE TITLE
Custom email message not working from a team. Subject is working.

### ISSUE THREAD

**Issue by RobertPosluszny** [documenso/documenso#1413]
### Issue Description

When sending an email from a team, the custom email message is not showing up properly. Instead, it will show a message like this: "{User} on behalf of {Team Name} has invited you to sign the document "1.pdf".

### Steps to Reproduce

Sending an email with a custom email message from a personal account works as expected. But sending an email with a custom email message from a team shows the message above.

### Expected Behavior

The custom email message entered should be shown instead.

### Screenshots (optional)

Unable to share screenshots due to PII

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

v1.7.2-rc.0

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ArbiterGR** [comment]
Hello, i want to add here that the same issue exists when using a template. No matter what we type in the custom email body, we just get the default one in the email.
