### ISSUE TITLE
Delete button remains disabled when using French prompt

### ISSUE THREAD

**Issue by Eblancho** [documenso/documenso#1426]
### Issue Description

When attempting to delete a document using the French prompt, the system requires the user to type "supprimer". However, even after entering the correct text, the delete button remains disabled. In contrast, typing "delete" in English successfully enables the button and allows the document to be deleted.

### Steps to Reproduce

Navigate to the document management section.
Select a document you wish to delete.
In the confirmation dialog, enter "supprimer" in the text field like the french translation ask for.
Observe that the delete button remains disabled.
Now, enter "delete" in the same text field.
Notice that the delete button becomes enabled.

### Expected Behavior

Button was enable and i can delete my document

### Current Behavior

Button was disabled

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/5588700b-6873-4fd0-b3e2-985f2f211371)
![image](https://github.com/user-attachments/assets/9159ede6-d668-4078-aca8-d526eea0faa4)
![image](https://github.com/user-attachments/assets/e57a29bb-ba40-4e79-ad81-a9c3595d086a)

### Operating System [e.g., Windows 10]

W11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

I use SaSS version

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Thank you for finding this, we'll fix this soon
