### ISSUE TITLE
Lack of translation for the French version

### ISSUE THREAD

**Issue by Eblancho** [documenso/documenso#1428]
### Issue Description

Hello, it's me again and my bugs on the “baguette” version. 
It's not really a bug but some places lack translation and it's a little problem especially when it's in the part that directly addresses the recipients of the signature.
I'll detail it in the screenshots

### Steps to Reproduce

Simply use the SaaS application and go to the signature url /sign/:id

### Expected Behavior

The entire text translated into French

### Current Behavior

Not the entire text translated

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/befcb700-4ae5-4c9c-9052-ba2dc22929e1)
View Document -> "Consulter le document" or "Voir le document" But it's less professional

![image](https://github.com/user-attachments/assets/fef558f1-db59-48a9-aa14-cb209b2dae1f)
Page x of y -> Page 1 sur 8

![image](https://github.com/user-attachments/assets/e81f0c3b-4d7d-4e98-8636-19a6444a21c8)
In this case, I don't know if it's a bug or a “legal” intention, but if in doubt, I'll note it anyway.

By proceeding with your electronic signature, you acknowledge and consent that it will be used to sign the given document and holds the same legal validity as a handwritten signature. By completing the electronic signing process, you affirm your understanding and acceptance of these conditions.
->
En apposant votre signature électronique, vous reconnaissez et consentez à ce qu'elle soit utilisée pour signer le document en question et qu'elle ait la même validité juridique qu'une signature manuscrite. En complétant le processus de signature électronique, vous affirmez votre compréhension et votre acceptation de ces conditions.

### Operating System [e.g., Windows 10]

W11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

SaaS

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Hi @Eblancho

We're currently improving the translation coverage here #1427 which should address these issues soon!
