### ISSUE TITLE
Fix CLS for videos on landing page

### ISSUE THREAD

**Issue by tobimori** [documenso/documenso#1431]
### Steps to Reproduce

Reload the page (maybe use connection throttling) - the text from the following section jumps

### Expected Behavior

Don't

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ElTimuro** [comment]
@tobimori thanks for reporting. We are moving the marketing page to Framer currently, so I will just close this as the page will be depracted 👌
