### ISSUE TITLE
Search link to document not working when in team

### ISSUE THREAD

**Issue by jsbrain** [documenso/documenso#1452]
### Issue Description

When searching for a existing document in the search bar and trying to access the result via 'enter', the link will reference the personal team when the document is actually in a team. So the link will try to access the document in `/documents/ID` instead of `/t/my-team/documents/ID`.

### Version [e.g., 2.0.1]

1.7.1

### Please check the boxes that apply to this issue report.

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by catalinpit** [comment]
Hey @jsbrain, thanks for reporting this!

Do you mean the search bar at the top of the page? The one marked with number `1` in this picture?

![CleanShot 2024-11-07 at 12 00 38@2x](https://github.com/user-attachments/assets/dbd6ffcd-13db-459c-b713-da9bf42385c5)

We'll fix this asap!

**Comment by catalinpit** [comment]
> @catalinpit this is the one, yes!

Opened a PR for it, thanks!
