### ISSUE TITLE
Unable to compile: > Build failed because of webpack errors

### ISSUE THREAD

**Issue by griffonace** [documenso/documenso#1480]
### Issue Description

Hello, 
I'm trying to build the apps on Ubuntu VM 22.04 running on Azure. 
No matter what I did, I can't get it to build. due to webpack errors. 
Is there anything that I miss?

### Steps to Reproduce

git clone https://github.com/documenso/documenso.git
cd ./documenso
cp .env.example .env
npm install
npm run build:web

The output:

> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build:
> @documenso/web:build: ../../node_modules/pdf-lib/es/index.js + 155 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build:
> @documenso/web:build: ../../node_modules/recharts/es6/chart/BarChart.js + 36 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build:
> @documenso/web:build: ../../node_modules/recharts/es6/component/Text.js + 1 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build:
> @documenso/web:build:
> @documenso/web:build: > Build failed because of webpack errors
> @documenso/web:build: npm error Lifecycle script `build` failed with error:
> @documenso/web:build: npm error code 1
> @documenso/web:build: npm error path /home/hrnadmin/documenso/apps/web
> @documenso/web:build: npm error workspace @documenso/web@1.8.0-rc.2
> @documenso/web:build: npm error location /home/hrnadmin/documenso/apps/web
> @documenso/web:build: npm error command failed
> @documenso/web:build: npm error command sh -c npm run translate:extract --prefix ../../ && turbo run translate:compile >
> 
>  Tasks:    2 successful, 3 total
> Cached:    0 cached, 3 total
>   Time:    1m25.382s
> Failed:    @documenso/web#build

### Expected Behavior

Succesful build so i can run with:
npm run

### Current Behavior

Build failed because of webpack errors

### Operating System [e.g., Windows 10]

Ubuntu 22.04

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by griffonace** [comment]
Here is the full log if needed. 

> > @documenso/root@1.8.0-rc.2 build:web
> > turbo run build --filter=@documenso/web
> 
> • Packages in scope: @documenso/web
> • Running build in 1 packages
> • Remote caching disabled
> @documenso/prisma:prebuild: cache bypass, force executing cfa39ddaf5c88ed2
> @documenso/prisma:prebuild: 
> @documenso/prisma:prebuild: > @documenso/prisma@0.0.0 prebuild
> @documenso/prisma:prebuild: > prisma generate
> @documenso/prisma:prebuild: 
> @documenso/prisma:prebuild: Prisma schema loaded from schema.prisma
> @documenso/prisma:prebuild: 
> @documenso/prisma:prebuild: ✔ Generated Kysely types (1.8.0) to ./generated in 1.96s
> @documenso/prisma:prebuild: 
> @documenso/prisma:prebuild: ✔ Generated Prisma Client (v5.4.2) to ./../../node_modules/@prisma/client in 597ms
> @documenso/prisma:prebuild: 
> @documenso/prisma:prebuild: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
> @documenso/prisma:prebuild: ```
> @documenso/prisma:prebuild: import { PrismaClient } from '@prisma/client'
> @documenso/prisma:prebuild: const prisma = new PrismaClient()
> @documenso/prisma:prebuild: ```
> @documenso/prisma:prebuild: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
> @documenso/prisma:prebuild: ```
> @documenso/prisma:prebuild: import { PrismaClient } from '@prisma/client/edge'
> @documenso/prisma:prebuild: const prisma = new PrismaClient()
> @documenso/prisma:prebuild: ```
> @documenso/prisma:prebuild: 
> @documenso/prisma:prebuild: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
> @documenso/prisma:prebuild: 
> @documenso/prisma:build: cache miss, executing c805863b0dc6676f
> @documenso/prisma:build: 
> @documenso/prisma:build: > @documenso/prisma@0.0.0 prebuild
> @documenso/prisma:build: > prisma generate
> @documenso/prisma:build: 
> @documenso/prisma:build: Prisma schema loaded from schema.prisma
> @documenso/prisma:build: 
> @documenso/prisma:build: ✔ Generated Kysely types (1.8.0) to ./generated in 1.95s
> @documenso/prisma:build: 
> @documenso/prisma:build: ✔ Generated Prisma Client (v5.4.2) to ./../../node_modules/@prisma/client in 591ms
> @documenso/prisma:build: 
> @documenso/prisma:build: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
> @documenso/prisma:build: ```
> @documenso/prisma:build: import { PrismaClient } from '@prisma/client'
> @documenso/prisma:build: const prisma = new PrismaClient()
> @documenso/prisma:build: ```
> @documenso/prisma:build: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
> @documenso/prisma:build: ```
> @documenso/prisma:build: import { PrismaClient } from '@prisma/client/edge'
> @documenso/prisma:build: const prisma = new PrismaClient()
> @documenso/prisma:build: ```
> @documenso/prisma:build: 
> @documenso/prisma:build: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
> @documenso/prisma:build: 
> @documenso/prisma:build: 
> @documenso/prisma:build: > @documenso/prisma@0.0.0 build
> @documenso/prisma:build: > prisma generate
> @documenso/prisma:build: 
> @documenso/prisma:build: Prisma schema loaded from schema.prisma
> @documenso/prisma:build: 
> @documenso/prisma:build: ✔ Generated Kysely types (1.8.0) to ./generated in 1.92s
> @documenso/prisma:build: 
> @documenso/prisma:build: ✔ Generated Prisma Client (v5.4.2) to ./../../node_modules/@prisma/client in 588ms
> @documenso/prisma:build: 
> @documenso/prisma:build: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
> @documenso/prisma:build: ```
> @documenso/prisma:build: import { PrismaClient } from '@prisma/client'
> @documenso/prisma:build: const prisma = new PrismaClient()
> @documenso/prisma:build: ```
> @documenso/prisma:build: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
> @documenso/prisma:build: ```
> @documenso/prisma:build: import { PrismaClient } from '@prisma/client/edge'
> @documenso/prisma:build: const prisma = new PrismaClient()
> @documenso/prisma:build: ```
> @documenso/prisma:build: 
> @documenso/prisma:build: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
> @documenso/prisma:build: 
> @documenso/web:build: cache miss, executing ea3d083a9a6e065f
> @documenso/web:build: 
> @documenso/web:build: > @documenso/web@1.8.0-rc.2 build
> @documenso/web:build: > npm run translate:extract --prefix ../../ && turbo run translate:compile && next build
> @documenso/web:build: 
> @documenso/web:build: 
> @documenso/web:build: > @documenso/root@1.8.0-rc.2 translate:extract
> @documenso/web:build: > lingui extract
> @documenso/web:build: 
> @documenso/web:build: ✔ 
> @documenso/web:build: Catalog statistics for packages/lib/translations/{locale}/marketing: 
> @documenso/web:build: ┌─────────────┬─────────────┬─────────┐
> @documenso/web:build: │ Language    │ Total count │ Missing │
> @documenso/web:build: ├─────────────┼─────────────┼─────────┤
> @documenso/web:build: │ de          │     137     │    0    │
> @documenso/web:build: │ en (source) │     137     │    -    │
> @documenso/web:build: │ fr          │     137     │    0    │
> @documenso/web:build: │ es          │     137     │    0    │
> @documenso/web:build: └─────────────┴─────────────┴─────────┘
> @documenso/web:build: 
> @documenso/web:build: Catalog statistics for packages/lib/translations/{locale}/web: 
> @documenso/web:build: ┌─────────────┬─────────────┬─────────┐
> @documenso/web:build: │ Language    │ Total count │ Missing │
> @documenso/web:build: ├─────────────┼─────────────┼─────────┤
> @documenso/web:build: │ de          │    1097     │   11    │
> @documenso/web:build: │ en (source) │    1097     │    -    │
> @documenso/web:build: │ fr          │    1097     │   11    │
> @documenso/web:build: │ es          │    1097     │   11    │
> @documenso/web:build: └─────────────┴─────────────┴─────────┘
> @documenso/web:build: 
> @documenso/web:build: Catalog statistics for packages/lib/translations/{locale}/common: 
> @documenso/web:build: ┌─────────────┬─────────────┬─────────┐
> @documenso/web:build: │ Language    │ Total count │ Missing │
> @documenso/web:build: ├─────────────┼─────────────┼─────────┤
> @documenso/web:build: │ de          │     417     │   14    │
> @documenso/web:build: │ en (source) │     422     │    -    │
> @documenso/web:build: │ fr          │     417     │   14    │
> @documenso/web:build: │ es          │     417     │   14    │
> @documenso/web:build: └─────────────┴─────────────┴─────────┘
> @documenso/web:build: 
> @documenso/web:build: (use "npm run translate:extract" to update catalogs with new messages)
> @documenso/web:build: (use "npm run compile" to compile catalogs for production)
> @documenso/web:build: • Packages in scope: @documenso/web
> @documenso/web:build: • Running translate:compile in 1 packages
> @documenso/web:build: • Remote caching disabled
> @documenso/web:build: @documenso/web:translate:compile: cache bypass, force executing cd27209213a708ab
> @documenso/web:build: @documenso/web:translate:compile: 
> @documenso/web:build: @documenso/web:translate:compile: > @documenso/web@1.8.0-rc.2 translate:compile
> @documenso/web:build: @documenso/web:translate:compile: > lingui compile --typescript
> @documenso/web:build: @documenso/web:translate:compile: 
> @documenso/web:build: @documenso/web:translate:compile: Compiling message catalogs…
> @documenso/web:build: @documenso/web:translate:compile: Done!
> @documenso/web:build: 
> @documenso/web:build:  Tasks:    1 successful, 1 total
> @documenso/web:build: Cached:    0 cached, 1 total
> @documenso/web:build:   Time:    3.413s 
> @documenso/web:build: 
> @documenso/web:build:   ▲ Next.js 14.2.6
> @documenso/web:build:   - Experiments (use with caution):
> @documenso/web:build:     · swcPlugins
> @documenso/web:build:     · outputFileTracingRoot
> @documenso/web:build: 
> @documenso/web:build:    Creating an optimized production build ...
> @documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
> @documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (759kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
> @documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
> @documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (759kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
> @documenso/web:build: Failed to compile.
> @documenso/web:build: 
> @documenso/web:build: ./src/components/(dashboard)/layout/header.tsx + 11 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build: 
> @documenso/web:build: ../../node_modules/@hello-pangea/dnd/dist/dnd.esm.js + 33 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build: 
> @documenso/web:build: ../../node_modules/pdf-lib/es/index.js + 155 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build: 
> @documenso/web:build: ../../node_modules/recharts/es6/chart/BarChart.js + 36 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build: 
> @documenso/web:build: ../../node_modules/recharts/es6/component/Text.js + 1 modules
> @documenso/web:build: Unexpected end of JSON input
> @documenso/web:build: 
> @documenso/web:build: 
> @documenso/web:build: > Build failed because of webpack errors
> @documenso/web:build: npm error Lifecycle script `build` failed with error:
> @documenso/web:build: npm error code 1
> @documenso/web:build: npm error path /home/hrnadmin/documenso/apps/web
> @documenso/web:build: npm error workspace @documenso/web@1.8.0-rc.2
> @documenso/web:build: npm error location /home/hrnadmin/documenso/apps/web
> @documenso/web:build: npm error command failed
> @documenso/web:build: npm error command sh -c npm run translate:extract --prefix ../../ && turbo run translate:compile && next build
> 
>  Tasks:    2 successful, 3 total
> Cached:    0 cached, 3 total
>   Time:    1m25.382s 
> Failed:    @documenso/web#build
> 
>

**Comment by ephraimduncan** [comment]
can you run the following and let me know if you're facing the same error?

```bash
npm run reset:hard
npm run d
```

**Comment by griffonace** [comment]
yes. I already run 

> npm run reset:hard
> npm run d

still failed to compile due to webpack error. Seems to be something wrong with my compile environment. 
I just switched to run the docker image for now, and it runs fine. 

Thanks.
