### ISSUE TITLE
Email Not Working

### ISSUE THREAD

**Issue by itsahmadawais** [documenso/documenso#154]
I've added the SendGrid API details and also tried Google SMTP details but the email feature is not working. What could the possible issue and way to solve this issue?

**Comment by dephraiim** [comment]
When you set up the repo locally with docker, a local SMTP server will be available for you. 

Add this to your `.env` and you will be good to go
```
SMTP_MAIL_HOST=127.0.0.1
SMTP_MAIL_PORT=2500
SMTP_MAIL_USER=documenso
SMTP_MAIL_PASSWORD=password
```

**Comment by ashifkhn** [comment]
Can you elaborated the issue??

**Comment by itsahmadawais** [comment]
> Can you elaborate the issue??

I have added the SendGrid API and also tried Google SMTP for the email but none of them is working.

**Comment by dephraiim** [comment]
@itsahmadawais Do you have any logs?

**Comment by nikmartin** [comment]
You can have either `SENDGRID_API_KEY` set, `OR SMTP_MAIL_HOST` set in .env. If you have both set, SMTP_MAIL_HOST will take precedence sicne it's the last parameter to be read in packages/lib/mail/sendMail.ts:22

**Comment by Mythie** [comment]
Hi there, as others have mentioned any elaboration would be greatly appreciated!

If you're running Documenso locally using the `npm run dx` command it will use Inbucket by default which captures all SMTP traffic and keep it locally. 

A Web UI for this is visible at http://localhost:9000 I apologise for any confusion this may have caused and will on documenting it better.

**Comment by Mythie** [comment]
I've updated our documentation to include a troubleshooting section for SMTP traffic while running locally 😄 

If you're still encountering issues please let us know otherwise I'll close this off for now.
