### ISSUE TITLE
Settings on the navbar does not display profile on first click

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#16]
Clicking on Settings Opens

<img width="1212" alt="Screenshot 2023-03-20 at 14 28 40" src="https://user-images.githubusercontent.com/55143799/226376616-b5467445-0013-443b-b2b1-9b3307b9cf53.png">

Instead of 

<img width="742" alt="Screenshot 2023-03-20 at 14 28 49" src="https://user-images.githubusercontent.com/55143799/226376699-48914b48-b1c1-4ad1-ba23-c4b9fd9830c3.png">

**Comment by ElTimuro** [comment]
Now even more, since the starter view changed to empty after I filled the other tab

**Comment by ElTimuro** [comment]
Navbar could just link to the first tab (both tabs set links when clicked). You should check for side effects, but it should be fine IMO
