### ISSUE TITLE
Load fonts with `next/font` for no layout shift

### ISSUE THREAD

**Issue by leerob** [documenso/documenso#169]
https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

Source: https://github.com/documenso/documenso/blob/main/apps/web/styles/tailwind.css#L15-L40

**Comment by TheoOliveira** [comment]
Checking on that particular issue.

**Comment by TheoOliveira** [comment]
I can't think of anything besides wrapping app _app.ts with main tag, do you have any other suggestions?
