### ISSUE TITLE
Semantic release management

### ISSUE THREAD

**Issue by jwthanh** [documenso/documenso#180]
@ElTimuro Is it worth having the semantic release management that collects the pull requests and creates release notes for each version? If YES, I can contribute to that integration.

### References:
- https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration

**Comment by dephraiim** [comment]
Releases will probably start after v1. Working towards v1 at the moment, you can take a look at the [roadmap](https://github.com/documenso/documenso/milestones).

**Comment by Mythie** [comment]
How does this compare to something like [changesets](https://github.com/changesets/changesets)? My prior experience was with NX + Lerna and Conventional Commits so it was a bit more automatic.

As we near 1.0 and the future we will certainly want some automatic changelog and semver tooling so I'd love to hear your thoughts on the matter.

**Comment by jwthanh** [comment]
The changesets is new to me. The semantic release uses conventional commits for creating the release notes. It is popular and has 10x more stars than changesets.

**Comment by Mythie** [comment]
Thanks for the details! I had a look into it and it looks to be the direction that we will want to go.

Mind if I park this issue for the moment so we can resume as we get closer to 1.0? 😄

**Comment by Mythie** [comment]
We had integrated changesets and we do use conventional commits so we just need to actually work on the release management aspect of things.

**Comment by jwthanh** [comment]
@Mythie Do you need to manage multiple package releases or the entire web application in the mono repo?

**Comment by Rainson12** [comment]
how are release notes created right now?
