### ISSUE TITLE
A Signer can Sign Twice

### ISSUE THREAD

**Issue by daallgeier** [documenso/documenso#192]
### Issue Description
A signer seemingly can sign twice.  

### How to Replicate

1. Send Signature to signer 
2. As Signer click link once & Sign where prompted then complete
3. As Signer click link again & get prompted to set the signature field yourself
4. As Signer sign again and submit
5. As Signature Requester see two signatures from the same person

### Supporting Documents
See Document under ID 29 in app.documentso.com

**Comment by Mythie** [comment]
Thanks for flagging this, I could have sworn we had already done the work on this one but I'll get onto it right away!

We apologise for the inconvenience that this would have caused 💚

**Comment by Mythie** [comment]
Closing as this has been resolved
