### ISSUE TITLE
Consider a more accessible and space-friendly font like Inter or System

### ISSUE THREAD

**Issue by marcusquinn** [documenso/documenso#194]
1st: BIG fan of your work, already has a lot of votes on the Cloudron forum!

I can't help but notice the use of the Montserrat font, which appears a bit too quirky for an application interface, and I feel is more appropriate to marketing designs. The regular version is quite light for readability, too. It just reminds me of trying-too-hard-in-the-wrong-things open-source design.

I feel a font like Inter or just good-old System Fonts that match the user's OS, would give a more native app experience, and focus attention on the functionality.

Keep doing amazing things. Really hope you take this in the spirit of goodwill it's written with, and if in doubt, just trust me and try it :)

**Comment by Mythie** [comment]
We're working on a few design things behind the scenes right now and Montserrat has been swapped to Inter within that. This can be seen on the current landing page which also opts for Inter.

Thanks for the feedback and we're glad to have you around! 🤗

**Comment by doug-andrade** [comment]
Playing around with the app router some more, adding shadcn/ui, and inter -- it does look nice.

<img width="1654" alt="Screenshot 2023-06-06 at 11 34 35 PM" src="https://github.com/documenso/documenso/assets/16950308/e69e0b4c-4b03-46d6-a8de-346ad462c463">
<img width="1097" alt="Screenshot 2023-06-06 at 11 35 41 PM" src="https://github.com/documenso/documenso/assets/16950308/ebefa31c-79fc-4970-8d68-16fb210ffd9d">

**Comment by marcusquinn** [comment]
@Mythie @doug-andrade Great stuff! An excellent choice!

So much more space efficient and, like all the best designs, invisible, since it's the functionality that should shine through to the user.

Especially with legal documents, you want the receiver to feel confident in every way that they are interacting with a professional platform, so boring is reassuring in legal land.

What you're making is far from boring to me, very excited to see you shaking up this area of apps!

**Comment by marcusquinn** [comment]
As they say, good design is C.R.A.P. 💩 

Contrast
Repetition
Alignment
Proportion

**Comment by Mythie** [comment]
> @Mythie @doug-andrade Great stuff! An excellent choice!
> 
> So much more space efficient and, like all the best designs, invisible, since it's the functionality that should shine through to the user.
> 
> Especially with legal documents, you want the receiver to feel confident in every way that they are interacting with a professional platform, so boring is reassuring in legal land.
> 
> What you're making is far from boring to me, very excited to see you shaking up this area of apps!

This is exactly it, we want to build trust from the first interaction with a stunning design! Our goal for this current work is to improve the visuals of the application so admins are delighted and signers feel confident with the platform 😄

**Comment by Mythie** [comment]
Going to close this issue as we're already onto it, but thanks for your contribution 😄
