### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by david-loe** [documenso/documenso#202]
Localization would be nice to have, especially considering the date printed on the documents.

**Comment by Mythie** [comment]
Completely agree, while it might not be v1.0 I'd be aiming to do so in quick succession with it likely appearing a v1.1 release. 

Given that we will now be using Next13 with AppDir, I'm wondering if anyone has any cool suggestions for localization providers? I don't think we need to go down the NextIntl path and I'm not even sure if it's available yet for AppDir projects.

**Comment by nsylke** [comment]
I normally go with [i18next](https://www.i18next.com/) for localization, there is a couple ways it could be implemented, using routes to determine the language (`/en/dashboard`, `/de/dashboard`, etc.) or could use the Context API from React to allow the user to select the language without changing the route. Probably best to default to the `Accept-Language` header on either option.

**Comment by anikdhabal** [comment]
Hey @catalinpit @Mythie Can you assign me? I am willing to work on this.
