### ISSUE TITLE
Support file storage instead of storing in the database

### ISSUE THREAD

**Issue by jwthanh** [documenso/documenso#205]
@Mythie Do we plan to support file storage (e.g., AWS S3,...) instead of storing in the database?

**Comment by AliMejbar** [comment]
That would be great, even better would be to consider Cloudflare R2 because of free egress.

**Comment by Mythie** [comment]
Yep so I'd like to support S3 compatible providers for file storage and while also moving our current document storage to use native postgres `Blob`'s on a separate table to avoid TOAST'ing which will affect query performance in the future as a larger number of documents are stored.

By aiming for S3 compatibility we can include things like R2, S3, Azure Blob, Digital Ocean Spaces, Backblaze and more.

https://www.postgresql.org/docs/current/storage-toast.html

**Comment by Mythie** [comment]
S3 support has been added as part of our `universal-upload` feature so I'm happy to close this off as complete for now.

We're using S3 successfully in production to achieve encryption at rest with presigned urls being used to restrict access.
