### ISSUE TITLE
[DOC-287] REST API

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#223]
* Create, fill, and send documents to sign
* Get documents and their state
* Get Notified on events (creation, signing, etc.) via webhooks

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-287](https://linear.app/documenso/issue/DOC-287/rest-api)</sub>

**Comment by KIET7UKE** [comment]
Hi @ElTimuro ,

I'm eager to contribute to the REST API #223 issue. The tasks align perfectly with my API development skills. Could you share more about the tech stack and coding guidelines? Excited to get started!

Best,
Sahil Sharma
sharmasahil2468@gmail.com
https://linktr.ee/kiet7uke

**Comment by swastik959** [comment]
@ElTimuro as much as I understood you need platform agnostic apis to work with right??

**Comment by swastik959** [comment]
@ElTimuro is there anything at this moment that I can work on

**Comment by ElTimuro** [comment]
> @ElTimuro is there anything at this moment that I can work on

nothing specific, but issues from documen.so/mania keep coming in and we have a Hacktober tag to keep and eye on

**Comment by ElTimuro** [comment]
We are in the final testing stages for the API
