### ISSUE TITLE
ssl certificate

### ISSUE THREAD

**Issue by minty-joep** [documenso/documenso#230]
Hi all,
I tried to secure the webapp useing the 'Creating your own signing certificate' instruction but i get the following error. Can anyone help solve this problem?
In the attachements you will find a screenshot of the .env file and the error.
![Schermafbeelding 2023-07-20 101303](https://github.com/documenso/documenso/assets/122375064/5bff5662-d853-446a-afdb-e6e6f6caec46)
![Schermafbeelding 2023-07-20 101951](https://github.com/documenso/documenso/assets/122375064/990d205d-bd51-4e80-9640-502f5b89229a)

**Comment by ElTimuro** [comment]
Hey @minty-joep,

- SSL certificates are not meant for signing PDF; this could be the reason, but it could technically work.
- Where does the error message come from?

**Comment by Mythie** [comment]
Closing as stale, we will have more on this later.
