### ISSUE TITLE
latest release 0.9 fails to build

### ISSUE THREAD

**Issue by happysalada** [documenso/documenso#255]
Hi! I tried packaging this for nixos and got a build failure on linux.
```
Type error: Module '"@prisma/client"' has no exported member 'SubscriptionStatus'.
  1 | import { useSubscription } from "@documenso/lib/stripe"
  2 | import { PaperAirplaneIcon } from "@heroicons/react/24/outline";
> 3 | import { SubscriptionStatus } from '@prisma/client'
    |          ^
  4 | import Link from "next/link";
  5 | 
  6 | export const BillingWarning = () => {
ERROR: `npm build` failed
```
Are you considering making another release soon ?
[full details of the build](https://logs.ofborg.org/?key=nixos/nixpkgs.248647&attempt_id=b7b7adf1-a0fe-436b-9eb7-cb7b39d359b7)

**Comment by dephraiim** [comment]
Hi, have you tried 

```
npx prisma generate
```

**Comment by happysalada** [comment]
I had a look at the package-lock and couldn't find anything wrong with prisma.
I have used the workaround `npx prisma generate` for now.
I'll update this issue after prisma is updated to 5.0.

**Comment by Mythie** [comment]
Closing as we now have `Dockerfile` builds as part of our CI 😄
