### ISSUE TITLE
[DOC-295] Add commitlint for linting of commit messages

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#267]
As the project grows we need to work on enforcing consistency across various processes, one of these areas is commit messages and formatting.

To handle this we would like to use [commitlint](https://github.com/conventional-changelog/commitlint) in combination with [husky](https://github.com/typicode/husky) (which is already in the repo). Using commitlint we would like to enforce [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) which will require that commits be labelled based on the kind of change they are.

This change will help align the way we contribute to the project and also allow niceties with other tools for automated release notes and versioning.

Implementation of this change should be fairly straightforward, from memory there is a quick start that will assist with the implementation of most of this without any real trouble.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-295](https://linear.app/documenso/issue/DOC-295/add-commitlint-for-linting-of-commit-messages)</sub>

**Comment by Ashutosh-Bhadauriya** [comment]
@Mythie I would like to take this 🙂
/attempt #267
