### ISSUE TITLE
[DOC-296] Add changesets for automatic release versioning

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#268]
Following the work on the `feat/refresh` branch we will be in a state where we're releasing more often at which time versioning will become a large painpoint.

To alleviate this we would like to add [changesets](https://github.com/changesets/changesets) to our project which should help automatically determine versioning based on the commit history between releases.

Additionally we hope to use changesets for the generation of release notes which will be improved via the usage of conventional commits [DOC-295](https://linear.app/documenso/issue/DOC-295/add-commitlint-for-linting-of-commit-messages) #267

I personally have used [Lerna](https://github.com/lerna/lerna) in the past for a similar purpose but given we've opted to use turborepo for this project it's no longer relevant.

We are open to alternate tools to use but they must be able to do the above in a semi-painless fashion.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-296](https://linear.app/documenso/issue/DOC-296/add-changesets-for-automatic-release-versioning)</sub>

**Comment by rishi-raj-jain** [comment]
@Mythie 

The first part here is to add changesets, and can you explain the second one in detail?

**Comment by Mythie** [comment]
G'day the primary goal is to add changesets, we have another issue for implementing conventional commits and such which should make changesets more valuable when it comes to release note generation and versioning.

**Comment by rishi-raj-jain** [comment]
Ah aight, I'll be on adding the changesets!

**Comment by rishi-raj-jain** [comment]
Thank you @Mythie 😍
