### ISSUE TITLE
Add a Github Issue form

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [documenso/documenso#274]
Opening issues should not be boring and vague. So therefore we need to add a structured form with easy-to-follow steps, encouraging contributors to capture every important detail.

**Comment by Mythie** [comment]
100% agree! I'll add them in just a moment 😎

**Comment by Mythie** [comment]
Added as part of 2d5727cab29a169f3efc3408759d7ac17e8f62cc 😎
