### ISSUE TITLE
For Every add Signer without a email, we are storing empty values in DB

### ISSUE THREAD

**Issue by yashug** [documenso/documenso#277]
Whenever an additional signer is added without an associated email, we're currently storing empty values in the database. This is causing issues with unidentified emails and subsequently displaying an incorrect count of recipients

![Screenshot 2023-08-18 at 6 38 40 PM](https://github.com/documenso/documenso/assets/14201280/a7d7b90b-5f6f-4587-8dbf-a923cda801b5)
![Screenshot 2023-08-18 at 6 41 01 PM](https://github.com/documenso/documenso/assets/14201280/d828403d-203a-41ea-9501-12c8186f8090)

**Comment by Diogovski** [comment]
This easy to fix on the displaying part, for that specific display changing this 
`{props?.recipients.map(
                (recipient: any) =><Listbox.Option></Listbox.Option>)}
`
                
to this:
`{props?.recipients.map( (recipient: any) =>recipient?.email?.length > 1 && (<Listbox.Option></Listbox.Option>))}
`

fixes the issue, but it shouldnt even be allowed to save empty signers in first place! Can anyone from the team suggest a change, we can either fix the displaying errors with an if condition( check for empy emails ) or we can change the way the signers are saved in the db.

**Comment by adithyaakrishna** [comment]
@Diogovski IMO this wouldn't be the right way to fix it. We can use isEmpty condition with a ternary operator

**Comment by vinaybadgujar102** [comment]
I can work on this issue

**Comment by Hallidayo** [comment]
Hi all, seems this issue is fixed in the `feat/refresh` branch

**Comment by Mythie** [comment]
Closing as this has been fixed in 1.0 as mentioned above 😄
