### ISSUE TITLE
Inconsistent spacing of nav links and incorrect discord icon in footer

### ISSUE THREAD

**Issue by yeganathan18** [documenso/documenso#281]
# Improvement

## Link 

Website: https://documenso.com/

## Describe the problem

- The spacing between the nav links isn’t consistent and looks like clustered
- Discord icon in the footer social links is incorrect

## Describe the improvement

- Should consider increasing the space between the nav links so that it looks consistent
- Regarding the icon, If the `lib` we use doesn’t have it, we can copy the SVG and create it as a component.

## Additional context

Here's the screenshot 👇🏻 

<img width="1792" alt="Screenshot 2023-08-19 at 2 18 57 PM" src="https://github.com/documenso/documenso/assets/63534555/9f2f1190-a780-4e75-8f7c-8e0847c4f388">

**Comment by kunal70006** [comment]
I think the discord one is intentional also I checked the nav links, and they're using flex gap so that is also consistent, can you take another look?

**Comment by adithyaakrishna** [comment]
@yeganathan18 I guess the spacing is accurate/exact. Here's a screenshot to depict the same. IMO the logo has a padding so this might not be a bug

<img width="389" alt="Screenshot 2023-08-19 at 11 42 53 PM" src="https://github.com/documenso/documenso/assets/23498248/26e06b59-1237-4f45-bc4d-dfeb4deb4070">

**Comment by yeganathan18** [comment]
@kunal70006 Inconsistent in the sense, the nav links are close to each other, maybe a bit of space should fix that. And also, discord logo is kinda different and not the actual one.

**Comment by yeganathan18** [comment]
@adithyaakrishna I think you're looking at the wrong place and sorry if my issue description is bit confusing. 

Here's what I mean,

The nav links in the navbar of the site are too close to each other and maybe a bit of spacing between those should look good. Again with discord icon, the logo doesn't depict discord exactly, and it would be great if we add the appropriate one

**Comment by kunal70006** [comment]
> @kunal70006 Inconsistent in the sense, the nav links are close to each other, maybe a bit of space should fix that. And also, discord logo is kinda different and not the actual one.

@yeganathan18 both of these are pretty subjective I guess because the spacing seems fine to me, same with the discord logo, it could be a deliberate design decision.

**Comment by Mythie** [comment]
@yeganathan18 You're right that they're too tight together at the top, this was mostly me being lazy and not wanting to add a hamburger menu since they annoy me. Fortunately #271 adds a menu which I'll be looking at very shortly 😄

**Comment by premiare** [comment]
Discord icon has been replaced in #248 - as mentioned in the PR description, I tried to use a Discord icon that would match the other (Lucide) icons as best as possible.

**Comment by Mythie** [comment]
Closing as this has now been done 😄
