### ISSUE TITLE
Improvement: User Avatar

### ISSUE THREAD

**Issue by Hussainzz** [documenso/documenso#288]
## Improvement Description
Instead of using the `avatar-from-initials` package, why not consider using the well-known `@radix-ui/react-avatar` ? This package allows us to use avatars with profile images and also provides a way to display fallback text, in our case, the user's name initials.

## Proposed Solution
I have implemented a UserAvatar component below are the screenshots

<img src="https://github.com/documenso/documenso/assets/13753141/34af1307-9672-4cd9-b23e-21209dc31a82" alt="Alt Text" width="600" height="400">

<img src="https://github.com/documenso/documenso/assets/13753141/c82911b6-8a3e-48e9-a9e5-2a2f3905beb3" alt="Alt Text" width="400" height="600">

## Related PR
https://github.com/documenso/documenso/pull/287

**Comment by doug-andrade** [comment]
This issue has been addressed in the `feat/refresh` branch. However it's worth noting that it's currently not receiving `<AvatarImage />`

As far as I can tell, user.image has not yet been added to the prisma schema.

<img width="882" alt="image" src="https://github.com/documenso/documenso/assets/16950308/0a4dfcb4-7d5e-4135-a9c9-ba13be192eae">

**Comment by Hussainzz** [comment]
Oh great. Good to have that as a reusable component in UI package

**Comment by Mythie** [comment]
Closing as we do have this on feat/refresh as mentioned.
