### ISSUE TITLE
Improvement: Customer Alert Confirmation Dialog

### ISSUE THREAD

**Issue by Hussainzz** [documenso/documenso#291]
## Improvement Description
Suggesting a minor improvement. rather than using the normal confirm dialog. we should have some decent-looking Alert dialog confirmation.

```js
<IconButton
  icon={TrashIcon}
  onClick={(event: any) => {
    event.preventDefault();
    event.stopPropagation();
    //We should have something generic that we can reuse across our application
    if (confirm("Are you sure you want to delete this document")) {
      const documentsWithoutIndex = [...documents];
      const removedItem: any = documentsWithoutIndex.splice(index, 1);
      setDocuments(documentsWithoutIndex);
      deleteDocument(document.id)
        .catch((err) => {
          documentsWithoutIndex.splice(index, 0, removedItem);
          setDocuments(documentsWithoutIndex);
        })
        .then(() => {
          loadDocuments();
        });
    }
}}></IconButton>

```

## Proposed Solution

Implementing a generic confirmation using context. I can work on this. if this is assigned to me @Mythie @ElTimuro 

<img src="https://github.com/documenso/documenso/assets/13753141/43f38141-5931-49ae-84e1-331d61a71f74" alt="Alt Text" width="400" height="200">

**Comment by Mythie** [comment]
Closing as we have integrated custom alerts and dialogs as part of switching to shadcn/ui
