### ISSUE TITLE
signing certificate issues.

### ISSUE THREAD

**Issue by fenominal** [documenso/documenso#299]
## Issue Description
i crate my own signing certificate and place it /apps/web/resources/certificate.p12 as per instruction but get error like below.
even i replace my document with your default one certificate and run again it give same error.
![image](https://github.com/documenso/documenso/assets/53823351/8a71e39f-8eb4-45e7-9646-58a9ee43a409)

**Comment by adithyaakrishna** [comment]
Did you save the password while creating the certificate?

**Comment by fenominal** [comment]
i do setup in windows . So time of creating certificate it did not give me option to save password .
If i miss the step to save password it also should run with default certificate also.  it happen same for that .

**Comment by fenominal** [comment]
i do some process in ubuntu os . and than it give same error again.

![Screenshot from 2023-08-24 16-42-28](https://github.com/documenso/documenso/assets/53823351/e85e9065-9dc1-491e-b987-25d1e959d666)


see above image . that generate openssl certificate and it process is same .

@adithyaakrishna now you have any answer for it ?

**Comment by fenominal** [comment]
> try remove the certfile encoding.

@RenatoNr  if i can do . i never raise this issue here.

**Comment by adithyaakrishna** [comment]
@fenominal I kindly request you to be a bit kind and respectful towards other community members or contributors as most of us have a day-to-day job. @RenatoNr just gave a suggestion, and if it didn't work, you can convey that in a more politer way. Also, Lucas might also be busy with his work as the whole repo is getting revamped.

**Comment by Mythie** [comment]
> > try remove the certfile encoding.
> 
> @RenatoNr if i can do . i never raise this issue here.
> 
> @Mythie Please resolve it fast because i install fresh version of project in my machine and not change anything in for self sign document content it give same error.

G’day, can you provide the cert and document you’re using while encountering this issue?

Feel free to jump onto our discord where I’ll be able to receive the files with ease.

**Comment by fenominal** [comment]
> @fenominal I kindly request you to be a bit kind and respectful towards other community members or contributors as most of us have a day-to-day job. @RenatoNr just gave a suggestion, and if it didn't work, you can say that in a more politer way. Also, Lucas might also be busy with his work as the whole repo is getting revamped.

 buddy I am not disrespect any one here please read my comment again not  pointing and not make joke on any one. I also have day to day work . I am just pointing issues.

If pointing issues and mentioning any one here as consider as disrespect . so next time i am not here to find any bug . 

Thank You...

**Comment by fenominal** [comment]
@Mythie hello buddy their is issue in project . because i do fresh installation in new machine and i got error . if i do some mistake to generate certificate . But issue generate in fresh installation .

**Comment by Mythie** [comment]
Hey there, not sure if we're still encountering issues with this. If so please feel free to DM me on discord, given the majority of contributors haven't had the issue I'm closing this out for now.
