### ISSUE TITLE
Certain Functions Aren't Using NEXT_PUBLIC_WEBAPP_URL

### ISSUE THREAD

**Issue by melotte25** [documenso/documenso#302]
## Issue Description

When configuring `NEXT_PUBLIC_WEBAPP_URL` and `NEXTAUTH_URL`, various functions are still redirecting users to 'http://localhost:3000'

## Steps to Reproduce

1. Build docker image via `./docker/build.sh`
2. Deploy image to public cloud
3. Migrate DB
4. Use app

I did realize I didn't have `NEXT_PUBLIC_WEBAPP_URL` set during the first deployment, but it is currently set. Perhaps going through all 4 steps, defining `NEXT_PUBLIC_WEBAPP_URL`, and then re-deploying would be more accurate.

## Expected Behavior

All URLs should respect the `NEXT_PUBLIC_WEBAPP_URL` setting.

## Current Behavior

The `http://localhost:3000` is being used as the base URL for multiple pages, eg:
* `/signup` redirect
* Email template link
* Document edit

## Environment

- OS: Google Cloud Run
- Browser: Any
- Version: Build from commit [19ea119](https://github.com/documenso/documenso/commit/19ea119009c40c66395971781d5809859af51230)

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Mythie** [comment]
I believe that this should be resolved now.

**Comment by rishi-raj-jain** [comment]
Can I work on this?
