### ISSUE TITLE
Previous signature erased

### ISSUE THREAD

**Issue by Tawitwins** [documenso/documenso#311]
## Issue Description

When I upload a document with existing digital signature to the system to be sign. The initial signature disappear when signed through the platform. I realized that inviting two person to sign too does not have two digital signature to the document but only the last one.

## Steps to Reproduce

1. Upload a document with digital signature in it ([document.pdf](https://github.com/documenso/documenso/files/12446561/document.pdf))
2. Invite a person to sign the document
3. Complete the signing
4. Download document
5. Check signatory tab in any compliant viewer
6. ...

## Expected Behavior

See two digital signatures

## Current Behavior

Only see the last signature

## Screenshots (optional)
[document (2).pdf](https://github.com/documenso/documenso/files/12446564/document.2.pdf)

## Environment

- OS: [e.g., 5.15.0-79-generic #86-Ubuntu deployed with docker
- Browser: brave
- Version: 0.1

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by adityadeshlahre** [comment]
**Not able to reproduce**
OR
**Might it is fixed now**

Attached video below please verify it did steps correct or not :smile: 
As per my reading i did it correct.
Thank You
**[VIDEO]**
https://drive.google.com/file/d/14ZcjThVoeKkURTHoejIzc_C1YHKTPNVP/view?usp=sharing

**Document which is generated after signature**
[documentTEST.pdf](https://github.com/documenso/documenso/files/12747201/documentTEST.pdf)

**Comment by Mythie** [comment]
Hey there, sorry for the super long delay on this one! Awesome work on using a signing server to pre-sign a document.

You're correct in that the previous signature is blown away as it's currently a temporary limitation on our end. We intend to address this as we work on making our signing more robust on the PDF sealing side 😄

**Comment by lnguyen14123** [comment]
Hi, I am currently working on this.

**Comment by lnguyen14123** [comment]
Hi @Mythie and @Tawitwins,

Thank you for bringing up this issue. I'm eager to help resolve it, but I'm currently unable to reproduce the problem as described.

To assist in diagnosing the issue effectively, could you please provide more information on how I can reproduce it?

After following the reproducing steps originally posted, using Adobe Acrobat Reader I was able to see both signatures.

* What was the software that you used to view the signed pdf so that the previous signature was no longer there?

Thank you :)

**Comment by Tawitwins** [comment]
> **Not able to reproduce** OR **Might it is fixed now**
>  
> Attached video below please verify it did steps correct or not 😄 As per my reading i did it correct. Thank You **[VIDEO]** https://drive.google.com/file/d/14ZcjThVoeKkURTHoejIzc_C1YHKTPNVP/view?usp=sharing
> 
> **Document which is generated after signature** [documentTEST.pdf](https://github.com/documenso/documenso/files/12747201/documentTEST.pdf)

Sorry for the long dellay, the issue was regarding the actual "cryptographic signature" the viewer you used (embeded in the navigator) isn't typically able to read the signature.
But as the the annotation layer was completely overiden in my case and it doesn't seem to be the case in yours. I'll need 
 to test the new version from feat/refresh branch because I tested the platform before it became the default branch.

**Comment by Mythie** [comment]
Awesome, let me know how you go! I believe I've fixed up the offending code but I can't be too sure 😅

**Comment by hanprat** [comment]
@Mythie has the bug fixed?

I test with this pdf [widget_with_incomplete_appearance.pdf](https://github.com/user-attachments/files/25405067/widget_with_incomplete_appearance.pdf).

|Original|Preview in editor after uploaded|Downloaded from documenso|
|-|-|-|
|<img width="482" height="715" alt="Image" src="https://github.com/user-attachments/assets/1be66753-bb74-49f6-914f-e1fd70e3a245" />|<img width="482" height="715" alt="Image" src="https://github.com/user-attachments/assets/c5650bf9-f664-4f08-b8d2-64229aed69e5" />|<img width="482" height="715" alt="Image" src="https://github.com/user-attachments/assets/fcf1162c-b4b7-47b6-986b-1a1e883f0752" />|
|John Doe still visible|John Doe background changes|John Doe hidden/removed|

#### Edit
Hmm. I notice that [flatten-form.ts](https://github.com/documenso/documenso/blob/v2.4.0/packages/lib/server-only/pdf/flatten-form.ts) has been removed on the latest version.
