### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by fmerian** [documenso/documenso#317]
## Feature Description

As a user, I'd like to have keyboard shortcuts to perform actions quickly.

## Use Case

Suggested shortcuts:
- Add a new document
- Open `Settings`
- View all `Documents`

## Proposed Solution

- could use [this component](https://github.com/pacocoursey/cmdk)?

## Checklist

- [x] I have searched the existing feature requests to make sure this is not a duplicate.
- [x] I have provided a detailed description of the requested feature.
- [x] I have explained the use case or scenario for this feature.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by G3root** [comment]
happy to give this a try 😀

**Comment by catalinpit** [comment]
Completed in #337
