### ISSUE TITLE
Optimise notification triggers when adding new recipient

### ISSUE THREAD

**Issue by thara003** [documenso/documenso#327]
## Improvement Description

While adding a new recipient the saved notification pops up even if both the fields are empty. This doesn't feels good it might affect UX of the platform.

## Rationale

- I think we need not show the saved notification for each and every user clicks, instead we could show a single notification after the user clicks send/resend  button.
- As of now we call the API for each and every clicks, which may create a panic situation.

## Proposed Solution

- We could collect all the recipient details as a whole like a list of objects and pass it to a single API request OR temporarily make a condition where no api would be called if the email field is empty.

- Instead of highlighting the input field and row at a time we could highlight the selected input field alone.

## Additional Context

https://github.com/documenso/documenso/assets/79561774/81f41fa9-3df7-4f3b-9493-e00d2037b520

## Checklist

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by ShivaKodes** [comment]
Looks quite reasonable suggestions. Can I take this?

**Comment by Mythie** [comment]
Closing as it's no longer relevant with the move to 1.0 😄
