### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [documenso/documenso#358]
## Issue Description
The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

## Steps to Reproduce

1. Step 1: Go to footer section and see twitter old lcon

## Expected Behavior
The Twitter logo should be changed to X.

## Current Behavior
Not updated to X

## Screenshots (optional)
<img width="299" alt="Screenshot 2023-09-07 170443" src="https://github.com/documenso/documenso/assets/91591901/a8f92118-2061-45b6-9b8d-7cd332e7d49e">

## Environment

- OS: [e.g., Windows 10]
- Browser: [e.g., Chrome, Firefox]
- Version: [e.g., 2.0.1]

## Checklist

- [✅] I have searched the existing issues to make sure this is not a duplicate.
- [✅] I have provided steps to reproduce the issue.
- [✅] I have included relevant environment information.
- [✅] I have included any relevant screenshots.
- [✅] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by fmerian** [comment]
hi @lalitkumawat1m, thanks for the issue! and great suggestion indeed. 

could relate it to #281. we used the [Lucide](https://github.com/lucide-icons/lucide/) library for social icons which doesn't support brand icons ([source](https://github.com/lucide-icons/lucide/issues/1434)) anymore and thus, we should start using [simple-icons](https://github.com/simple-icons/simple-icons) instead.

**Comment by captain-Akshay** [comment]
@fmerian can i work on converting all the Lucide social icons to svg icons?

**Comment by fmerian** [comment]
> @fmerian can i work on converting all the Lucide social icons to svg icons?

thanks! sounds good to me. wdyt @Mythie?
