### ISSUE TITLE
3 or more API call for the same task to save changed name

### ISSUE THREAD

**Issue by captain-Akshay** [documenso/documenso#364]
## Issue Description
While changing the name in the settings page, I observed an unexpected behavior of the toast pop. If the user is not aware of this, the toast pop will use the same API that I called 3 or more times, which will reduce the database capabilities.
## Steps to Reproduce
1. go to setting page 
2. change your name to any other name 
3. wait for one second then press enter or save button 

## Expected Behavior
The toast pop-up should only be displayed when the name is changed.

## Current Behavior
However,if the user changed the name and waited for a second to use mouse and press save then 2 api calls will be called for no reason, if the user presses the Enter key even for a second, multiple toast pops will be displayed on the screen, each making multiple API calls. This will result in a poor user experience and will impact the database's performance.

## Screenshots
when pressed enter for 1 second:
![image](https://github.com/documenso/documenso/assets/59491379/a2031253-8364-478a-b8bd-56ac65e6aa2a)

when pressed save button (which usually take a second) and the timeout pop up were called simultaneously! 

![Screenshot from 2023-09-11 11-05-35](https://github.com/documenso/documenso/assets/59491379/2cc96ce4-e3a6-4123-8444-f73c8a91f961)

## Environment
- OS: Ubuntu
- Browser: Firefox
- Version: 116.0.2 (64-bit)

## Checklist

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by captain-Akshay** [comment]
can you assign it to me i can work on this issue.

**Comment by captain-Akshay** [comment]
would you like to assign it to me i can work on that issue

**Comment by Mythie** [comment]
Closing as this has been solved with the move to 1.0 😄
