### ISSUE TITLE
[DOC-205] Completed Documents should not be editable (for now)

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#37]
* Documents with status completed should disable the edit and add recipient button
* Adding another recipient with another signature can be added later, to reduce complexity for now

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-205](https://linear.app/documenso/issue/DOC-205/completed-documents-should-not-be-editable-for-now)</sub>

**Comment by dephraiim** [comment]
@ElTimuro I want to take this

**Comment by ElTimuro** [comment]
Let's go
