### ISSUE TITLE
"Could not send :/" email

### ISSUE THREAD

**Issue by AsimAJ33** [documenso/documenso#378]
## Issue Description

I get the above error when trying to send email.  I am using SMTP via postmark.  I've confirmed that the postmark server and credentials work as I use them for other applications also.

## Steps to Reproduce

1. Prepare a document for signing
2. Click "Send"
3. Witness "Could not send :/" error
4. Logs contain this:
```
0|documenso  | @documenso/web:dev:                  error - TypeError: Cannot read properties of undefined (reading 'from')
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/sshpk/lib/algs.js:57:13)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/sshpk/lib/key.js:6:12)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/sshpk/lib/index.js:3:11)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/http-signature/lib/utils.js:4:13)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/http-signature/lib/parser.js:5:13)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/http-signature/lib/index.js:3:14)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/request/request.js:11:21)
0|documenso  | @documenso/web:dev:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
0|documenso  | @documenso/web:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
0|documenso  | @documenso/web:dev:     at Module.load (node:internal/modules/cjs/loader:1119:32)
0|documenso  | @documenso/web:dev:     at Module._load (node:internal/modules/cjs/loader:960:12)
0|documenso  | @documenso/web:dev:     at Module.require (node:internal/modules/cjs/loader:1143:19)
0|documenso  | @documenso/web:dev:     at require (node:internal/modules/cjs/helpers:121:18)
0|documenso  | @documenso/web:dev:     at Object.<anonymous> (/opt/documenso/node_modules/request/index.js:143:19)
``` 

## Expected Behavior

Success message and email to be sent.

## Current Behavior

Error message and email not being sent.

## Environment

- OS: Debian 11
- Browser: Chrome
- Node: 18.17.1
- NPM: 9.6.7

## Checklist

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by AsimAJ33** [comment]
I've double checked my `.env` file to make sure I've not made any syntax errors in the SMTP config and I can confirm that I've not.

![Screenshot from 2023-09-15 23-11-30](https://github.com/documenso/documenso/assets/17923501/ab60472d-415f-4833-9894-100b44c1e422)

**Comment by shanu55444** [comment]
Hey @AsimAJ33, can you add these values into `.env.local` instead of `.env` file and try again?

I see that .env is getting ignored by docker.

Just for reference, you have both `SMTP_MAIL_USER` and `SMTP_MAIL_PASSWORD` as the same value from Postmark , right ?

**Comment by AsimAJ33** [comment]
I should have specified that I'm not using docker. Should I still use
.env.local? Other parameters from .env are being read correctly i.e the
home URL etc so the .env file must be getting used right?

Yes I have both those parameters as the same for postmark.

**Comment by Pablohn26** [comment]
I hit the same error and my problem was the SMTP variables. 

If you are not using docker maybe you are not providing the variables to the platform and that is causing the error. Try to deploy it with docker using the variables that you are using and check if they are working or not. 

To check if you `.env` file is working or not, just change some variable to break the configuration and check if you hit an error. If changing the variables to wrong values does not affect to your deployment, you are not using those variables.

**Comment by dephraiim** [comment]
@AsimAJ33 Have you been able to fix it? Any progress on this?

**Comment by AsimAJ33** [comment]
Not been able to fix it yet still getting the same error

**Comment by redfoxasim** [comment]
> I hit the same error and my problem was the SMTP variables.
> 
> If you are not using docker maybe you are not providing the variables to the platform and that is causing the error. Try to deploy it with docker using the variables that you are using and check if they are working or not.
> 
> To check if you `.env` file is working or not, just change some variable to break the configuration and check if you hit an error. If changing the variables to wrong values does not affect to your deployment, you are not using those variables.

My `.env` file is definetely being read because I made other changes that I can see are being read in the log.  e.g. I changed the subscription from false to true and can see that reflected in the log.  I've checked and double checked my SMTP parameters and they're the same as my previous screenshot and they're 100% correct so I'm unsure what the issue is.

I feel I might need to abandon documenso for a while sadly, I need to send documents out ☹️

**Comment by Mythie** [comment]
Hey there, with the improvements to Documenso coming from the `feat/refresh` branch leading to the launch of 1.0 I'd like to invite you to try again.

We've made a number of changes and improvements that should hopefully help make Documenso work for you 🤗

**Comment by compgeniuses** [comment]
i seem to also be getting the same error with documenso in regards to sending emails on registrations, seems there is an issue with smtp settings.

We are building a nethserver  module for documenso
