### ISSUE TITLE
Use bun instead of npm 

### ISSUE THREAD

**Issue by swastik959** [documenso/documenso#382]
## Improvement Description

we can use bun instead of npm package as it is faster then npm
## Rationale
we can use bun instead of npm package as it is faster then npm

## Checklist

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [ ] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mythie** [comment]
Hey there, while it sounds fun I'm not looking to fragment the tools needed to build and run Documenso at the current moment.

We will be watching Bun to see how it evolves and how much marketshare it gains, if we believe that switching will net a decent gain while not alienating self-hosters we will move to it at that point 😄
