### ISSUE TITLE
Vercel + Supabase guide

### ISSUE THREAD

**Issue by BleedingDev** [documenso/documenso#389]
I think it would be awesome to have a guide for deployment without Docker. For the documentation I see no problem with this setup.
## Rationale
Simple and easy process.

## Proposed Solution
Improve Readme.md with instructions.

## Checklist

- [ ] I have searched the existing issues and improvement suggestions to avoid duplication.
- [ ] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mythie** [comment]
G'day, we've added one as a blog post as part of #386 it's still pending deployment to https://documenso.com but you can read it at https://dev.to/documenso/deploying-documenso-with-vercel-supabase-and-resend-foi
