### ISSUE TITLE
[DOC-206] When adding more than 1 Signer and the Document is sent while some Recipient email fiels stay empty, the document status be stuck in "waiting for others"

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#39]
<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-206](https://linear.app/documenso/issue/DOC-206/when-adding-more-than-1-signer-and-the-document-is-sent-while-some)</sub>

**Comment by SauravL3010** [comment]
I am working in this, will have a PR up in some time :)

**Comment by ElTimuro** [comment]
fixed by rewrite
