### ISSUE TITLE
Spanish translation (multi language)

### ISSUE THREAD

**Issue by Pablohn26** [documenso/documenso#392]
## Feature Description

I would like to translate documenso to Spanish. It adds a high value allowing non English speakers to sign documents.  

## Use Case

A Spanish person wants to follow the hole signing process but all the text is in English.  

## Proposed Solution

Since you are rewritting the whole app, I suppose you will provide multilanguage. So please let me know when you support multilanguage and I will provide Spanish translation of the app. 

## Alternatives (optional)

As you wish 

## Additional Context

The app is still in beta and it is only in English, so non English users could not use it. 

## Checklist

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by aneudy91** [comment]
@Pablohn26 I am willing to collaborate on this Issue.

**Comment by dguyen** [comment]
Thanks for bringing this up, this isn't something that we can get into 1.0 due to time constraints but it may be something we will consider adding to the roadmap in the future.

**Comment by Pablohn26** [comment]
@dguyen could you add `on-hold` tag to skip auto closing this issue?

**Comment by Mythie** [comment]
Was on my todo list 😄 Sorry Pablo!

**Comment by dguyen** [comment]
Spanish has been added to the application, further improvements to the translations are welcome!
