### ISSUE TITLE
[DOC-207] Testing in Safari, iOS, MacOS

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#40]
* So far, there has been little testing on iOS
* Using test.documenso.com the web app should be tested on those systems
* Found Bugs should be created as Issues (https://github.com/documenso/documenso/issues) or discussed here

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-207](https://linear.app/documenso/issue/DOC-207/testing-in-safari-ios-macos)</sub>

**Comment by singhbhaskar** [comment]
Hey @ElTimuro ,
I have test the following scenario from MacOS Safari with version `Version 15.6.1 (17613.3.9.1.16)`
Scenario:
* Create a new user
* Upload a document
* Add a Signer
* Send the request to sign
* Sign the document
* Download the document after signing.
I didn't see any issues.

**Comment by ElTimuro** [comment]
@singhbhaskar that's really awesome, thanks for checking 🫡

![image](https://github.com/documenso/documenso/assets/1309312/b7eb26ff-a929-4ea2-aaa1-453ea05f2b60)

**Comment by fmerian** [comment]
for the record, some data:

## browsers
- Chrome: 54%
- Safari: 34%
- Firefox: 5%
- Edge: 4%

## OS
- iOS: 33%
- Mac: 30%
- Windows: 18%
- Android: 15%
- Linux: 3%

## Size
- Desktop: 51%
- Mobile: 48%
- Tablet: 1%

**Comment by ElTimuro** [comment]
closing since doen
