### ISSUE TITLE
[Staging] Google Auth not working

### ISSUE THREAD

**Issue by arpadgabor** [documenso/documenso#431]
First? Sorry.

Anyways, seems like OAuth is not working with Google, no clue why. Tested with different browser profiles on Firefox and Chrome.

https://github.com/documenso/documenso/assets/9270494/c35f8372-9cff-4434-8638-47a62cd31af0

**Comment by premiare** [comment]
+1 same issue here.
Windows 11, Brave Browser.

**Comment by Mythie** [comment]
Hey ya'll added the Google environment variables that were missing and it should be working now 😄 

Cheers!
