### ISSUE TITLE
[Staging] Signee doc version doesn't have sticky signing area

### ISSUE THREAD

**Issue by premiare** [documenso/documenso#432]
Couldn't think of a better title, apologies.

In the document page, the 'Add Signers' area which I'll call "signing box" is sticky and follows along the PDF if the PDF is long.
In this example, it's 13 pages.
![image](https://github.com/documenso/documenso/assets/64188227/d7f2ee7e-6842-443e-b8e0-f317bfc0a2fe)

In the signee signing box (`stg-app.documenso.com/sign/{SLUG}`) the signing box isn't sticky
![image](https://github.com/documenso/documenso/assets/64188227/3f071835-3e4b-421c-9d1e-ccb216755776)

**Comment by Dun-sin** [comment]
can i work on this?
