### ISSUE TITLE
Changes in signature 

### ISSUE THREAD

**Issue by giiiiid** [documenso/documenso#433]
Changes are made to the signature if the user is using a phone and while scrolling, their finger might touch the signature and changes will be made to the signature. A save and change button will help to save and change a signature respectively.

**Comment by Mythie** [comment]
Hey there, this was an active design decision on our end. We want signature fields to be able to be used instantly and only display a popup for certain cases.

We may revise our position on this as we collect more usage data in the future 😄

**Comment by giiiiid** [comment]
Okay Mythie
