### ISSUE TITLE
Not Receiving Docs sent to Mail in staging

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [documenso/documenso#436]
As the title implies, I'm not getting any mail in my inbox or spam even though the success toast was triggered.
Am I doing something wrong??
![Screenshot (62)](https://github.com/documenso/documenso/assets/31078314/6b17a8fd-64ab-4909-a450-4bd7c65314ad)

**Comment by Mythie** [comment]
Hey there, as far as I can tell according to our email provider you should have received the emails. If you want to message me on Discord I can provide more information privately 😄

**Comment by PeterKwesiAnsah** [comment]
yeah sure i can do that @Mythie
