### ISSUE TITLE
Missing Empty Recipients List Message in Staging

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [documenso/documenso#437]
So the Recipients List is missing an empty message when a particular recipient can't be found.

This opens up a feature allowing the user to add a recipient if it can't be found in the list.
I think for version 1.0 We can show the empty message.
Let me know what you think.

![Screenshot (63)](https://github.com/documenso/documenso/assets/31078314/4c3066bc-b603-47e8-af54-7f7a283af7d3)

**Comment by Mythie** [comment]
Empty message is ideal, although I do agree we might want to support on the fly creation in the future 😄

**Comment by PeterKwesiAnsah** [comment]
Coolio. Can I take a swing on this ?? It's a good first time issue
