### ISSUE TITLE
[Bug] - Action Buttons Gets Hidden

### ISSUE THREAD

**Issue by adithyaakrishna** [documenso/documenso#441]
**Description:**

On the **AddSigners** page, if I add N number of signers, and scroll down, the action buttons for `Go back` and `Continue` gets hidden 😶 

Added a video below for reference :)

[NoActionButtons.webm](https://github.com/documenso/documenso/assets/23498248/74757634-e139-49d0-9876-441e80f004b9)

Also, the area seems to be not properly sticky which was mentioned [here](https://github.com/documenso/documenso/issues/432#issuecomment-1735274536)  as well

**Comment by mittalsam98** [comment]
I would like to work upon this

**Comment by catalinpit** [comment]
Thanks for reporting this @adithyaakrishna!

@mittalsam98 it seems the author picked the issue already.

**Comment by dguyen** [comment]
![image](https://github.com/documenso/documenso/assets/20962767/97cbb147-ca9b-4b88-afc4-9ec79d9d8c93)

Just noting I can't seem to see the videos you've been posting, could be just me though

**Comment by catalinpit** [comment]
> ![image](https://user-images.githubusercontent.com/20962767/272762359-0b3cd805-0576-4b82-bc0f-2fbf647c969d.png)
> 
> Just noting I can't seem to see the videos you've been posting, could be just me though

I can see the video myself. 😃
