### ISSUE TITLE
[BUG]: Signers component form validations are messed up when more than 2 signers are added

### ISSUE THREAD

**Issue by hashkazi00** [documenso/documenso#443]
![Screenshot 2023-09-27 at 7 19 51 PM](https://github.com/documenso/documenso/assets/37013706/7ed55301-7b6a-467e-8c1a-42318c78e784)

![Screenshot 2023-09-27 at 7 23 21 PM](https://github.com/documenso/documenso/assets/37013706/dddfce38-be6c-4334-b801-9c6d5ca6b7df)

https://github.com/documenso/documenso/assets/37013706/5c99e652-3c28-4f2d-bb0b-7f3934f2bc20

Steps to repro:
1. In the first field add email and name correctly
2. Then add 2 or more signers and keep them empty
3. Click Continue

**Comment by Mythie** [comment]
That one was painful, thanks for reporting! 🫡
