### ISSUE TITLE
[BUG] The count of completed documents is coming wrong

### ISSUE THREAD

**Issue by hashkazi00** [documenso/documenso#444]
Steps to Reproduce:
1. Completed document count is getting multiplied by 2 * actual number of completed docs and thus is appearing wrong

![Screenshot 2023-09-27 at 7 32 50 PM](https://github.com/documenso/documenso/assets/37013706/141aae54-3bd6-4d14-a71c-3f8ffcd0e8d3)
![Screenshot 2023-09-27 at 7 35 08 PM](https://github.com/documenso/documenso/assets/37013706/c63079a3-fdd6-4447-8e81-df8d4659a999)

**Comment by dephraiim** [comment]
I've been able to reproduce it locally

**Comment by dguyen** [comment]
@hashkazi00 are you both the recipient and signer in this scenario?

In that case, theoretically you are both the signer and recipient, which means you have 2 completed documents 

@Mythie explained the reason before, but I don't remember

I assume the count calculation can be updated if someone wants to take this

**Comment by hashkazi00** [comment]
Anyways, yes that's the case.

**Comment by Abhinav-Developer-23** [comment]
Is this resolved? I am still getting incorrect count.


https://github.com/documenso/documenso/assets/145282438/f52c245d-9778-4bfd-9008-8d12599bca60

**Comment by Mythie** [comment]
In the completed tab you're getting a double count for where you're a recipient and the owner, this is "technically correct" but obviously looks wrong.

We can improve this but we also want to ensure we aren't doing too much in the database since that'll slow down what is at the end of the day a vanity stat.
