### ISSUE TITLE
[Bug] Name and email does not get updated 

### ISSUE THREAD

**Issue by hashkazi00** [documenso/documenso#445]
Steps to Repro:
1. Add a document
2. Only Add the signers emails and hit continue
3. Go back to the Add signers page and add the name and hit continue
4. go back to add signers page
5. Voila! Name doesn't get updated or saved

https://github.com/documenso/documenso/assets/37013706/9cbb5196-f441-4f28-9eb7-62ff39334e06

Note: I found out that sam happens with the e-mail field

**Comment by adityadeshlahre** [comment]
This is valid [Bug]. i have also reproduced and faced locally !
