### ISSUE TITLE
[BUG/UX] PDF Name gets truncated even while ample of space available on screen

### ISSUE THREAD

**Issue by hashkazi00** [documenso/documenso#447]
The full name of the PDF was Postgres is an open source database engine, which got truncated on edit document page

<img width="960" alt="Screenshot 2023-09-27 at 8 23 11 PM" src="https://github.com/documenso/documenso/assets/37013706/d4316089-b5b0-4e7e-9169-3a944d12847b">

**Comment by Mythie** [comment]
Hey there, this one isn't a bug but was a decision we made during the design phase. That said we've recalibrated and decided to allow for longer titles even if they will look a little more awkward.

Thanks for bringing us back to this.
