### ISSUE TITLE
[DOC-350] [DOC-351] Free Singleplayer Mode

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#456]
* Quickly signing a single, once-in-a-while document alone can be a pain
* Creating an account to sign once is tedious and potentially expensive
* Documenso Singleplayer is a login-less single-user signing experience that lets users quickly sign a document for free
* Without even creating an account
* Signing documents can be downloaded immediately or saved in a free complimentary Documenso free plan account
* The Documenso Free Plan will feature 5 signatures per month

\*\*### Singleplayer will launch in the first half of October, shortly after the release of 1.0, \*\*[**ON PRODUCT HUNT!**](https://www.producthunt.com/products/documenso) That's right, we are going back to Product Hunt to kick of this new phase of Documenso and you are invited to join us once again :)

Read More: [https://documen.so/sp](https://documen.so/sp)

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-350](https://linear.app/documenso/issue/DOC-350/[doc-351]-free-singleplayer-mode)</sub>

**Comment by adityadeshlahre** [comment]
I would like take this and work on it. @ElTimuro can you please assign me ! :smile:

**Comment by adityadeshlahre** [comment]
I would like take this and work on it. @ElTimuro can you please assign me ! :smile:
