### ISSUE TITLE
[Bug] - Signing Card Has Sharp Corners

### ISSUE THREAD

**Issue by adithyaakrishna** [documenso/documenso#461]
**Description:**

The corner of the 3D sign box seems to have a sharp corner having background. Please refer the screenshots and video below for more reference :)

**Video:**

[SharpCorner.webm](https://github.com/documenso/documenso/assets/23498248/7e744a07-e50e-4b3d-a434-af4dfb2f6990)

**Screenshot:**

<img width="893" alt="Screenshot 2023-09-29 at 1 54 08 AM" src="https://github.com/documenso/documenso/assets/23498248/d46868f0-6cfb-446c-b3ed-e5fa1830090c">

**Comment by Mythie** [comment]
Thanks for reporting and fixing :green_heart:

/tip 25
