### ISSUE TITLE
Secure Password Parameters

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#464]
**Currently**:
- Passwords can be easily guessed or brute-forced.
- Takes a minimum password length of 8 characters.

**Desired State**
- Must include at least:
	- One uppercase letter.
	- One lowercase letter.
	- One digit.
- Restriction against using easily guessable passwords (e.g., "password123", "12345678")
- Passwords should not be based on the user's personal information (e.g., name, email).
- Errors and alerts for password change if it detects weak or commonly used passwords.

![Password Strength](https://imgs.xkcd.com/comics/password_strength_2x.png)

**Comment by Dun-sin** [comment]
A library for this would be good? Or manual way is what should be done?

**Comment by catalinpit** [comment]
Hey @Dun-sin, sorry for the late reply! It seems @adithyaakrishna started working on this shortly after @dephraiim created the issue.

Sorry about that! We recently made some improvements to the [contribution guide](https://github.com/documenso/documenso/blob/feat/refresh/CONTRIBUTING.md#taking-issues), and it'll take some time until everyone familiarizes themselves with it.

**Comment by babblebey** [comment]
This issue has been addressed #568
