### ISSUE TITLE
[BUG] [SAFARI] The document viewer has pdf overflow issue

### ISSUE THREAD

**Issue by hashkazi00** [documenso/documenso#465]
<img width="1036" alt="Screenshot 2023-09-29 at 4 49 49 PM" src="https://github.com/documenso/documenso/assets/37013706/799ba3d5-9149-491e-a26a-9b2f36266c58">
<img width="150" alt="Screenshot 2023-09-29 at 4 51 27 PM" src="https://github.com/documenso/documenso/assets/37013706/2d37f3cf-cafb-4fff-8e4a-2630ecc0b145">
<img width="210" alt="Screenshot 2023-09-29 at 4 51 18 PM" src="https://github.com/documenso/documenso/assets/37013706/57602af0-0781-4caa-93b7-e47e6b996081">

**Comment by hashkazi00** [comment]
Workaround for this:
adding the 'will-change-transform' class should fix the issue, tested locally, will try to raise a PR @Mythie 


Refer: https://gist.github.com/domske/b66047671c780a238b51c51ffde8d3a0

**Comment by dguyen** [comment]
That's strange, I can't seem to replicate this

![image](https://github.com/documenso/documenso/assets/20962767/c16daf37-243e-46ad-b209-cbb5c028aefb)

Can anyone else replicate this on safari?

**Comment by hashkazi00** [comment]
Ah, I can still see it, 

It's visible on Safari MacOS, Safari iOS and Brave iOS browsers.
