### ISSUE TITLE
[DOC-213] Signers need a email notificatin on Document Completion with the signed document

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#47]
* This already works for the sender

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-213](https://linear.app/documenso/issue/DOC-213/signers-need-a-email-notificatin-on-document-completion-with-the)</sub>

**Comment by dephraiim** [comment]
@ElTimuro I would like to take this

**Comment by ElTimuro** [comment]
Testing
