### ISSUE TITLE
Delete a draft document

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#472]
**Current Behavior:** 
- While the UI allows to delete draft documents, the underlying functionality is missing.

**Desired Feature:** 
- Enable users to delete documents that have not been sent, opened, or signed from the Actions on the documents table

**Comment by arjunbharti** [comment]
hey, i would like to pick this up!

**Comment by dguyen** [comment]
Hey @arjunbharti, thanks for your interest in contributing!

Sorry but it appears that another contributor has already started working on this particular issue.

We plan to create clear guidelines for contributing in the near future which will hopefully provide clarity on how issues and PRs are assigned to ensure everyone has a fair chance at contributing.
