### ISSUE TITLE
 Resending Emails to Recipients

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#473]
# Document signing "Resend" feature

This feature should allow document owners to send reminders to one or more document recipients. It should be a modal popup that looks like this:

<img width="679" alt="Screenshot 2023-10-02 at 15 43 59" src="https://github.com/documenso/documenso/assets/20962767/4ec1fa22-0b6c-4c29-8dc5-7afbbe916431">

The user should be able to only send a reminder to the recipients who didn't sign the document. The recipients that signed the document could have a green tick instead of the checkbox, or they could be hidden altogether.

The current "Resend" button can be found on the /documents page.

<img width="1464" alt="Screenshot 2023-10-02 at 15 45 36" src="https://github.com/documenso/documenso/assets/20962767/caa0aa79-e324-46f2-8830-a4f3edec4531">

Feel free to ask any questions.

**Comment by mittalsam98** [comment]
Hey @dephraiim  I would like to pick this up, pls assign this to me

**Comment by dguyen** [comment]
Hey @mittalsam98, thanks for your interest in contributing!

Sorry but it appears that another contributor has already started working on this particular issue.

We plan to create clear guidelines for contributing in the near future which will hopefully provide clarity on how issues and PRs are assigned to ensure everyone has a fair chance at contributing.

**Comment by mittalsam98** [comment]
Got it but actually when I asked its unassigned

**Comment by dguyen** [comment]
Sorry about that, we plan to likely have first come first serve in the future for public issues once we create some guidelines

**Comment by dephraiim** [comment]
Closing this as this has been added in #496
