### ISSUE TITLE
"Undo Button" while Drawing Signature 

### ISSUE THREAD

**Issue by Rahilkzi** [documenso/documenso#479]
### Problem:
Currently, the Documenso signature feature lacks an undo button, which can be problematic for users. while Drawing Signature, mistakes can happen, and users need a way to rectify them without going through the hassle of starting over.

### Reasoning:
1. **Error Correction:** Users often make small mistakes or want to make adjustments while drawing a signature. An "undo" button would allow users to easily correct errors without the need to erase or restart the entire signature.

2. **User-Friendly Experience:** This button would allow users to step back and correct any errors they may have made during the signature creation. It would greatly enhance the user experience and reduce frustration.

**Comment by 18feb06** [comment]
Sounds interesting

**Comment by 18feb06** [comment]
Working on it

**Comment by hashkazi00** [comment]
Good problem definition! Keep it up
