### ISSUE TITLE
Signature Pad Color on Darkmode

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#483]
The signature pad color on darkmode is different from the dark mode colors available on the app in general.

![CleanShot 2023-10-02 at 00 46 06@2x](https://github.com/documenso/documenso/assets/55143799/6fc76f62-3989-4ea3-95dc-9a68adf6ca2d)

**Comment by adithyaakrishna** [comment]
Fancy, taking this up :)

@dephraiim could you pls let me know if it needs to be in the grey color? 👀

**Comment by catalinpit** [comment]
Hey @adithyaakrishna, thanks for showing interest! It seems that someone started working on the issue already. Sorry about that!

We're working on improving the process of assigning issues though. 🙏
