### ISSUE TITLE
[bug] Email Requesting Signature shows "Completed Document" in Preview Text

### ISSUE THREAD

**Issue by daallgeier** [documenso/documenso#499]
When receiving an email from documenso with a new document asking to sign the Preview Text (next or under the email subject in an inbox) shows the Preview as "Completed Document" while it should be "Signature Requested" or something similar.

How to reproduce?
1. Send signature request to gmail
2. Be in Inbox 
3. Look for "completed document" next to the subject 

![image](https://github.com/documenso/documenso/assets/9637909/0358cf92-7a27-461a-956a-736e7ff2dc75)

Other suggestions for a good Preview Text
- Signature Requested by {sender.name} on {document.name}
- Signature Requested on {document.name}
- Please sign {document.name}
- Please sign {document.name} by {sender.name} by {date.due}

**Comment by catalinpit** [comment]
Thanks for reporting this, @daallgeier!

**Comment by dguyen** [comment]
Thanks for finding this 😄 

/tip 25
