### ISSUE TITLE
[DOC-217] Show Completed Date for Documents

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#50]
- The document entity in the database should have a completedDate field
- The field is null per default
- When the status is set to completed, the field is filled with the current date
- The completion date is shown in the recipients view and documents view

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-217](https://linear.app/documenso/issue/DOC-217/show-completed-date-for-documents)</sub>

**Comment by dephraiim** [comment]
@ElTimuro I would like to take this.
