### ISSUE TITLE
[Feature] Allow for direct signing when creating a new document

### ISSUE THREAD

**Issue by daallgeier** [documenso/documenso#501]
As a document creator and signature requestor: 
Instead of having to send a document to one's own inbox it would be great if I can sign my document directly when creating the signature placements so when I complete the document creation my signature is already on the document. 

This would skip over me needing to receive the email and then sign and on one person signature docs would only email the completed document. 

For multi-person documents it would also show them the already signed portion and allow for faster completion.

For multi-signature documents where some people sign on multiple pages (say a thank you for your offer request letter above an offer), I'd like to sign the letter directly but only sign the document after everyone else signed.   vgl. Pandadocs.

**Comment by catalinpit** [comment]
Hey @daallgeier, thanks for the suggestion. That sounds like a useful improvement!

**Comment by 18feb06** [comment]
I would like to work on this improvement ! 😊

**Comment by catalinpit** [comment]
@18feb06 please go ahead!

**Comment by 18feb06** [comment]
Sure

**Comment by 18feb06** [comment]
@catalinpit  Kindly review the PR, and give feedback. Thanks
