### ISSUE TITLE
Inconsistent Recipient signing behavior

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [documenso/documenso#503]
1. **Unexpected Behavior**: When a Document Recipient signs using the Signature button it automatically adds the signature to the signature pad in the 'Sign Document Form'.  But when you remove that same signature using the signature button,  the signature in the 'Sign Document form' does not get removed 
![Screenshot (70)](https://github.com/documenso/documenso/assets/31078314/4c30ccda-16b1-4386-8818-debf4b675299)

1. **Expected Behavior**: The Signature in the 'Sign Document'  should be removed accordingly.

2. **Unexpected Behavior**: When a Document Recipient signs using the Signature button and the page is refreshed, the signature button gets prefilled but the other signature pad doesn't.
![Screenshot (71)](https://github.com/documenso/documenso/assets/31078314/947c0be7-4e77-49c1-a789-5987463a1a41)

2. **Expected Behavior**: The other signature pad should also get prefilled accordingly.

I have a question. Currently, adding a signature using the signature button adds the signature to the other signature pad, why don't the other signature pad do the same to the signature button?

Let me know what you guys think. Just Thinking out loud

**Comment by 18feb06** [comment]
@PeterKwesiAnsah  You can update signature and name by following method
file:///home/tameem/Videos/Screencasts/Screencast%20from%2010-03-2023%2004:50:30%20PM.webm

**Comment by pansah321** [comment]
@18feb06 seems the video is archived.

**Comment by PeterKwesiAnsah** [comment]
@18feb06 The Video is Archived.

**Comment by 18feb06** [comment]
@PeterKwesiAnsah   Sorry for archived video, now you can watch it by clicking on [Watch Methode](https://youtu.be/4p8eRjUahqs) link

**Comment by PeterKwesiAnsah** [comment]
@18feb06 I have seen your video but I don't see how it relates with the behaviours above
Have you tried to reproduce it ??
