### ISSUE TITLE
[Bug] - Non Responsiveness of Add your signature modal 

### ISSUE THREAD

**Issue by adithyaakrishna** [documenso/documenso#507]
**Description:**

The _**Add your signature modal**_ at https://documenso.com/ on Mobile view is not centered and has the close icon very close to the search bar which may cause users to click on other buttons by mistake.

Please refer the screenshot below

![IMG_9070](https://github.com/documenso/documenso/assets/23498248/dea0ee7a-0f58-4970-98f5-c469e495b78a)

The expected outcome would be to center the modal on mobile views and give sufficient margins around it

**Comment by mittalsam98** [comment]
Hey, pls assign this to me. I would love to work on this

**Comment by adithyaakrishna** [comment]
@mittalsam98 Sure! Please feel free to take this up and send a PR towards it :)

**Comment by adityadeshlahre** [comment]
hey @adithyaakrishna and @mittalsam98 
since i worked on this PR #516 
it looks like this issue is device specific because there is already a perfect margin exist ! 
may be i am wrong :smile: 

**Screenshot**
![margined2023-10-04_12-24](https://github.com/documenso/documenso/assets/132184385/95b477d3-afcf-4fb4-bce5-757766216bf7)

ThankYou !

**Comment by dguyen** [comment]
Hey @adithyaakrishna, just wanted to check

> has the close icon very close to the search bar which may cause users to click on other buttons by mistake.

Which search bar are you referring to? The mobile browser search bar?

**Comment by adithyaakrishna** [comment]
@dguyen I guess it was a brave browser issue, I'm not facing this anymore. I would love to know what you think about the modal with respect to mobile viewpoints. Proly make it centered? If so, we can change the issue description to it

**Comment by dguyen** [comment]
@adithyaakrishna after some internal discussion, the team believes that the best way forward is to have the dialog default to full screen on mobile.

Proposed changes:
- Keep the current ability to position the dialog
- Make dialogs by default full screen on mobile (when dialog prop position is not set)
- Move the X slightly further from the corner of the screen

What do you think?
