### ISSUE TITLE
[improvement] Signing up using existing email does not show correct message

### ISSUE THREAD

**Issue by AbhinavAwesome** [documenso/documenso#511]
[Description]
If a person uses documenso occasionally, they may not remember that they already have account.if they try to sign up again using same email id, correct error message is not shown.They may think that it is a problem with the system. We should have a message like "user already exists".
![Screenshot from 2023-10-03 21-02-09](https://github.com/documenso/documenso/assets/145282438/6b27a96e-792c-4ff7-889f-6ee446930e6a)

**Comment by catalinpit** [comment]
Hey @mittalsam98, thanks for your interest! It seems that someone else opened a PR already.

We're in the process of improving the contributing process, which just got an update - [#taking-issues](https://github.com/documenso/documenso/blob/feat/refresh/CONTRIBUTING.md#taking-issues), but it'll take a bit until everyone familiarizes themselves with the new process.

**Comment by AbhinavAwesome** [comment]
Thank you so much

**Comment by AbhinavAwesome** [comment]
I have completed algora onboarding
