### ISSUE TITLE
Able to login using Forgot password

### ISSUE THREAD

**Issue by mittalsam98** [documenso/documenso#512]
Description:

When I clicked on `Forgot your password?` and entered my email address, a password reset email arrived in my inbox. Ideally, it should have shown an "Email not found" error. However, I was able to set a new password and then login to the app without any issue.

Not sure whether it is the intended behaviour or a bug

Would you like to work on this?
Yes

**Comment by 18feb06** [comment]
@mittalsam98 can you please elaborate this??

**Comment by mittalsam98** [comment]
@18feb06 I already mentioned the steps.
I was not registered but still able to login via that step I mentioned above

**Comment by dguyen** [comment]
@mittalsam98 just to get some clarification, are you saying that when you:

1. Click 'Forgot your password'
2. Enter an email for an account that does not exist
3. A password reset email is sent to you
4. You set a password and log in 

I don't think you would receive an email if you are requesting a password reset for an account that does not exist. Could you please try again with an email you are confident does not exist in the database?

> Ideally, it should have shown an "Email not found" error. 

Not necessarily, we intentionally display the following message to the user regardless if the account exists or not.

> A password reset email has been sent, if you have an account you should see it in your inbox shortly.

**Comment by catalinpit** [comment]
I couldn't reproduce the issue.

**Comment by mittalsam98** [comment]
Now I am not getting the email, but I created one account like this only

**Comment by mittalsam98** [comment]
Oh got the issue, how I am able to login, these are retro steps

1. Open this Signup Modal and just enter the `Name` and `Email ID` and click on `Claim the ..`. without any subscription purchase
![image](https://github.com/documenso/documenso/assets/42431274/3bfbc4bd-7897-405b-b3bd-55f7ea462f07)

2. Now go to Login and follow the above mentioned steps


I think we are storing the email of click of Claim button click

**Comment by dguyen** [comment]
Oh okay so when you go through the early adopter sequence it'll create an account and will provide you a password at the end of it when you checkout.

Currently this won't work on staging since it's not setup there, but your account will still be created.

This is currently a non-issue, but there can definitely be improvements to the flow.

**Comment by mittalsam98** [comment]
Yeah ideally IMO user account should be created only when every steps has been completed successfully

**Comment by dguyen** [comment]
Created a separate issue specifically for this #532

/tip 25
