### ISSUE TITLE
Cannot run npx prisma migrate deploy

### ISSUE THREAD

**Issue by e7172** [documenso/documenso#515]
Hi, im trying to deploy Documenso but i need some help. 

Im following this [tutorial](https://dev.to/documenso/deploying-documenso-with-vercel-supabase-and-resend-foi)

**And when i get to:**
`npx prisma migrate deploy`

**It says:**
```Environment variables loaded from .env
Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-us-east-1.pooler.supabase.com:6543"
Error: P1017: Server has closed the connection.
```

First I checked that the connection to the database was correct, which is fine, then I looked at the logs and found no errors. 
I guess it's a schema error, but I can't figure out how to solve it and move on. 

_Any help is appreciate_

**Comment by dephraiim** [comment]
@e7172  Can you try `npx prisma db push`?

**Comment by e7172** [comment]
Same problem!

```
Environment variables loaded from .env
Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "aws-0-us-east-1.pooler.supabase.com:6543"

Error: P1017: Server has closed the connection.
```

**Comment by e7172** [comment]
Solved, it was a problem with default port in Supabase connection string which is 6543, instead db is in port 5432.
Thank you all,

**Comment by e7172** [comment]
Closing

**Comment by e7172** [comment]
Solved, it was a problem with default port in Supabase connection string which is 6543, instead db is in port 5432.
Thank you all,
