### ISSUE TITLE
Correcting Gitpod Configuration: Updating gitpod.yml for Proper Port Exposure and Initialization Commands

### ISSUE THREAD

**Issue by anjy7** [documenso/documenso#518]
Gitpod isn't configured properly, we need to configure the gitpod.yml file to expose the right ports and run the necessary commands to start the dev env.

![image](https://github.com/documenso/documenso/assets/92802904/86f01517-0ec3-486f-bef3-fd22cfe59d8d)

**Comment by anjy7** [comment]
I'm working on this and will raise a PR soon..

**Comment by catalinpit** [comment]
Thanks @anjy7. Looking forward to the PR.

**Comment by anjy7** [comment]
Hey @anikdhabal, I understand that you might be new to this community, but I would appreciate it if you went through the contributing guidelines before making a PR - reason being :
 1. It would avoid redundant work
 2. It wouldn't waste anyone's time
Apart from this, I went through your PR; it looks like there's some error in the DB connection. I have been trying to fix the same issue for a while now; otherwise, I would have raised the PR myself before. I hope you understand. Keeping that aside, I would be glad to work with you to solve that error :) .

**Comment by anikdhabal** [comment]
> Hey @anikdhabal, I understand that you might be new to this community, but I would appreciate it if you go through the contributing guidelines before making a PR - reason being :
> 
> 1. It would avoid redundant work
> 2. It wouldn't waste anyone's time
> 
> Apart from this, I went through your PR; it looks like there's some error in the DB connection. I have been trying to fix the same issue for a while now; otherwise, I would have raised the PR myself before. I hope you understand. Keeping that aside, I would be glad to work with you to solve that error :) .

I updated it. Now it's working without any error :).
