### ISSUE TITLE
[Bug] - Signature State Should Persist Unless Cleared or Refreshed

### ISSUE THREAD

**Issue by adithyaakrishna** [documenso/documenso#520]
**Description:**

Currently, if we add our email at https://documenso.com and our signature in the box, the state does not persist upon opening the _**Add your signature**_ modal. The ideal case is to clear it upon refresh or when the user clicks the **clear signature** button

Please refer to the video below for more reference :)

[screen-capture.webm](https://github.com/documenso/documenso/assets/23498248/1a23da4e-e0d2-4539-8333-ecdc34b2d001)

**Comment by zahid47** [comment]
I'd like to attempt this!

**Comment by catalinpit** [comment]
Hey @adithyaakrishna, thanks for reporting this!

@zahid47 please go ahead. Thanks!
