### ISSUE TITLE
[DOC-361] Use dotenv for Prisma package scripts

### ISSUE THREAD

**Issue by catalinpit** [documenso/documenso#523]
The app should use the "dotenv" package to load the environment variables.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-361](https://linear.app/documenso/issue/DOC-361/use-dotenv-for-package-scripts)</sub>

**Comment by adityadeshlahre** [comment]
i would like to work on this improvement ! :smile:

**Comment by anjy7** [comment]
Hey @adityadeshlahre , I ran into this issue and had made the changes while working on the gitpod setup. To save your time - install dotenv package and add "require('dotenv').config();" to helper.ts and schema.prisma under packages/prisma

**Comment by adityadeshlahre** [comment]
Thank You @anjy7 sure will consider your changes : )

**Comment by adityadeshlahre** [comment]
**UPDATE**
![image](https://github.com/documenso/documenso/assets/132184385/e9053da1-44f3-49a0-b880-52ac62c69e8d)

i m able to load the .env from root level using package.json ! :smile: 
but **`npm run prisma:migrate-dev -w @documenso/prisma`** is giving error 

I am trying to figure it out !
Thank You
