### ISSUE TITLE
[bug] Download button not working when there are multiple recepients

### ISSUE THREAD

**Issue by AbhinavAwesome** [documenso/documenso#531]
As shown in the video, the download button is not working when there are multiple recipients, but it works for single recipient.

https://github.com/documenso/documenso/assets/145282438/3f55baf5-525a-4bb2-a60d-4463d9c0ae81

**Comment by AbhinavAwesome** [comment]
I would like to work on this if approved

**Comment by zahid47** [comment]
I just checked it, and for me, it is not working even with 1 recipient. Maybe the issue isn't the number of recipients?

**Comment by dephraiim** [comment]
I have not been able to reproduce this so far, download works for me

![CleanShot 2023-10-05 at 22 15 14](https://github.com/documenso/documenso/assets/55143799/b3bed7a0-00c2-4dc8-9b18-37d1c591091d)

Can you check for logs when you click on the download button?

**Comment by dguyen** [comment]
Just noting I also can't replicate this, tested both Ubuntu & MacOS.

**Comment by AbhinavAwesome** [comment]
Download button is working now. Maybe there was some temporary issue.This can be closed
