### ISSUE TITLE
Account creation on marketing pricing page

### ISSUE THREAD

**Issue by dguyen** [documenso/documenso#532]
## Issue Description

Currently when a user navigates to the `/pricing` page and submits the form to claim the 'early adopter plan', an account is unknowingly created for them regardless if they complete the stripe checkout out not.

Previously this wasn't an issue, but with the introduction of free accounts users who previously didn't complete the stripe checkout will find that an account already exists when they go to sign up.

There might also be an issue where a user creates an free account, then navigates to the pricing page to claim the plan and have their password reset since we appear to upsert the user with a random password during this process.

## Steps to Reproduce

1. Navigate to the marketing pricing page
2. Click 'Signup Now' and submit the form with your details
3. Regardless of the outcome (error or stripe redirect) navigate to the web app
4. Sign up with the same credentials you entered in step 2 
5. You should be informed that an account already exists

## Expected Behavior

You should be able to proceed with creating an account in step 5, since you never explicitly signed up before.

## Current Behavior

You are informed that an account already exists even though you never explicitly created an account

## Additional notes

- The user can go through the forgot password flow, but this obviously isn't optimal
- We probably can't resolve this for users who already created an account via `/pricing` without a spicy migration

**Comment by anjy7** [comment]
Is this issue public? If yes then I would like to take this

**Comment by dguyen** [comment]
Not yet, this still requires discussion.

**Comment by Abhijit20112003** [comment]
Please Close the issue. A pull request has already been made

**Comment by dguyen** [comment]
@Abhijit20112003 not yet

We will mark this public once it's ready

**Comment by dguyen** [comment]
@Abhijit20112003 which pull request?

**Comment by Mythie** [comment]
Solved this with our recent free plan updates, dangling accounts were removed as part of this change as well 🙌
