### ISSUE TITLE
[Bug] Ability to mark Document signing as completed without actually signing the document

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#536]
Ability to mark Document signing as completed without actually signing the document

https://github.com/documenso/documenso/assets/145282438/a7464dde-541d-4bc9-8d04-b04011788a42

As shown in the video, we are able to click on complete button without signing.Ideally it should ask the user to sign the document.
Although it  does  not proceed on the ui but the document signing is marked completed.
At last if we download the document we do not see any signature in the final document.

Steps to reporduce

1.Create a new documenso signing with at least two receipients.
2.sign the document normally with one user.
3. with other user ,click on the signing link 
4.click on the signature field . make signature, after that click on cross (x) 
5.click on signature again.
6.now click on complete , and wait for 30 seconds.
7.Ui will not proceed but spinner icon keeps on spinning
8.Go to email and click on the same link to sign again.
9. it will show that document is already signed, download the document
10.there will be no signatures
11. Now go to the documenso dashboard, it will be marked as completed. download the file. it will have no signatures.

Expected Behavior
1.When we click on complete without signing, we should get a prompt to complete signing
2.Document should not be marked as completed.

Current Behavior
1.the spinner keeps on spinning
2.document is marked as completed without any signature

Environment
OS:ubuntu 22
Browser:Chrome Version 117.0.5938.132 (Official Build) (64-bit)

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Abhinav-Developer-23** [comment]
I would like to work on this ,if this is approved

**Comment by dephraiim** [comment]
In my opinion, marking an unsigned document as completed could lead to confusion. Users might assume that a "completed" status implies that all necessary signatures have been collected, which might not be the case.

**Comment by dguyen** [comment]
Yep replicated, please go ahead.

**Comment by Abhinav-Developer-23** [comment]
This issue is present even if we click outside the modal.
I am fixing this to in same pull request.

**Comment by Abhinav-Developer-23** [comment]
Please review the pull request
