### ISSUE TITLE
Add a lint staged task for package.json changes

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#546]
## Improvement Description

Add a lint-staged task that identifies if any `package.json` files have been modified and then runs `npm install` to ensure we always have the latest package.json file.

## Rationale

Whenever I encounter an issue I like to try and solve it for good so we don't have to worry about it again. As per #523 we accidentally forgot to commit the package-lock file and thus caused CI failures, could have happened to anyone so we should try and alleviate the burden of remembering such a mundane thing.

## Proposed Solution

Create the lint staged task as per above

## Alternatives (optional)

N/A

## Additional Context

N/A

## Checklist

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by adityadeshlahre** [comment]
i would love to work on this issue! :smile:

**Comment by Mythie** [comment]
Sounds great!
