### ISSUE TITLE
ENV variable undefined in local development

### ISSUE THREAD

**Issue by mayukh551** [documenso/documenso#552]
After running `npm run dev`, I move to localhost:3000, and it displays this error that there the env variable `NEXT_PRIVATE_DATABASE_URL` is undefined.

## Issue Description

![image](https://github.com/documenso/documenso/assets/82811112/d5b4dd4f-7ff2-4a1c-8843-163e5e54eb35)

---

How can I fix this? Do I need to install `dotenv` ?

**Comment by 18feb06** [comment]
Please check that env variable NEXT_PRIVATE_DATABASE_URL have the connection string or not.
If no, then please store postgresql db connection string and then proceed according to instructions given in [readme file](https://github.com/documenso/documenso/blob/feat/refresh/README.md).

**Comment by mayukh551** [comment]
@18feb06 
Ok the issue is resolved. Thanks for your help!
