### ISSUE TITLE
bug(name_field): name field can be update with "spaces_only"

### ISSUE THREAD

**Issue by adityadeshlahre** [documenso/documenso#555]
I was trying to update names. There i found that name can be updated with spaces only!

## Issue Description

In profile section in name tab name can be updated with spaces only "        ".

## Steps to Reproduce

https://www.loom.com/share/fbb762fd704844caac63b88ef2f83e91?sid=3729b00c-b1c5-4df5-b7bb-09f13029f6aa

## Expected Behavior

It should trim the name and update it else should give same error which it gives when we try to update name without any character.

## Current Behavior
In profile section in name tab name can be updated with spaces only "        ".

## Environment

- OS: [Arch Linux]
- Browser: [Brave]
- Version: [v1.59.117]

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by adityadeshlahre** [comment]
I would like get it assigned.
if it gets public tag !
Thank You :smiley:

**Comment by catalinpit** [comment]
Nice catch; thanks for reporting it! Also, please go ahead and work on it. 👍

**Comment by adityadeshlahre** [comment]
Hey @dguyen @catalinpit just a follow up comment.
I have raised PR you can check it.
if any changes required let me know.
Thank You :smile:
