### ISSUE TITLE
[Bug] Download Button not working for some files

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#561]
The download button on the dashboard does not work for some files.

## Issue Description

The download button on the dashboard does not work for some files.
for example
https://www.sldttc.org/allpdf/21583473018.pdf

## Steps to Reproduce
1. create a signer for this https://www.sldttc.org/allpdf/21583473018.pdf with at least two recipients in staging
2. Sign using both the recipients 
3. Go to the dashboard and download the file. you will get an error in the console and the file will not download

below is the error message in the console output

Uncaught (in promise) TRPCClientError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
at s.from (9235-3b4546a79de2921d.js:9:30071)
at 9235-3b4546a79de2921d.js:9:32103
## Expected Behavior
Download should start

## Current Behavior

It is not downloading and no error is shown in the ui

## Screenshots (optional)

https://github.com/documenso/documenso/assets/145282438/ba8d56e8-b363-49d4-8429-d26218b89289

## Environment

- OS: ubuntu 22
- Browser: Version 118.0.5993.32 (Official Build) beta (64-bit) 

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by 3xp10it3r** [comment]
Assign this to me...
I can work

**Comment by catalinpit** [comment]
Hey @Abhinav-Developer-23, thanks for reporting this bug!

@3xp10it3r assigned it to you. Thanks.

**Comment by 3xp10it3r** [comment]
Working on it

**Comment by 3xp10it3r** [comment]
will raise PR today.

**Comment by lalitkumawat1m** [comment]
Hello Team, I want to work on this issue please assign it to me

**Comment by catalinpit** [comment]
Hey @lalitkumawat1m, it seems that @3xp10it3r works on it.  I'll assign it to you if [3xp10it3r](https://github.com/3xp10it3r) doesn't reply in the next 2-3 days.

@3xp10it3r are you still working on this issue?

**Comment by 3xp10it3r** [comment]
Yes just give me today. i will be completing this. 
thanks

**Comment by catalinpit** [comment]
Thanks for the update @3xp10it3r! No rush, just wanted to see if there is any update. :-)

**Comment by poorna-prakash-sr** [comment]
Hey I can resolve this one!
