### ISSUE TITLE
Can't drag the fields from Add Fields sections

### ISSUE THREAD

**Issue by Udit-takkar** [documenso/documenso#564]
## Improvement Description

You can't just drag and drop fields

https://github.com/documenso/documenso/assets/53316345/76635699-9c21-4ad9-b364-c4d35c722a30

## Rationale

- I should be able to drag and drop fields by clicking on any field and then releasing on the exact target. 

OS:- Macos Sonoma
Browser: Braver
on latest feat/refresh branch

**Comment by Abhinav-Developer-23** [comment]
I am not able to replicate this. I am able to drag and drop without any issues.

**Comment by dguyen** [comment]
I can't replicate it as well.

Can you please update the issue description with your environment?

Example template can be found here:

https://github.com/documenso/documenso/blob/feat/refresh/.github/ISSUE_TEMPLATE/bug-report.md#environment

**Comment by Udit-takkar** [comment]
@dguyen the dragging works fine on the first page only. try uploading a document with multiple pages (2 in my case) then click the filed and drag the field and only release the click on the target. (on 2nd page which i tried in the video).
