### ISSUE TITLE
Improve Password Validation

### ISSUE THREAD

**Issue by mayukh551** [documenso/documenso#568]
## Improvement Description

The Zod schema object checks if the `password` is atleast 6 characters long or not.

But for a strong password we should ask the users to create a password that is 6 characters long and has the following characters:
- UpperCase
- Number
- Symbol

password Examples: heyThere#366, ThisIsATestPassoword#100

## Rationale

The benefit of creating and using a password that has an uppercase, lowercase, number, and a symbol is that it makes it much more difficult for hackers to crack. 

Hackers often use automated software to try to guess passwords, and these programs are typically very good at guessing simple passwords that only use one type of character.

## Checklist

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by adithyaakrishna** [comment]
Hey @mayukh551, there seems to be an existing issue for the validation improvement here, https://github.com/documenso/documenso/issues/464, and I've been working on the same in this PR, https://github.com/documenso/documenso/pull/469 as well

**Comment by mayukh551** [comment]
oh my bad!
Closing this issue...
