### ISSUE TITLE
(Error: Invalid URL) on Main Page on Self Host

### ISSUE THREAD

**Issue by 18feb06** [documenso/documenso#573]
(Error: Invalid URL) on Main Page on Self Host.

## Issue Description

After pulling latest changes. When ever I start the server and approch it's web app at 'http://localhost:3000'. It give 'Error: Invalid URL'.

## Steps to Reproduce

1. Pull latest changes from 'feat/refresh' branch.
2. Start the setup.
3. Approach web app on browser.

## Expected Behavior

Should work normally as before.

## Current Behavior

Displaying error: INVALID URL

## Screenshots (optional)

https://ibb.co/ZMkmJjh

## Environment

- OS: Ubuntu 22.04
- Browser: Chrome

## Checklist

- [ x ] I have searched the existing issues to make sure this is not a duplicate.
- [ x ] I have provided steps to reproduce the issue.
- [ x ] I have included relevant environment information.
- [ x ] I have included any relevant screenshots.
- [ x ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by 18feb06** [comment]
I would love to work on it.

**Comment by SidVermaS** [comment]
@18feb06 
Here's the fix:
https://github.com/documenso/documenso/pull/574

**Comment by catalinpit** [comment]
Hey @18feb06, thanks for the report. Please go ahead and fix it!

@SidVermaS, thanks for the PR, but @18feb06 asked first to pick up the issue. We've recently updated the contributing guidelines, which specify that `Before taking an issue, ensure that: [....] No one has expressed intention to work on it.`. You can see the full guide [here](https://github.com/documenso/documenso/blob/feat/refresh/CONTRIBUTING.md).

**Comment by 18feb06** [comment]
@SidVermaS's pull request helped alot. Thanks @SidVermaS 😊
