### ISSUE TITLE
[BUG] Loading State in Wrong Subscribe Button 

### ISSUE THREAD

**Issue by PeterKwesiAnsah** [documenso/documenso#577]
## Issue Description
I tried to subscribe to a plan. Upon clicking on a subscribe button, two loading states were triggered instead of one.

## Steps to Reproduce

1. Go To the Billing Page in Settings
2. Click on a subscribe button in a Plan card

## Expected Behavior

One loading state

## Current Behavior
Two loading  button states show

## Screenshots (optional)

![Screenshot (78)](https://github.com/documenso/documenso/assets/31078314/7463c9cc-1fc6-49f1-89ae-b5361fe618cd)

## Environment

- OS: Linux
- Browser: Chrome

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by mittalsam98** [comment]
I would like to pick this up

**Comment by PeterKwesiAnsah** [comment]
@mittalsam98 I'm already taking a swing at it

**Comment by Mythie** [comment]
One thing to note and a reason why I left this the way it is, we don't want a user to click a second subscription button while a checkout is loading. This means that while loading all buttons should be disabled.

**Comment by catalinpit** [comment]
Hey @PeterKwesiAnsah, thanks for opening the issue & PR! However, we recently updated the contribution guide, which states that you should `Comment on the issue with your intention to work on it` and get it assigned to you before starting to work on it.

In this case, @mittalsam98 should've been assigned the issue.

The reason for this update is to bring more order and improve the contribution process. Thanks for understanding!

![IMG_7832](https://github.com/documenso/documenso/assets/25515812/dd3e9fda-5d04-4436-9ab4-86aa715ad773)
*Source: [Contribution Guide #taking-issues](https://github.com/documenso/documenso/blob/feat/refresh/CONTRIBUTING.md#taking-issues)*

**Comment by PeterKwesiAnsah** [comment]
@catalinpit Got it. Thanks Man!

**Comment by mittalsam98** [comment]
Hey @catalinpit , thanks for assigning this to me. I will try to raise a fix ASAP

**Comment by catalinpit** [comment]
Hey @mittalsam98, the issue reporter already started working on this. Normally, you would have priority since you asked first, but can we leave it like this for this one, please? To avoid confusion.

I apologize for this, but it takes a while until everyone gets familiar with the new guidelines.

**Comment by Dun-sin** [comment]
@catalinpit can it be given an assigned label or the individual working on it be shown to be assigned

**Comment by mittalsam98** [comment]
Hey @catalinpit it seems @PeterKwesiAnsah not working on it, didn't hear any update from him

**Comment by PeterKwesiAnsah** [comment]
@mittalsam98 I have already created a PR for this 2 weeks ago.

**Comment by mittalsam98** [comment]
Okay , my bad, I didn't check old messages

**Comment by niranjan-official** [comment]
Can I get assigned to work on this issue?

**Comment by dguyen** [comment]
Apologies to everyone who has put work into this, this one seemed to fall through the cracks and mishandled on our part.

Lets close this one out soon.

@niranjan-official I've assigned it to you

**Comment by niranjan-official** [comment]
Thankyou for assigning, hope I can fix it in a couple of days.

**Comment by adithyaakrishna** [comment]
Hey @niranjan-official,
Could you pls let us know if you have any updates on this issue?

**Comment by niranjan-official** [comment]
> Hey @niranjan-official,
> Could you pls let us know if you have any updates on this issue?
> 

I got stuck while setting up locally
