### ISSUE TITLE
[Bug] can not upload more files because of incorrect upload limit

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#578]
## Issue Description

If we have two accounts, on one(account 1) we have reached the limit, on the other account (account 2) we have not reached the limit.
if we login to account 2 we are getting (You have reached your document limit) and the add a document button is disabled.

## Steps to Reproduce
1. Log in to the account where the limit is reached .
2. try uploading one more file 
3. you will get (You have reached your document limit). and the upload button will be disabled
4. now logout
5. Log in with account 2 where the limit is not reached.
6. Here your upload button will be disabled.

## Expected Behavior

The upload button should not be disabled on account 2

## Current Behavior

the upload button is disabled on account 2

## Screenshots (optional)

https://github.com/documenso/documenso/assets/145282438/9d9a1ffc-5b50-44c8-963b-822bbc46a0c4

## Environment

- OS: ubuntu 22
- Browser: Chrome (Version 118.0.5993.32 (Official Build) beta (64-bit))

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Abhinav-Developer-23** [comment]
I am working on it

**Comment by Mythie** [comment]
Hey there, since this involves EE code I’ll unfortunately have to take it.

Understand the issue and just need to add an effect for user account
changes.

**Comment by Mythie** [comment]
Completed as part of [this commit](https://github.com/documenso/documenso/commit/0b5017617835493690cd02f1398ce96576e4bbb6)

Thanks for raising!

/tip 25
