### ISSUE TITLE
[BUG] web: Typo in `Draft` empty-state of Documents.

### ISSUE THREAD

**Issue by Bitnagar** [documenso/documenso#582]
## Issue Description

There is a minor typo in the `empty-state.tsx` component for the `Draft` status:

![typo-documenso](https://github.com/documenso/documenso/assets/88842947/6d576297-b3bd-4353-8b18-fef8c7cba6bf)

## Steps to Reproduce

- Go to dashboard of the app in staging environment.
- Check the `Draft` section.

## Expected Behavior

`then` should be changed to `the`

## Current Behavior

There is a minor typo in the `empty-state.tsx` component for the `Draft` status.

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by dguyen** [comment]
Could you please also update these ones as well?

> There are no completed documents yet. Documents that you have created or received that become completed will appear here later.

There are no completed documents yet. Documents that you have created or received will appear here once completed. 

> All documents are currently actioned. Any new documents are sent or recieved they will start to appear here.

All documents have been processed. Any new documents that are sent or received will start to appear here.
