### ISSUE TITLE
[BUG] web: `continue` button hides when email inputs overflow in `add signers` section

### ISSUE THREAD

**Issue by Bitnagar** [documenso/documenso#586]
## Issue Description

After uploading the document, when we try to add multiple signers, the `continue` button hides when there too many inputs or when inputs overflow.

## Steps to Reproduce

1. Go to dashboard and add a new document.
2. Click on `add signers` few times so that the whole container overflows with inputs.
3. When container overflows, it hides the `continue` button.

## Expected Behavior

Overflow should not be hidden in the CSS as shown so as to handle the worst case scenario:

https://www.loom.com/share/bd7d54bb0a4f45e0b69f87452c57565a?sid=180d0342-6b08-4898-832c-feb1b71859b7

## Current Behavior

https://www.loom.com/share/ce41615ae6e64326bcfce0bdfac7d792?sid=c8577d26-fd9f-4a37-8433-baea3cd8406a

## Environment

- OS: staging environment
- Browser: chrome
- Version: latest

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Bitnagar** [comment]
Happy to raise a PR :)

**Comment by dephraiim** [comment]
Thank you for this; however, this issue has been noted previously here, https://github.com/documenso/documenso/issues/441 and @adithyaakrishna is looking at it in this PR https://github.com/documenso/documenso/pull/460, hence I will be closing this duplicate for better tracking and resolution.
