### ISSUE TITLE
Improve the README for self-hosting

### ISSUE THREAD

**Issue by olivierlambert** [documenso/documenso#589]
## Improvement Description

Right now, there's no guide on how to deploy Documenso outside for dev purpose. I'm not counting Docker because some people might want to do the deployment the way they want. The goal of this improvement (that I can realize) is to update the README for a step-by-step instruction for install and updating an installation.

## Rationale

Current pain points:
* no guide on how to do a manual install from scratch (no docker, no black box)
* must read what's in the Docker file to replicate it

## Proposed Solution

* I can contribute to update the README file providing the instruction I used
* Also showing it works with a reverse proxy in front of it doing the SSL work

## Alternatives (optional)

* I could write a guide somewhere else, but why not contributing to the upstream directly?

## Additional Context

None

## Checklist

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mythie** [comment]
Sounds great! I’d also consider writing a bash script as part of the guide that does most of the steps assuming the target environment is using apt for package management.

**Comment by olivierlambert** [comment]
@Mythie on which branch do you want me to create the PR against?

**Comment by adithyaakrishna** [comment]
@olivierlambert AFAIK, it would be the `feat/refresh` branch 👀

**Comment by olivierlambert** [comment]
Should I close the issue since the PR is merged?

**Comment by Mythie** [comment]
Yep sorry about that one!
