### ISSUE TITLE
Error: Cannot find module '/home/tameem/Desktop/18feb06/documenso/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'

### ISSUE THREAD

**Issue by 18feb06** [documenso/documenso#592]
Getting following error:
Error: Cannot find module '/workspace/documenso/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'

## Issue Description

On sending request to api, Getting following error:
Error: Cannot find module '/home/tameem/Desktop/18feb06/documenso/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'

## Steps to Reproduce

1. start server
2. send request to api

## Expected Behavior

Should work normally.

## Current Behavior

Giving following error:
Cannot find module '/workspace/documenso/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node'

## Environment

- OS: ubuntu 22.04
- Browser: Chrome

## Checklist

- [ x ] I have searched the existing issues to make sure this is not a duplicate.
- [ x ] I have provided steps to reproduce the issue.
- [ x ] I have included relevant environment information.
- [ x ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by 18feb06** [comment]
I would love to solve this.

**Comment by dephraiim** [comment]
Can you run this and try again?
```
npm run reset:hard
```

**Comment by 18feb06** [comment]
@dephraiim I have tried this but it is not working.
I know its due to bcrypt version "^5.1.1".
If we remove bcrypt from package.json as it was before. It will work normally. I removed bcrypt from package.json and then installed all packages. Then it started working normally.

**Comment by 18feb06** [comment]
Kindly allow me to solve this

**Comment by Mythie** [comment]
That won't be the issue though sorry. Could you confirm the Node.js version you're using right now?

`bcrypt` has been a dep for some time and no recent changes should have broken that, looking at the `package-lock.json` I can see that there's nothing that could be causing a realm error or similar.

**Comment by 18feb06** [comment]
node version: 18.17.1

**Comment by 18feb06** [comment]
Closed this issue because it is solved

**Comment by Mythie** [comment]
Apologies, what was the fix on your end?

**Comment by 18feb06** [comment]
To remove "bcrypt": "^5.1.1" from main package.json file, which is already done
