### ISSUE TITLE
[Improvement] Validation messages in single-player mode can be improved.

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#593]
Validation messages in single-player mode can be improved.
## Improvement Description

Validation messages in single-player mode can be improved.

## Rationale

Someone who does not have knowledge of programming  may not understand the terms "null" or "string"

![Screenshot from 2023-10-26 00-14-28](https://github.com/documenso/documenso/assets/145282438/b17d1a74-2c0d-4c8e-82fc-aa40aabf768c)

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Hallidayo** [comment]
I can pick this one up

**Comment by catalinpit** [comment]
Hey @Abhinav-Developer-23, thanks for opening this issue. I agree with you that those error messages could be improved.

@Hallidayo thanks for your interest. I'll assign this to you.

**Comment by luckyklyist** [comment]
I see this issue has been inactive for a week. I can work on it. Also, on the 'Forgot Password' page, the same issue exists in the validation message.
<img width="813" alt="Screenshot 2023-11-01 at 9 04 17 PM" src="https://github.com/documenso/documenso/assets/35479077/7fb647c5-3f08-4af8-9b5a-a9cb78cf8080">

**Comment by catalinpit** [comment]
Hey @Hallidayo, do you have an update on this?

**Comment by catalinpit** [comment]
Hey @luckyklyist, thanks for your interest! You can go ahead and work on it.

**Comment by anikdhabal** [comment]
@Abhinav-Developer-23 fix this one also
![Screenshot 2023-11-08 131957](https://github.com/documenso/documenso/assets/81948346/4f121178-bed8-47d8-a1f3-b027b5a8791d)

expected:-
![Screenshot 2023-11-08 132023](https://github.com/documenso/documenso/assets/81948346/7dff015b-2ac7-4c14-9bcf-687860cdf6ce)

**Comment by anikdhabal** [comment]
> I see this issue has been inactive for a week. I can work on it. Also, on the 'Forgot Password' page, the same issue exists in the validation message. <img alt="Screenshot 2023-11-01 at 9 04 17 PM" width="813" src="https://user-images.githubusercontent.com/35479077/279718012-7fb647c5-3f08-4af8-9b5a-a9cb78cf8080.png">

Hey @luckyklyist, since this issue belongs to the single-player mode, please focus on fixing the validation messages for single-player mode. I am addressing the same validation message issue for the Documenso app here

**Comment by luckyklyist** [comment]
sure , working on it
