### ISSUE TITLE
[improvement] incorrect default signature

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#594]
## Issue Description

Suppose a user has 2 emails. They are signed in with email1 on documenso and email2 on Google Mail. When they receive an email to sign a document on email2, the default signature on the signature pad is from email1.signature

## Steps to Reproduce
1. create a signer using email1
2. add email2 in the recipient
3. sign in to Gmail using email2
4. open the link. The default signature will be of email1
## Expected Behavior

Signature pad should email empty

## Current Behavior

We get the signature of email1

## Screenshots (optional)

https://github.com/documenso/documenso/assets/145282438/dd99d0f8-b0c4-4cf8-b35c-79038ace68c9

## Environment

- OS: ubuntu 22
- Browser:Chrome

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by 18feb06** [comment]
It is because you are already logged in documenso. When you click on that signature invitaion link containing recipient token on email, you are redirected to signature page of documenso where you are already logged in , so that is reson that your default signature is already placed on signature pad.

**Comment by 18feb06** [comment]
But I would love to solve this.

**Comment by catalinpit** [comment]
Hey @Abhinav-Developer-23, nice catch! Thanks for bringing this up!

I agree that this could be improved to avoid confusion. @18feb06, if you want, you can go ahead. I'll assign this to you.

For context: when a user is signed in, the app pre-fills the signature pad with the one from the profile of the logged user. One way to improve this would be to leave the signature blank if the recipient email doesn't match the logged user's email.

**Comment by 18feb06** [comment]
> Hey @Abhinav-Developer-23, nice catch! Thanks for bringing this up!
> 
> I agree that this could be improved to avoid confusion. @18feb06, if you want, you can go ahead. I'll assign this to you.
> 
> For context: when a user is signed in, the app pre-fills the signature pad with the one from the profile of the logged user. One way to improve this would be to leave the signature blank if the recipient email doesn't match the logged user's email.

OK I understand
