### ISSUE TITLE
[improvement]: improve the early adopters plan input section

### ISSUE THREAD

**Issue by anikdhabal** [documenso/documenso#597]
## Improvement Description

1. The step message is out of sync with the flow. Steps can be reduced by using the "Next" button on the email input field without having to click the "Next" button on the name input field.

2. The "Sign" button becomes clickable after making changes in the name input field. The "Sign" button should only become enabled after clicking the "Next" button in the name input field for the first time.

3.  After completing all the steps, when the "Sign" button becomes clickable, the message currently displayed states "1 step(s) until signed." This can be quite confusing because all the steps have already been completed, and it's ready to be signed. This message should be replaced with a success message. 

loom video:- https://www.loom.com/share/a2d5bfa634534d2ebf65bb858242765b
## Proposed Solution

1. The "Sign" button is only enabled for clicking after clicking the "Next" button in the name input field.
2. After completing all the steps, the step message should be a success message.

## Additional Context

I'm seeking community feedback and suggestions to improve this.

**Comment by anikdhabal** [comment]
I am ready to tackle this issue.

**Comment by Abhinav-Developer-23** [comment]
I guess, you should check if this issue is there in staging environment.

**Comment by Mythie** [comment]
G'day, that's because the final step would be to pay via stripe which will send you to a claimed page. I'm happy to entertain the PR which I'll review shortly.

**Comment by anikdhabal** [comment]
> G'day, that's because the final step would be to pay via stripe which will send you to a claimed page. I'm happy to entertain the PR which I'll review shortly.

Thank you
