### ISSUE TITLE
[Bug] Cancel button does nothing

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#604]
Cancel Button on the document signing page does nothing

## Steps to Reproduce

1. Go to the received mail for document signing
2. Open the link
3. Click on cancel.

## Expected Behavior

It should close the page

## Current Behavior

Nothing happens

## Screenshots (optional)

https://github.com/documenso/documenso/assets/145282438/a7b01d49-3a3d-4347-b4e6-12f9e7172da4

## Environment

- OS: Ubuntu
- Browser: Chrome

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Abhinav-Developer-23** [comment]
I can work on this

**Comment by Mythie** [comment]
Hey there, we had handling for this by checking the history length on `window.history` but it seems as though this isn't super reliable:

<img width="871" alt="image" src="https://github.com/documenso/documenso/assets/13398220/4430598d-e99a-48ad-9d08-625f4f09082f">

Based on our code and handling the button should be disabled, my guess is this might be a security feature built into chrome to prevent history snooping.

**Comment by catalinpit** [comment]
> I can work on this

Assigned it to you.
