### ISSUE TITLE
BUG: 'Page Not Found' at share page for document signed in SINGLE PLAYER MODE

### ISSUE THREAD

**Issue by 18feb06** [documenso/documenso#605]
'Page Not Found' at share page for document signed in SINGLE PLAYER MODE

## Issue Description

'Page Not Found' at share page for document signed in SINGLE PLAYER MODE

## Steps to Reproduce

1. Go to marketing app.
2. scroll to bottom.
3. In Footer, select SINGLE PLAYER MODE.
4. Upload document and complete signing process.
5. On Success page, click on share button and copy the link.
6. Go to that Share Link and you will find 'Page Not Found' Error.

## Expected Behavior

Should show me signed document.

## Current Behavior

'Page Not Found' Error.

## Screenshots (optional)

[Screencast from 10-29-2023 09:03:23 PM.webm](https://github.com/documenso/documenso/assets/88766161/48984132-a959-48c9-a16c-deba402d5f2d)

## Environment

- OS: Ubuntu 22.04
- Browser: Chrome

## Checklist

- [ x ] I have searched the existing issues to make sure this is not a duplicate.
- [ x ] I have provided steps to reproduce the issue.
- [ x ] I have included relevant environment information.
- [ x ] I have included any relevant screenshots.
- [ x ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by 18feb06** [comment]
I would love to work on this. 😊

**Comment by luckyklyist** [comment]
This issues also talks about the #603 . The share links redirect you to the homepage https://documenso.com/ .

**Comment by 18feb06** [comment]
Bro this is change because on marketing app there is no share page for single player mode.
That #603 is another case, which exists in web app.

**Comment by Mythie** [comment]
Hey there, this is simply an error on my behalf. Changing the document share button to use `process.env.NEXT_PUBLIC_WEBAPP_URL` rather than `window.location.origin` will solve it.

The marketing site can have share links created for _single player_ documents which is intended to be used for sharing on socials.

**Comment by 18feb06** [comment]
@Mythie But it will demand signin details as it will access web app. That is why I am creating a share page for marketing app.

**Comment by Mythie** [comment]
It won't the share url is for social sharing, see my elaboration in #603 😄

**Comment by 18feb06** [comment]
@Mythie Okay, Now I understand.
