### ISSUE TITLE
Unprotected Route : /sign/[token]

### ISSUE THREAD

**Issue by raj-saroj-vst-au4** [documenso/documenso#607]
## Issue Description
The route or page /sign/[token] is unprotected.

## Steps to Reproduce

1. Create a new document by uploading > add signers > add fields > add subject > send
2. From the /documents page > click on 'sign' for the doc
3. From the /sign page, copy the full url viz. https://app.documenso.com/sign/[token]... 
4. From browser, Open a new incognito window and paste the url

## Expected Behavior

Should've redirected to / or login route

## Current Behavior

Allows unauthenticated user to sign 

## Screenshots (optional)
![image](https://github.com/documenso/documenso/assets/54412653/1e09d3be-752b-4287-8704-867586918e85)
![image](https://github.com/documenso/documenso/assets/54412653/eab2ab7e-368a-4a9a-a0fa-ec1425d0350b)

## Environment

- OS: Deepin OS
- Browser: Brave
- Version: latest

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by catalinpit** [comment]
Hello @raj-saroj-vst-au4, thanks for bringing this to our attention! However, this is the intended behavior. People should be able to sign a document with an account as well.

**Comment by raj-saroj-vst-au4** [comment]
But unwanted or random unathenticated people can also also sign my document & my dashboard shows status completed.

**Comment by Mythie** [comment]
> But unwanted or random unathenticated people can also also sign my document & my dashboard shows status completed.

That would require them knowing the signing token which would be incredibly hard unless a recipient leaked it prior to signing.
