### ISSUE TITLE
[Bug] Days filter not working

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#610]
The days filter on the dashboard is not working

## Steps to Reproduce

1. Go to https://stg-app.documenso.com/documents?status=COMPLETED&period=7d&page=1&perPage=50
2. increase rows per page to 50
3. click on  last 7 days

## Expected Behavior

It should show documents created in the last 7 days

## Current Behavior

It shows all documents

## Screenshots (optional)

https://github.com/documenso/documenso/assets/145282438/5a9bd157-2cfc-486a-9be2-48695678ad69

## Environment

- OS: Ubuntu
- Browser: Chrome

## Checklist

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Mythie** [comment]
Go for it! This should involve creating a type guard for the `period` param to ensure it's one of `[7d, 14d, 30d]` and then passing it along to the `findDocuments` method.

With that we should be able to use Luxon to subtract the number of days from the period.
