### ISSUE TITLE
[Improvement] - Improve the issue templates with issue forms (supported via `yml`)

### ISSUE THREAD

**Issue by sachinmmane** [documenso/documenso#611]
## Improvement Description
GitHub supports the [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). This improvement allows users to create issues using a structured and visually appealing form. This functionality is facilitated through a `yml` file for the issue template.

Below, you'll find an example of an existing issue template and another example of the same template after integrating the new `yml` file.

----------------------------------------
**Existing Issue Template for Bug Report**
![](https://user-images.githubusercontent.com/54999683/279059613-e96eab11-25fe-4b68-98e2-3e57bad4a6b8.png)

----------------------------------------
**New Issue Template**
![](https://user-images.githubusercontent.com/54999683/279060279-a572a71b-4f71-4ba6-b27f-d4c0ef807a3a.png)

## Rationale

This change will improve the user experience of creating the GitHub issue for users. They will see an nice form to raise a GitHub issue.  

## Checklist

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by sachinmmane** [comment]
This improvement is hande in the following pull request https://github.com/documenso/documenso/pull/612.

## Live Demo 
The live preview of this change and issue templates can be found here
https://github.com/sachinmmane/documenso/issues/new/choose

**Comment by catalinpit** [comment]
Dang, this is really neat! Thanks for this suggestion, @sachinmmane!

**Comment by Mythie** [comment]
Solved as per #612

**Comment by sachinmmane** [comment]
Thank you @catalinpit for your comment. Sure, I will take care of it in my future contributions.
