### ISSUE TITLE
npm run prisma:migrate-dev error

### ISSUE THREAD

**Issue by wangwenting-dev** [documenso/documenso#618]
### Issue Description

init database error:  version [last code]
npm run prisma:migrate-dev

> prisma:migrate-dev
> npm run with:env -- npm run prisma:migrate-dev -w @documenso/prisma

> with:env
> dotenv -e .env -e .env.local --

> @documenso/prisma@1.0.0 prisma:migrate-dev
> prisma migrate dev

Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "test", schema "public" at "127.0.0.1:5432"

Error: P3006

Migration `20230907074451_insert_old_data_into_document_data_table` failed to apply cleanly to the shadow database. 
Error:
错误: 函数 gen_random_uuid() 不存在
HINT: 没有匹配指定名称和参数类型的函数. 您也许需要增加明确的类型转换.
   0: sql_schema_connector::validate_migrations
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/lib.rs:324
   1: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:270

npm ERR! Lifecycle script `prisma:migrate-dev` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @documenso/prisma@1.0.0 
npm ERR!   at location: /home/documenso/packages/prisma

### Steps to Reproduce

npm run dx 

### Operating System [e.g., Windows 10]

Centos 7.9

### Version [e.g., 2.0.1]

feat/refresh

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Mythie** [comment]
Hey there, that migration should be able to apply cleanly.

is this for a local development environment or self hosted instance?

**Comment by wangwenting-dev** [comment]
local development

**Comment by Mythie** [comment]
Have you ran previous versions of the application or is this your first time?

**Comment by wangwenting-dev** [comment]
first run

**Comment by wangwenting-dev** [comment]
Do databases have version requirements?
my use version postgresql-12

**Comment by 18feb06** [comment]
@wangwenting-dev  Are you using docker??

**Comment by wangwenting-dev** [comment]
not using  docker
Usage steps：
1/npm i
2/vim .env    update database config
3/npm run prisma:migrate-dev 
setup3 out error

**Comment by 18feb06** [comment]
@wangwenting-dev I think you should use postgresql 15 because project requires postgresql 15

**Comment by Mythie** [comment]
Yeah I believe we support >= 13 sorry!

the docker compose file will have the tagged version of Postgres 😄

**Comment by catalinpit** [comment]
Thanks for reporting this! Please try Postgres 15, and if you have the same issue, feel free to open another issue.

**Comment by wangwenting-dev** [comment]
Thank you，After upgrading to Postgres 15, it was successful
