### ISSUE TITLE
Remove Scrollbars on Documents

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#62]
<img width="1053" alt="Screenshot 2023-04-09 at 10 55 55" src="https://user-images.githubusercontent.com/55143799/230768579-a7a33fdc-7a02-4aa5-a4b4-b9e407008747.png">

**Comment by ElTimuro** [comment]
Should it just cut off oder should the row be reduced in your opinion?
Currently everything but https://github.com/documenso/documenso/milestone/1 is not a top priority btw.

**Comment by dephraiim** [comment]
Closing this in favour of the https://github.com/documenso/documenso/tree/feat/refresh branch
