### ISSUE TITLE
Forget password Options for OAuth Users

### ISSUE THREAD

**Issue by luckyklyist** [documenso/documenso#620]
### Issue Description

For OAuth users, there is no password set in the database. Therefore, the 'Forgot Password' page will not be of any use to them. There should be an option to implement the creation of a password for OAuth users if they haven't set one would be a good idea.

### Steps to Reproduce

Log in with the OAuth provider Google, go to the profile page, and click on the 'Password' tab.

### Expected Behavior

There should be a way for the OAuth user to set the password.

### Current Behavior

When trying to add the password, the current password for the OAuth user is null, so there won't be forget password functionality for the oauth user.

### Screenshots (optional)

<img width="1335" alt="Screenshot 2023-11-02 at 1 31 40 PM" src="https://github.com/documenso/documenso/assets/35479077/c2b15636-7fd2-43cd-baea-fa64b386be37">

<img width="424" alt="Screenshot 2023-11-02 at 1 39 51 PM" src="https://github.com/documenso/documenso/assets/35479077/0772c6b6-6016-438a-bd0b-cd4df5c88a60">

### Browser [e.g., Chrome, Firefox]

Brave

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by luckyklyist** [comment]
After the approval of this issue, I would like to work on it.

**Comment by Mythie** [comment]
Can we confirm if the forgot password flow works? So when signed out click on forgotten password and work from there :)

**Comment by luckyklyist** [comment]
Yes, the 'Forgot Password' functionality is working. OAuth users can reset their password from there.

Should I add another tab to the settings page for 'Forgot Password'? Would that be beneficial for the UX?
<img width="1323" alt="Screenshot 2023-11-02 at 3 57 58 PM" src="https://github.com/documenso/documenso/assets/35479077/f5e6c41e-1abd-4b88-9436-13a1a9087ed8">

**Comment by Mythie** [comment]
Reserving for a write up tomorrow on options and complications

**Comment by G3root** [comment]
@luckyklyist in the context of OAuth, the responsibility for handling passwords should lie with the OAuth provider, not the application itself. It's normal to have the password being empty in the DB. Maybe we can show a message that the passwords should be handled in the relevant OAuth provider. thoughts @Mythie ?

**Comment by luckyklyist** [comment]
> @luckyklyist in the context of OAuth, the responsibility for handling passwords should lie with the OAuth provider, not the application itself. It's normal to have the password being empty in the DB. Maybe we can show a message that the passwords should be handled in the relevant OAuth provider. thoughts @Mythie ?

You can set a password for the OAuth user by visiting the "Forgot Password" link. However, the issue arises when the OAuth user encounters the "Change Password" tab. They might become confused because their password is null at that point, and they have to sign out to access the "Forgot Password" link. Therefore, we can improve the user experience in this area.

**Comment by NuggaN85** [comment]
How do I delete my account and test files?

**Comment by Mythie** [comment]
> Reserving for a write up tomorrow on options and complications

I failed this hard.

Since we're linking OAuth accounts to existing accounts (if they exist) we should allow for the password to be set or updated from the dashboard. That said we should retain the "Current Password" field for cases where a bad actor is attempting account takeover by stealing cookies or similar.

By requiring the current password we can ensure a bad actor can not simply reset the password for a user without prior knowledge of their account password (credentials compromised).

Instead for OAuth accounts that have no password set we can look to disable the "Current Password" with a tooltip explaining that they don't currently have a current password as they're using an OAuth provider. We then should update our `updatePassword` handler to accept an empty current password if the value is `null` within the database.

**Comment by luckyklyist** [comment]
@Mythie  , should we now include a field in the dashboard to allow OAuth users to set their password ?

**Comment by Mythie** [comment]
Yep as per above please! If the password in the database is `null` then disable the current password field and only allow the new password fields.

The tRPC handler will also need to be updated to accomodate for this.
