### ISSUE TITLE
[IMPROVEMENT]: more specific instructions for adding a document

### ISSUE THREAD

**Issue by Dun-sin** [documenso/documenso#621]
### Improvement Description

I think the following should be added:
- the type of file which can be uploaded
- the limit of the file to be uploaded
![image](https://github.com/documenso/documenso/assets/78784850/48fe0107-905c-4be0-b0a5-c676f2bc995b)

### Rationale

I tried using the app for the first time and the first time and immediately thought to upload msword to check as it ended with .doc extension, so specifying what file format/extension would be accepted.

Adding the limit it has would also help with users avoiding the large file and know beforehand what is required.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Dun-sin** [comment]
i would like to work on this if this is a accepted change and any way you want me to do that.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, thanks for the suggestions! I agree that adding the maximum document limit would be helpful. Regarding the doc type, do people usually sign non-pdfs?

no, they don't i know that, but when you go to image converter site for instance, they still indicate to upload an image, i mean we both know users are a mystery, it can be skipped btw doesn't really matter, the most important in my opinion is the file limit

**Comment by sumitbishti** [comment]
is anyone working on this issue?

**Comment by dguyen** [comment]
Apologies to those involved for the delay, this one seemed to have gotten lost.

@Dun-sin are you still interested in working on this feature? If not I can assign it to @sumitbishti 

To summarise some things:

> I tried using the app for the first time and the first time and immediately thought to upload msword to check as it ended with .doc extension, so specifying what file format/extension would be accepted.

I think changing the text to `Drag & drop your PDF document here.` should suffice.

> Adding the limit it has would also help with users avoiding the large file and know beforehand what is required.

Agreed, I believe that the current upload limit is 50MBs for the S3 upload transport we implemented. Currently if you select a file that exceeds the limit, it will silently error.

Since users would rarely upload a 50mb document, we can keep the UI clean by displaying a toast when they select a file that's too large. The toast should contain the information on the current current file size limit.

This would involve displaying a toast error saying the current file limit size when a file limit size error occurs via `onDropRejected` in `useDropzone`.

**Comment by sumitbishti** [comment]
Would be happy to work on this.

**Comment by Dun-sin** [comment]
> Apologies to those involved for the delay, this one seemed to have gotten lost.
> 
> @Dun-sin are you still interested in working on this feature? If not I can assign it to @sumitbishti
> 
> To summarise some things:
> 
> > I tried using the app for the first time and the first time and immediately thought to upload msword to check as it ended with .doc extension, so specifying what file format/extension would be accepted.
> 
> I think changing the text to `Drag & drop your PDF document here.` should suffice.
> 
> > Adding the limit it has would also help with users avoiding the large file and know beforehand what is required.
> 
> Agreed, I believe that the current upload limit is 50MBs for the S3 upload transport we implemented. Currently if you select a file that exceeds the limit, it will silently error.
> 
> Since users would rarely upload a 50mb document, we can keep the UI clean by displaying a toast when they select a file that's too large. The toast should contain the information on the current current file size limit.
> 
> This would involve displaying a toast error saying the current file limit size when a file limit size error occurs via `onDropRejected` in `useDropzone`.

you can give it to @sumitbishti

**Comment by dguyen** [comment]
@sumitbishti I've assigned it to you :)
