### ISSUE TITLE
[IMPROVEMENT]: issue template fixes and improvement

### ISSUE THREAD

**Issue by Dun-sin** [documenso/documenso#622]
### Improvement Description

here's a list of my suggestion:
- the number of fields are too long and can be dropped to 3 max
- the required field should be indicated
- adding a checkbox if the issue raiser wants to work on it
![image](https://github.com/documenso/documenso/assets/78784850/542278ce-c131-46a2-85d6-516183de20d2)

### Rationale

Will be talking from a user standpoint or contributor standpoint:
- number of fields: it's super tasking and looks pretty repetitive
- required fields: any contributor can just click on crate and they will be allowed which i'm guessing isn't what you want
- contributor wants to pick issue: it's an unneeded extra task to after creating an issue, ask to be assigned as the issue creator

### Proposed Solution

solution:
- number of fields:  we can achieve the same thing but in a shorter way, for instance:
 we can have the steps needed in a list format e.g 
 ```
  - tell us why the improvement is benefical
  - tell us the proposed solution
 ```
 here:
![image](https://github.com/documenso/documenso/assets/78784850/7d8e6e20-40c7-4bf3-8219-4d010859ec9a)
 and also combine additional information and alternatives in the same way
- required fields: you can add this to each body type: 
![image](https://github.com/documenso/documenso/assets/78784850/af1114c8-45fb-4f5b-89ed-f0740e4a9651)
- contributor wants to pick issue: add a checkbox for this and make it required

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by catalinpit** [comment]
Hey @Dun-sin, thanks for the suggestion! It looks good to me, but if we can make this easier and shorter, I'm up for it. Maybe the `Improvement Description` and `Rationale` could be mashed together. I also think that `Alternatives` and `Additional Context` could be optional.

I specifically like the points about making it obvious which fields are obvious and adding the checkbox so people can pick the issue easier.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, thanks for the suggestion! It looks good to me, but if we can make this easier and shorter, I'm up for it. Maybe the `Improvement Description` and `Rationale` could be mashed together. I also think that `Alternatives` and `Additional Context` could be optional.
> 
> I specifically like the points about making it obvious which fields are obvious and adding the checkbox so people can pick the issue easier.

yeah my main point for the longevity is to combine related fields, just like you said

**Comment by Mythie** [comment]
Wasn't assigned and I apologise for that but we've now incorporated the associated improvements ❤️
