### ISSUE TITLE
[IMPROVEMENT]: add github action to limit non public issues

### ISSUE THREAD

**Issue by Dun-sin** [documenso/documenso#625]
### Improvement Description

It would be great if there was a github action that automatically locks a new issue so only collabators can comment on it and when the public label is added to it, it automatically unlocks.

### Rationale

Would be beneficial for the maintainers to easily keep track of issues instead of going on manual, there won't be any confusion of `sorry this isn't a public issue`

### Alternatives (optional)

an alternative solution is to have it open by default with a public label or no label and once the public label is removed the issue is locked with a message saying if anyone has an opinion they can talk about it in the discord server

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by 18feb06** [comment]
I would love to work on this

**Comment by adithyaakrishna** [comment]
@Dun-sin Just voicing my thoughts here, if this is implemented, then the whole idea of open-source and meaning behind it kinda doesn't make sense. I mean, some contributors may have a new opinion or perhaps a different approach which can go unnoticed 😶

**Comment by Dun-sin** [comment]
> @Dun-sin Just voicing my thoughts here, if this is implemented, then the whole idea of open-source and meaning behind it kinda doesn't make sense. I mean, some contributors may have a new opinion or perhaps a different approach which can go unnoticed 😶

not exactly, from my understanding of how this project works that's the purpose of what the public and non-public issues serve, it doesn't stop people from voicing opinions because it's not for them, plus you can have your opinions in the PR. But that's just what I understand of what the labels serve.

**Comment by catalinpit** [comment]
Hey @Dun-sin, thanks for the suggestion! I'm not too convinced about this, but let's see what others think, too.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, thanks for the suggestion! I'm not too convinced about this, but let's see what others think, too.

you can see a working example here -> https://github.com/EddieHubCommunity/BioDrop/issues/9658

**Comment by catalinpit** [comment]
Thanks, will check it out!
