### ISSUE TITLE
dark-mode doesnt work when signin or signup

### ISSUE THREAD

**Issue by Divin-18** [documenso/documenso#628]
### Please check the boxes that apply to this improvement suggestion.

- [ ] I have searched the existing issues and improvement suggestions to avoid duplication.
- [ ] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Dun-sin** [comment]
works for me, you should fill in the issue template and further explain the issue
![image](https://github.com/documenso/documenso/assets/78784850/abd3cfd6-c02d-401d-85ed-e465c9ce4fd0)

**Comment by mittalsam98** [comment]
If this is a issue, I would like to raise a PR

**Comment by catalinpit** [comment]
Closed due to insufficient details.
