### ISSUE TITLE
improvement: fix the validation message for documenso app

### ISSUE THREAD

**Issue by anikdhabal** [documenso/documenso#635]
### Issue Description

There are some input fields where I believe improvements are needed for the error messages displayed when an input field is empty, and someone attempts to proceed to the next step.

1.) In the Sign-In form and the reset password form, when the password field is empty, it shows the message "String must contain at least 6 character(s)."

2.) The email field in the "Add Signer" form displays "String must contain at least 1 character(s)."

### Expected Behavior

1.)  When the password field is empty, the error message should be "Invalid Password," similar to the email field.

2.) Instead of "String must contain at least 1 character(s)," the email field should display "Email is required," similar to how the name field behaves.

### Screenshots (optional)

Current behavior:-

![Screenshot 2023-11-08 131922](https://github.com/documenso/documenso/assets/81948346/6813c47c-de03-4956-a66f-fee9e37ccfad)

![Screenshot 2023-11-08 132454](https://github.com/documenso/documenso/assets/81948346/c18c9271-f4bf-4256-8dfb-c5ce900d98b1)

![Screenshot 2023-11-08 145659](https://github.com/documenso/documenso/assets/81948346/56df6a86-6475-4d3f-aa2a-0737c7dfca65)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by anikdhabal** [comment]
I want to tackle this one.

**Comment by anikdhabal** [comment]
cc @Mythie @catalinpit

**Comment by catalinpit** [comment]
Hey @anikdhabal, thanks for the suggestions! Yes, I agree that the messages could be improved.

Just to make sure, this is for the Documenso app, right? Cause already have an open issue for the Singleplayer Mode https://github.com/documenso/documenso/issues/593

**Comment by anikdhabal** [comment]
> Hey @anikdhabal, thanks for the suggestions! Yes, I agree that the messages could be improved.
> 
> Just to make sure, this is for the Documenso app, right? Cause already have an open issue for the Singleplayer Mode #593

Thank you for your review. Since there was a similar issue for the single-player mode, I will now work on the problem specific to the Documenso app.

**Comment by anikdhabal** [comment]
Pls assign me this issue.
