### ISSUE TITLE
Make OG images great again

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#637]
### Improvement Description

Currently our signing card OG image has to use a helper function called `getAssetBuffer` which hits the live site to get the images and fonts that it requires. 

This is super slow and results in a decent lag time for image generation which had caused issues with Twitter OG cards that we've temporarily fixed by prewarming (#615) the images prior to sharing but this is a bandaid rather than a full term fix. 

I would ideally like to see us use the automagical `fetch(new URL('path/to/asset', import.meta.env))` API as described in the below documentation but have encountered numerous errors in doing so:

https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#generate-images-using-code-js-ts-tsx 

**Bonus points for extracting the assets to a separate package in the monorepo so we store them all in one place rather than the current duplication occurring in the marketing and web apps.**

### Rationale

Speeding up open graph image generation would be a big win and solve a number of headaches that we're currently facing.

### Proposed Solution

Making OG images great again

### Alternatives (optional)

N/A

### Additional Context

N/A

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by anjy7** [comment]
Hi @Mythie , I would like to take this one

**Comment by Mythie** [comment]
> Hi @Mythie , I would like to take this one

I'll assign you but will note that neo773 basically commented at the exact same time. Due to this unique situation ya'll can both work on it, if two solutions are presented I'll have to consider what to do at that time 😅

**Comment by rishi-raj-jain** [comment]
@Mythie Can I work on this?

**Comment by Mythie** [comment]
Let’s let these two work on it for now and check in on progress in a few days 😄

**Comment by rishi-raj-jain** [comment]
Awesome!
