### ISSUE TITLE
ERR! Missing script: "db-migrate:dev"

### ISSUE THREAD

**Issue by Dominion0815** [documenso/documenso#649]
### Issue Description

Documenso no longer starts, even a complete fresh installation throws this error:

```

docker-documenso-1  | npm ERR! Missing script: "db-migrate:dev"

...

docker-documenso-1  | @documenso/web:dev:  ⨯ Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

### Steps to Reproduce

- git clone repo
- docker compose up

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Thanks for catching this! Change was trivial so I've unfortunately already gone ahead with the PR #650

**Comment by Dominion0815** [comment]
@Mythie I must run this command interactively and now I got this error:

documenso-documenso-1  | @documenso/web:dev:  ⨯ NotFoundError: No User found

**Comment by dephraiim** [comment]
Looks like you're trying to create a unique index based on the migration but you have duplicate values that will break because it won't be unique anymore.

Try this before running your migration

```
npx prisma migrate reset --schema packages/prisma/schema.prisma
```

**Comment by Dominion0815** [comment]
oh he will empty the database...

```
root@68940f5416dc:/app# npx prisma migrate reset --schema packages/prisma/schema.prisma
Prisma schema loaded from packages/prisma/schema.prisma
Datasource "db": PostgreSQL database "documenso", schema "public" at "database:5432"

✔ Are you sure you want to reset your database? All data will be lost.
```

**Comment by catalinpit** [comment]
This seems solved! If there's an issue, feel free to open a new issue. Thanks!
