### ISSUE TITLE
feat: send grating or welcome mail to every signup

### ISSUE THREAD

**Issue by anikdhabal** [documenso/documenso#659]
### Feature Description

This would be great to send a welcome message to the user who has created their account.
eg:-
![Screenshot 2023-11-15 012244](https://github.com/documenso/documenso/assets/81948346/c4259622-6668-4779-ac8d-f4fc194da91d)

![Screenshot 2023-11-15 012311](https://github.com/documenso/documenso/assets/81948346/9b1ddf5c-eca7-4676-9630-9c58e4125681)

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by anikdhabal** [comment]
I want to work in this one.

**Comment by catalinpit** [comment]
Hey, thanks for opening this issue! It's a good suggestion, and it's already under way here - [https://github.com/documenso/documenso/pull/599/files#diff-c4d05dea665535ffdb18d0a34b5fd58abca4b623465a1aeb44af250bd09fa496](https://github.com/documenso/documenso/pull/599/files#diff-c4d05dea665535ffdb18d0a34b5fd58abca4b623465a1aeb44af250bd09fa496).

Will close this for now, but after that PR lands, if you think something can be improved, feel free to open a new PR! 🙏
