### ISSUE TITLE
feat: Title of your own choice

### ISSUE THREAD

**Issue by tanayvaswani** [documenso/documenso#660]
### Feature Description

- After uploading the document, title is set by default to the file name. 
- Adding a feature to change title while in draft mode. 

### Use Case

- This title will be shown at the Dashboard.
- Same title can be used while sending emails. 

### Proposed Solution

- It would be great if users can have the flexibility of putting a title of their own choice. 
- Can be done by allowing users to input title while in draft & disable the input once document is no longer a draft.

### Additional Context

- Once the document is changed from **Draft** to **Pending**, there will no longer be an option to change the title, to avoid confusions.  

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mythie** [comment]
Assigned 😁

**Comment by tanayvaswani** [comment]
Done #663 ✅
