### ISSUE TITLE
Custom Fields (with auto recognition)

### ISSUE THREAD

**Issue by daallgeier** [documenso/documenso#662]
### Feature Description

Currently there are only 4 core and important fields available. 
I'd love to have some more fields and field types for more complex signatures in standard contracts / contract templates.  

#### Cookie cutter contracts that only need a few more information points from the signers to ensure they are valid.  
Think: Address, Job Titles, Delivery Locations, etc. 

#### Forms from old school governments (or other bureaucracies) that need to fill a long list of things into their forms. 
Think: Tax forms, SEPA slips, etc. 

### Proposed Solution

The list below is kind of sorted by importance (the further down we go work arounds can be made using the custom text field)

- 1 more custom text field which I can use for people to fill in additional details such as addresses or whatever else custom they need to add;
- groups of radio buttons to allow a single selection of say a product
- groups of tick boxes to allow multi selection of say products
- a date field that's not tied to the signature date/time (for say a delivery date). 
- a number field that signers to add a number. 
- a drop down field to select a single option out of multiple (similar to radio button) 

Auto detection for fields in uploaded PDF's would be awesome too.  Similar to how Preview.app on Mac does it. 

### Alternatives (optional)

Currently using Preview.app to fill in data for PDF's and then upload it to documenso. 
Currently having to use a Google Docs template to create and add all final fields before uploading to documenso. 

### Additional Context

Being able to add ID's to each of these field types is something that can allow for standardised Metadata across contracts. 

Say I have a Name Field for my Customer.  I'd love to be able to give it a global standardised ID (`customer_name`) and thus ensure I can filter all contracts with that customer in the future (regardless of signer). 

Or a start/end dates.  Think of multi-year software contracts signed using documenso.  I'd love to be able to have the ability to filter all my contracts based on the `end_date` field information.  This would enable other implementations through an API which will allow me to create email reminders based on the contract signature.  So I don't have to also keep track of that in my CRM system.  

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by masoudtahmasebi** [comment]
Hi there, can I ask if this mentioned feature is available?

_Auto detection for fields in uploaded PDF's would be awesome too_
