### ISSUE TITLE
Resend Button should be disabled/invisible for Recipients

### ISSUE THREAD

**Issue by crediblebilal** [documenso/documenso#666]
### Improvement Description

When a recipient receives a document, under the `Action` menu list, the recipient also sees the `Resend` Button and the following resend pop-up after clicking the `Resend` button. This `Resend` button should be only functional for the document sender and it should be **invisible/disabled** for the recipients.

## Steps to reproduce:
- Send a document for signing.
- The recipient(s) receives the document.
- In the Documents table, Recipient(s) clicks on the three dots `...` under Actions column.
- A dropdown menu is shown with a Resend button along with other buttons

## Current UI for Recipients:

![image](https://github.com/documenso/documenso/assets/55330484/3a50a8c9-5222-47d0-bf6a-47fc81b1434f)

## Expected UI for Recipients: 
The Resend button should be disabled or hidden.

![image](https://github.com/documenso/documenso/assets/55330484/ffea5205-8e3f-439b-aa93-ac097eb3ff93)

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by crediblebilal** [comment]
If this is approved, I'm willing to work on it.

**Comment by Mythie** [comment]
Whoops, that shouldn't have slipped through! Thanks for the help 🙏
