### ISSUE TITLE
UI/UX Improvements on the Complete Sign Page

### ISSUE THREAD

**Issue by crediblebilal** [documenso/documenso#669]
### Improvement Description

When a Recipient successfully completes the sign, he is redirected to the `/sign/token/complete` page. ( SS attached below). The UI of this page is the same for both registered and non-registered users. 

## Current UI:

![Screenshot from 2023-11-21 11-35-43](https://github.com/documenso/documenso/assets/55330484/34618b54-354f-4ec6-b08f-e77dafa8c77d)

Although this UI is good looking, I think the message shown at the bottom **_Want to send slick signing links like this one? Check out Documenso._** should not be there for the **Registered/Logged in** users.

## Proposed Behaviour:

- **Registered/Logged in** users should see some button like **Return to homepage** and on clicking this should be redirected to `/documents` page.

### Rationale

The current behavior is fine for the Non-Registered users and Registered/Logged In users should see a different message or button there.

### Proposed Solution

- **Registered/Logged in** users should see some button like **Return to homepage** or some different message and on clicking this should be redirected to `/documents` page.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by crediblebilal** [comment]
If this is approved, I can work on this improvement.

**Comment by catalinpit** [comment]
Sounds good, in my opinion. Let's see what other team members say as well.
