### ISSUE TITLE
Unable to click or DnD on 'Add a document'

### ISSUE THREAD

**Issue by david-loe** [documenso/documenso#673]
### Issue Description

I'm not able to click or Drag&Drop on 'Add a document' on the `/documents` page.

### Steps to Reproduce

Start gitpod workplace, sign up and try..

### Screenshots (optional)

![grafik](https://github.com/documenso/documenso/assets/56305409/9df1b71b-a285-4dca-b868-2bb9a04ae970)

### Browser [e.g., Chrome, Firefox]

Tested on Firefox and Edge

### Version [e.g., 2.0.1]

main (9444e0cc67c67e3759d52cf91135aabee0c716d9)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey again, appreciate you catching these bugs! I’ve made some fixes and can confirm that everything is now working well on Gitpod 💪🏻

**Comment by david-loe** [comment]
Thanks for your fast Reactions! It works now :)
