### ISSUE TITLE
Can't upload files on Local Instance : Error: Text content does not match server-rendered HTML.

### ISSUE THREAD

**Issue by Thatsgaurav** [documenso/documenso#675]
### Issue Description

Unhandled Runtime Error
Error: Text content does not match server-rendered HTML.

Warning: Text content did not match. Server: "Ctrl" Client: "⌘"

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
div
div
button
_c
../../packages/ui/primitives/button.tsx (53:11)
div
DesktopNav
layout/desktop-nav.tsx (20:11)
div
header
Header
layout/header.tsx (23:11)
LimitsProvider
../../packages/ee/server-only/limits/provider/client.tsx (30:11)
SessionProvider
../../node_modules/next-auth/react/index.js (455:24)
NextAuthProvider
./src/providers/next-auth.tsx (14:11)
Call Stack
checkForUnmatchedText
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (32511:0)
didNotMatchHydratedTextInstance
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (35914:0)
prepareToHydrateHostTextInstance
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (7250:0)
completeWork
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (19638:0)
completeUnitOfWork
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25699:0)
performUnitOfWork
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25504:0)
workLoopConcurrent
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25479:0)
renderRootConcurrent
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (25435:0)
performConcurrentWorkOnRoot
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (24288:0)
workLoop
../../node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (261:0)
flushWork
../../node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (230:0)
MessagePort.performWorkUntilDeadline
../../node_modules/next/dist/compiled/scheduler/cjs/scheduler.development.js (534:0)

### Steps to Reproduce

Follow the steps given in Readme file to install local instance 

Run app on local system  http://localhost:3000/documents

### Expected Behavior

It should be able to upload files 

### Current Behavior

Not able to upload files also getting 

```
curl 'http://localhost:3000/api/limits' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: next-auth.csrf-token=2410113c75216b71189160bef609910002adfdb884e9d34e88d7ad7b7ce967b2%7Ce52d477e241eb7d6d0804c05ef17bd2885a007343cf2eff54c3525a72067a9df; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fdocuments; next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..lwBfbHpVpAJCkPXT.gDFEZh8rpD2ykqH2XsCtEQHkNAxa43oUEi94s7h39H88IBMNQ5m7X9BVjdTbxy4_6mK4U5wLcJHnJ3ZLjCr6bg9HbaTzcZJXQQF6gnZzKVIeWnBte_R7uhIBfZ0tMaCBCyzx_iHj_W--aOtz9g8vAuhw28J7q0zTPFqnW5MF6xjOGW3tNlL0iPkEubTKog8U_wcfWKOCapT_7itshiLpwjaZKEYsmb8Vpzv1NozdguOPjT4.G_y9rJjrSWRnmNWcnmpuuQ' \
  -H 'If-None-Match: "17nghgco31t2n"' \
  -H 'Referer: http://localhost:3000/documents' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed

```

```
{
    "quota": {
        "documents": null,
        "recipients": null
    },
    "remaining": {
        "documents": null,
        "recipients": null
    }
}

```

### Operating System [e.g., Windows 10]

Mac M1

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

latest master branch

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Thanks for catching this, I’ve since sent a fix to main and it should all be working now!

**Comment by Thatsgaurav** [comment]
Thanks that is resolved now !
