### ISSUE TITLE
Error: Unknown font format: Unhandled Runtime Error

### ISSUE THREAD

**Issue by Thatsgaurav** [documenso/documenso#677]
### Issue Description

Call Stack
Object.create
../node_modules/@pdf-lib/fontkit/dist/fontkit.es.js (17839:10)
create
../node_modules/pdf-lib/es/core/embedders/CustomFontEmbedder.js (37:57)
call
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (100:22)
step
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (81:52)
next
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (74:70)
new Promise
<anonymous>
__awaiter
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (70:11)
CustomFontEmbedder.for
../node_modules/pdf-lib/es/core/embedders/CustomFontEmbedder.js (33:25)
fontkit
../node_modules/pdf-lib/es/api/PDFDocument.js (881:72)
call
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (100:22)
step
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (81:52)
next
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (74:70)
new Promise
<anonymous>
__awaiter
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (70:11)
PDFDocument.embedFont
../node_modules/pdf-lib/es/api/PDFDocument.js (861:25)

### Steps to Reproduce

Add A document to sign on local deployment 
Add a recipient 
while the last recipient signs the document following error is raised 

Call Stack
Object.create
../node_modules/@pdf-lib/fontkit/dist/fontkit.es.js (17839:10)
create
../node_modules/pdf-lib/es/core/embedders/CustomFontEmbedder.js (37:57)
call
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (100:22)
step
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (81:52)
next
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (74:70)
new Promise
<anonymous>
__awaiter
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (70:11)
CustomFontEmbedder.for
../node_modules/pdf-lib/es/core/embedders/CustomFontEmbedder.js (33:25)
fontkit
../node_modules/pdf-lib/es/api/PDFDocument.js (881:72)
call
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (100:22)
step
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (81:52)
next
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (74:70)
new Promise
<anonymous>
__awaiter
../node_modules/pdf-lib/node_modules/tslib/tslib.es6.js (70:11)
PDFDocument.embedFont
../node_modules/pdf-lib/es/api/PDFDocument.js (861:25)

### Expected Behavior

After last sign a signed document should be generated. 

### Current Behavior

No signed document is generated. 

### Operating System [e.g., Windows 10]

Mac M1

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

latest master branch

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by david-loe** [comment]
fixed by 823034911487d5785473ca8aef9bfe46e271be88

**Comment by catalinpit** [comment]
Thanks @david-loe for the comment!
