### ISSUE TITLE
Delete Documents

### ISSUE THREAD

**Issue by david-loe** [documenso/documenso#681]
### Feature Description

As a User I want to be able to delete signed documents in order to save some disk space and keep my dashboard clean.

### Proposed Solution

Enable the delete button in UI and build backend solution.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by crediblebilal** [comment]
If this is approved, I can work on it.

**Comment by VishalMCF** [comment]
@catalinpit  Can I work on this?

**Comment by david-loe** [comment]
Done by #712
