### ISSUE TITLE
User should not be able to add his own email in the list of signers

### ISSUE THREAD

**Issue by bilalqv** [documenso/documenso#685]
### Improvement Description

In the **Add Singers** form, the user should not be able to add his own email in the Signers Form.

### Current Behaviour:

1. User uploads the document on the `/documents` page.
2. After uploading, user is redirected to `/documents/id` page, where **Add Signers** form is displayed.
3. User can add his own **email id** in the email field.
4. After adding the other fields, user clicks the **Send** button.
5. User receives an email **_{Users own name}_ has invited you to sign...**
6. User receives his own document in the `/documents` page with the **Sign** button.
7. User can **Sign** his own sent document.

### Rationale

User should not be able to add his own email in the signers list. There should be a separate flow which user can use if he wants to Sign his own documents.

### Proposed Solution

If user gives his own email, a popup/toast should be displayed like _**Error: You can not add yourself as signer**_

### Alternatives (optional)

Create a separate flow where user can sign his own documents if needed.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by crediblebilal** [comment]
If this is approved, I can work on it.

**Comment by Mythie** [comment]
Hey there, I don’t really see why this has to be a separate flow. It seems cheaper and more convenient to keep it like this.

An improvement would be to redirect the user to sign the document upon sending it to the recipients. This should be opt-in though since I’m sure there are cases where the user wants to sign last as well.

**Comment by crediblebilal** [comment]
Why I am saying a separate flow is that, If let's say I need to sign a document, I should be able to upload and sign the document without entering my own details like email and signature again, or these fields should be prefilled with the ability to change the signature.

**Comment by surajgjadhav** [comment]
Also I observed one thing, if user self signed the Doc, then it showing incorrect count in completed tab:
![image](https://github.com/documenso/documenso/assets/31582237/41f7b5a3-3fb3-4169-a2aa-a3621ce11063)

Here I Self Signed one Doc, but instead of showing 1 in completed tab it is showing 2

**Comment by surajgjadhav** [comment]
We can update hasSignedCount Query like this:
![image](https://github.com/documenso/documenso/assets/31582237/a711ae81-ead6-43bf-a90c-ceae032e7023)

basically, from this:
![image](https://github.com/documenso/documenso/assets/31582237/23833802-4dea-4f09-8391-9e34a60b6bf9)
ownerCounts & hasSignedCount is encountering same doc as our hasSignedCount also includes owner doc due to existing condition.

Please do let me know if you want it to update and it seems to be right logic
Thanks :)
Happy to work 😄

**Comment by crediblebilal** [comment]
> We can update hasSignedCount Query like this: ![image](https://private-user-images.githubusercontent.com/31582237/286671843-a711ae81-ead6-43bf-a90c-ceae032e7023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzg3NTIsIm5iZiI6MTcwMTI3ODQ1MiwicGF0aCI6Ii8zMTU4MjIzNy8yODY2NzE4NDMtYTcxMWFlODEtZWFkNi00M2JmLWE5MGMtY2VhZTAzMmU3MDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZjdlYTgyOTk0YmNmZDgyZDI2M2U4ZDBmNDg5ZjRhNzAzMjhiM2ViNTczMTJkMTJmZDc5YTdjZWZiZjlkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tPpaDyWEpBdSgYNla7U46jHQLwHmH1EFpn4wicYAf-o)
> 
> basically, from this: ![image](https://private-user-images.githubusercontent.com/31582237/286671989-23833802-4dea-4f09-8391-9e34a60b6bf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzg3NTIsIm5iZiI6MTcwMTI3ODQ1MiwicGF0aCI6Ii8zMTU4MjIzNy8yODY2NzE5ODktMjM4MzM4MDItNGRlYS00ZjA5LTgzOTEtOWUzNGE2MGI2YmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZWVlNDc5YzhkODI1ZDQ4NTA0YjVmMzYzNzQ4MWQ5ZmRmYjU1NWZmMjJmOGNhMWQ4MzhiMjhjODY5YTE3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X3DakdRxDRqCpa6nmSDDuCyPtTW01Pj_GohuZaHe3Yc) ownerCounts & hasSignedCount is encountering same doc as our hasSignedCount also includes owner doc due to existing condition. and, we are showing summation of Signed OwnerCounts and count from hasSignedCount. which is showing us double count
> 
> Please do let me know if you want it to update and it seems to be right logic Thanks :) Happy to work 😄

Currently, Completed shows the total count of documents that are signed by the user himself + count of documents of current user that are signed by others. If that is the case, then Completed = 2 in above case is correct because your one document is signed by someone(in this case by you yourself) and you have signed one document of someone(which in this case is your own)! 😄

**Comment by surajgjadhav** [comment]
> > We can update hasSignedCount Query like this: ![image](https://private-user-images.githubusercontent.com/31582237/286671843-a711ae81-ead6-43bf-a90c-ceae032e7023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzg3NTIsIm5iZiI6MTcwMTI3ODQ1MiwicGF0aCI6Ii8zMTU4MjIzNy8yODY2NzE4NDMtYTcxMWFlODEtZWFkNi00M2JmLWE5MGMtY2VhZTAzMmU3MDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZjdlYTgyOTk0YmNmZDgyZDI2M2U4ZDBmNDg5ZjRhNzAzMjhiM2ViNTczMTJkMTJmZDc5YTdjZWZiZjlkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tPpaDyWEpBdSgYNla7U46jHQLwHmH1EFpn4wicYAf-o)
> > 
> > basically, from this: ![image](https://private-user-images.githubusercontent.com/31582237/286671989-23833802-4dea-4f09-8391-9e34a60b6bf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNzg3NTIsIm5iZiI6MTcwMTI3ODQ1MiwicGF0aCI6Ii8zMTU4MjIzNy8yODY2NzE5ODktMjM4MzM4MDItNGRlYS00ZjA5LTgzOTEtOWUzNGE2MGI2YmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDE3MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZWVlNDc5YzhkODI1ZDQ4NTA0YjVmMzYzNzQ4MWQ5ZmRmYjU1NWZmMjJmOGNhMWQ4MzhiMjhjODY5YTE3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X3DakdRxDRqCpa6nmSDDuCyPtTW01Pj_GohuZaHe3Yc) ownerCounts & hasSignedCount is encountering same doc as our hasSignedCount also includes owner doc due to existing condition. and, we are showing summation of Signed OwnerCounts and count from hasSignedCount. which is showing us double count
> > 
> > Please do let me know if you want it to update and it seems to be right logic Thanks :) Happy to work 😄
> 
> Currently, Completed shows the total count of documents that are signed by the user himself + count of documents of current user that are signed by others. If that is the case, then Completed = 2 in above case is correct because your one document is signed by someone(in this case by you yourself) and you have signed one document of someone(which in this case is your own)! 😄
> 
> 
> 

This seems to be right from Dev. Perspective but if we think from User's Perspective, User will see Completed (2) but in the doc list there is only 1 doc available, which is self signed. That might confuse the User about where is the second document 😅
