### ISSUE TITLE
Failed when run `npm run dx` with NodeJS 18.18.0 and NPM 8.19.2

### ISSUE THREAD

**Issue by ducle-infotrack** [documenso/documenso#687]
### Issue Description

Hi mates, I got this issue when try to install documenso. Can you guys give it a try?

- OS: Window 10
- Node: 18.18.2
- NPM: 8.19.2

```bash
 npm run dx

> dx
> npm i && npm run dx:up && npm run prisma:migrate-dev

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @documenso/marketing@0.1.0
npm ERR! Found: next@14.0.0
npm ERR! node_modules/next
npm ERR!   next@"14.0.0" from @documenso/marketing@0.1.0
npm ERR!   apps/marketing
npm ERR!     @documenso/marketing@0.1.0
npm ERR!     node_modules/@documenso/marketing
npm ERR!       workspace apps\marketing from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12.2.5 || ^13" from next-auth@4.24.3
npm ERR! node_modules/next-auth
npm ERR!   next-auth@"4.24.3" from @documenso/marketing@0.1.0
npm ERR!   apps/marketing
npm ERR!     @documenso/marketing@0.1.0
npm ERR!     node_modules/@documenso/marketing
npm ERR!       workspace apps\marketing from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\infotrack.vn\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\infotrack.vn\AppData\Local\npm-cache\_logs\2023-11-26T16_44_34_522Z-debug-0.log
```

### Steps to Reproduce

run `npm run dx`

### Expected Behavior

To be end up successfully

### Current Behavior

To be end up in below error

### Operating System [e.g., Windows 10]

 Windows 10

### Browser [e.g., Chrome, Firefox]

Bash

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dephraiim** [comment]
Can you run this and try again?
```
npm run reset:hard
```

**Comment by Mythie** [comment]
Gday, this is due to our next 14 upgrade. I’ll get it sorted this morning! 🙌🏻
