### ISSUE TITLE
Ability to add text fields

### ISSUE THREAD

**Issue by meilechwieder** [documenso/documenso#688]
### Feature Description

Ability for requestor to add any text filed on any place of the document for the signer to fill out. 

There is already the "Name" input. But we want to be able to add any label, not just "Name".

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by crediblebilal** [comment]
If this is approved, I want to work on it.

**Comment by Anuragt1104** [comment]
Hey, I can work on this issue. Can you assign me?

**Comment by anikdhabal** [comment]
> Hey, I can work on this issue. Can you assign me?

Hey there, I've already started working on this issue. I previously asked to assign me this issue. I delete that message.

**Comment by Anuragt1104** [comment]
okay no problem

**Comment by anikdhabal** [comment]
> okay no problem

Thank mate

**Comment by Varsani2520** [comment]
i can work on this issue? can you assign me?

**Comment by anikdhabal** [comment]
> i can work on this issue? can you assign me?

Hey @Varsani2520 ,I've already made a Pr.

**Comment by ephraimduncan** [comment]
This is currently available in the latest release. 

PR Here: https://github.com/documenso/documenso/pull/945
