### ISSUE TITLE
bug : Can add signature space for empty recipients

### ISSUE THREAD

**Issue by SauravL3010** [documenso/documenso#69]
Preview:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/65268462/231239420-0ade038d-40c1-4a49-bbd3-3c3b45cdc936.png">

Steps to reproduce the bug:
 - add a empty recipient
 - got to edit documents
 - see the list of recipients

**Comment by SauravL3010** [comment]
p.s this doesn't effect any functionality, don't know if this was intended, just wanted to point it out. can close if not required.

**Comment by ElTimuro** [comment]
No, not by design. The "draft recipient" wasn't fully thought through, as elaborated here: https://github.com/documenso/documenso/pull/70
