### ISSUE TITLE
[DOC-372] Allow for the deletion of any document

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#696]
### **Description**

Expand deletion functionality to include documents in PENDING and COMPLETED states, alongside existing draft deletion.

### **Improvement Description**

* Allow deletion of documents in any state (DRAFT, PENDING, COMPLETED).
* Implement varying confirmation requirements based on the document state.
* Soft delete documents using a `deletedAt` column.

### **Rationale**

We've had a couple of users complain that they are unable to delete an erroneous document once it's left the draft state, this has hindered their ability to use Documenso and doesn't match that of other providers. To improve user satisfaction and match our competition, we should improve our current handling of deletions. It also hinders the user from handling their data as they please.

### **Proposed Solution**

* Maintain simple deletion for drafts.
* Require explicit confirmation (e.g., typing "delete me") for deleting PENDING or COMPLETED documents.
* Email recipients for documents that are PENDING so they are aware that it has been canceled.
* Implement soft deletion for documents, retaining access in the inbox.

### **Alternatives**

* Introduce a temporary holding area for deleted documents before permanent deletion. (Recycle Bin)
* User-customizable settings for deletion confirmations.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-372](https://linear.app/documenso/issue/DOC-372/allow-for-the-deletion-of-any-document)</sub>

**Comment by ElTimuro** [comment]
Updating to reflect our new template alongside some caveats

**Comment by crediblebilal** [comment]
Is this open for contributions? I wanted to pick it up.

**Comment by crediblebilal** [comment]
Started working on this one

**Comment by Mythie** [comment]
For OSSHack participants we won’t be assigning or following our usual guidelines, please start work if you want to do the challenge.

The first *good* solution (read: to acceptable quality and conformance) wins!
