### ISSUE TITLE
dark mode/ light mode positioning

### ISSUE THREAD

**Issue by prashikk** [documenso/documenso#699]
@### Improvement Description

at the Home page the dark mode / light mode toggle button could be place on the top in the navbar section. the navbar is always upfront so it would be easy for user to toggle the mode anytime rather than to scroll all the way down and toggle it.

### Rationale

after scrolling all the way down the user could notice that the website has this feature. 

### Proposed Solution

place the dark / light mode toggle button in navbar.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mutai-Gilbert** [comment]
@crediblebilal I hope they assign that to you.

**Comment by Nisarg-Sha** [comment]
I am new to open source. I would like to take this & work on this can you please assign it to me.

**Comment by catalinpit** [comment]
Thanks for suggesting this, @prashikk! Documenso uses `prefers-color-scheme`, so I'd say having the switcher at the bottom is fine. We wouldn't move with this issue further, unfortunately. Thanks for understanding!
