### ISSUE TITLE
[OSSHACK] Add document search to the command menu

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#702]
## Improvement Description

Add a search feature to the command menu that allows users to search for documents by title or recipient email. The search feature should be accessible from any page on the platform and should return a list of documents matching the search query. 

The search results should be limited to 3-5 documents to maintain interface clarity. 

The search feature should include both sent and received documents.

## Rationale

As we were a new platform search was not an issue since most users had a small number of documents. However, as the number of documents increases, users are required to paginate through tables to find specific documents. This is inefficient and time-consuming. A search feature would allow users to quickly find the documents they are looking for.

## Proposed Solution

- Add a search feature in the command bar.
- Enable search by document title or recipient email.
- Limit search results to 3-5 to maintain interface clarity.
- Include both sent and received documents in search results.

## Alternatives

- A separate dedicated search page or section as an alternative to integrating with the command bar.
- Advanced search filters (like date, document type, etc.) for more specific searches. (We will explore this later)

**Comment by itzabhinavarya** [comment]
@Mythie Assign this to me.

**Comment by Mythie** [comment]
For OSSHack participants we won’t be assigning or following our usual guidelines, please start work if you want to do the challenge.

The first *good* solution (read: to acceptable quality and conformance) wins!

**Comment by kritarth2121** [comment]
Working on this
