### ISSUE TITLE
[OSSHACK] Recipient Roles

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#705]
## Improvement Description

Add the ability to specify a role for a recipient. This will include CC (Carbon Copy), Signer, Viewer, and Approver.

- Signers will be able to sign the document as per usual.
- Approvers may be able to sign the document but will also be able to approve the document without signing it.
- Viewers will be able to view the document but will not be able to sign or approve it.
- CCs will only receive a copy of the completed document.

## Rationale

Not all recipients of a given document need to sign it. Some recipients may only need to view the document, others may need to approve it, and others may need to sign it. Support for these roles will allow for more flexibility in the types of documents that can be created and sent.

## Proposed Solution

- Add a `role` enum to the `Recipient` model that contains the role types.
- Update the add signers step to allow for the selection of a role for each recipient defaulting to `Signer`.
- Update our signing flow to allow for the different roles.
- Update the recipient popover to display the role of each recipient in addition to their email.
- Update our complete document flow to allow for the different roles and email sending requirements.

## Alternatives

N/A

## Additional Context
- The design for this improvement can be found on our Figma: https://www.figma.com/file/mKYFxgmekwxXsoXCP9dXXx/Documenso-Design-System?type=design&node-id=4%3A336&mode=design&t=RCNR7fdt1cxJEReM-1

**Comment by e-roy** [comment]
@Mythie I'm interested in starting on this.
