### ISSUE TITLE
[OSSHACK] Create a Stepper component

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#708]
## Improvement Description

- Create a stepper component that will enhance the user experience and reduce the complexity of current multistep forms.
- The component should use Radix UI and/or Shadcn to the best of its ability.

## Rationale

- Current multistep forms are complex and potentially inefficient.
- A stepper component will standardize the process, leading to easier maintenance and better user experience.
- Utilizing Radix UI and Shadcn ensures consistency with existing design and functionality paradigms.

## Proposed Solution

- Develop a `Stepper` component with the following structure:

```html
<Stepper onComplete?={callback}>
  <Step>
    <Component />
    <!-- 
      Where in the component I could use `useStep` hook to get the current step and the `next` function to go to the next step.
      Additionally I would need a previous method and an `isFirst` and `isLast` boolean.
    -->
  </Step>
  ...
</Stepper>
```

- The `useStep` hook within each `Step` component should provide:
  - The current step information.
  - `next` and `previous` methods to navigate between steps.
  - `isFirst` and `isLast` booleans to identify the beginning and end of the steps.

## Alternatives

- Explore third-party stepper components that could be adapted to our needs. This hasn't been promising so far.
- Refactor existing multistep forms without a stepper component, which could be more time-consuming and less efficient.

## Additional Context

- The new stepper component must be fully compatible with our current stack.
- Documentation and examples should be provided for easy integration into existing and future forms.

## Things to consider building on top of
- https://headless-stepper.netlify.app/
- https://github.com/devrnt/react-use-wizard

**Comment by Mythie** [comment]
For OSSHack participants we won’t be assigning or following our usual guidelines, please start work if you want to do the challenge.

The first *good* solution (read: to acceptable quality and conformance) wins!

**Comment by crediblebilal** [comment]
I've already surrendered here! 😄

**Comment by G3root** [comment]
Haha, the only thing I'm good at is centering divs. Other than that, I'm as dumb as a piece of wood, so I'm no competition. 😅

**Comment by rahulgpt** [comment]
https://x.com/lxunos/status/1730513478937686050?s=20

> Haha, the only thing I'm good at is centering divs. Other than that, I'm as dumb as a piece of wood, so I'm no competition. 😅

https://x.com/lxunos/status/1730513478937686050?s=20

**Comment by rahulgpt** [comment]
> Haha, the only thing I'm good at is centering divs. Other than that, I'm as dumb as a piece of wood, so I'm no competition. 😅

https://x.com/lxunos/status/1730513478937686050?s=20
