### ISSUE TITLE
[DOC-376] No jump to sign field

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#710]
![image.png](https://uploads.linear.app/884f43d5-69da-459d-bc6b-864f16914e0f/cfb8b919-9780-401d-a927-09aec7ab57c9/91e90dc1-1c4e-4447-b8e1-db4590f2424b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg4NGY0M2Q1LTY5ZGEtNDU5ZC1iYzZiLTg2NGYxNjkxNGUwZi9jZmI4YjkxOS05NzgwLTQwMWQtYTkyNy0wOWFlYzdhYjU3YzkvOTFlOTBkYzEtMWM0ZS00NDQ3LWI4ZTEtZGI0NTkwZjI0MjRiIiwiaWF0IjoxNzAxNDcwMTQxLCJleHAiOjE3MDE1NTY1NDF9.Lo77tPPabVngXJHO3abGFDlGtUYsx5u_GzUUTOtxj88)

* When the user already has a signature in their account, the complete button is disabled, forcing them to scroll through the doc and click each field manually.
* When clicked on complete, the auto-scroll to open field should also be triggered.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-376](https://linear.app/documenso/issue/DOC-376/no-jump-to-sign-field)</sub>

**Comment by ksushant6566** [comment]
Hey @ElTimuro @Mythie , if I understand this correctly if I user has a signature in their (in other words is logged in, right?) then the complete button shouldn't be disabled and when clicked should trigger scroll to the first field in the document.

attaching a loom: https://www.loom.com/share/25d099d8557e4b1688b0f139bb75f1ff?sid=cc9dac8e-3a10-446a-8a8f-58946e071fef

**Comment by catalinpit** [comment]
Hey, just to make sure I understand this. When the user has a signature **AND** clicks the first signature field, should the app take the user to the next field automatically **OR** should the app complete all the signature fields?

**Comment by ElTimuro** [comment]
Complete should be clickable but if not all fields are signed, jump to the next open field. click to sign. its not legal to autofill all sadly

**Comment by ElTimuro** [comment]
signing the big field could also trigger going to the next open one, if that can work smoothly.
the open field trigger a dialog, if the big field is not signed

**Comment by ksushant6566** [comment]
> Complete should be clickable but if not all fields are signed, jump to the next open field. click to sign. its not legal to autofill all sadly

Hey guys, this behaviour was achieved in PR #729 but I see that PR is now outdated now. Would you like me to update it?

**Comment by ksushant6566** [comment]
> signing the big field could also trigger going to the next open one, if that can work smoothly. the open field trigger a dialog, if the big field is not signed

not sure what is meant by big field here?

**Comment by ElTimuro** [comment]
marked as done on GH
