### ISSUE TITLE
Failed when using the Developer Quickstart guide

### ISSUE THREAD

**Issue by myugan** [documenso/documenso#731]
### Issue Description

The __No User Found__ error appeared when setting up a new environment by following the steps of the Developer Quickstart guide.

### Steps to Reproduce

Followed the steps mentioned here https://github.com/documenso/documenso#developer-quickstart and just moved .env.example to .env without changing any values.

### Expected Behavior

It should be running successfully.

### Current Behavior

After following the steps, this is the last output that appeared.

```
@documenso/marketing:dev: cache bypass, force executing c5ea7e47220f4f06
@documenso/web:dev: cache bypass, force executing 80bef2cbfaa8b59f
@documenso/web:dev: 
@documenso/web:dev: > @documenso/web@0.1.0 dev
@documenso/web:dev: > next dev -p 3000
@documenso/web:dev: 
@documenso/marketing:dev: 
@documenso/marketing:dev: > @documenso/marketing@0.1.0 dev
@documenso/marketing:dev: > next dev -p 3001
@documenso/marketing:dev: 
@documenso/web:dev:    ▲ Next.js 14.0.0
@documenso/web:dev:    - Local:        http://localhost:3000
@documenso/web:dev: 
@documenso/marketing:dev:    ▲ Next.js 14.0.0
@documenso/marketing:dev:    - Local:        http://localhost:3001
@documenso/marketing:dev: 
@documenso/web:dev: npm ERR! code ENOWORKSPACES
@documenso/web:dev: npm ERR! This command does not support workspaces.
@documenso/web:dev: 
@documenso/web:dev: npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-12-06T04_39_56_377Z-debug-0.log
@documenso/marketing:dev: npm ERR! code ENOWORKSPACES
@documenso/marketing:dev: npm ERR! This command does not support workspaces.
@documenso/marketing:dev: 
@documenso/marketing:dev: npm ERR! A complete log of this run can be found in: /Users/user/.npm/_logs/2023-12-06T04_39_56_377Z-debug-0.log
@documenso/web:dev:  ✓ Ready in 2.8s
@documenso/marketing:dev: Contentlayer config change detected. Updating type definitions and data...
@documenso/marketing:dev: Generated 15 documents in .contentlayer
@documenso/marketing:dev:  ✓ Ready in 3.3s
@documenso/web:dev:  ✓ Compiled /src/middleware in 295ms (160 modules)
@documenso/web:dev: (node:88382) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
@documenso/web:dev: (Use `node --trace-deprecation ...` to show where the warning was created)
@documenso/web:dev:  ○ Compiling /(dashboard)/documents/page ...
@documenso/web:dev: 
@documenso/web:dev: 
@documenso/web:dev:  ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
@documenso/web:dev:  ⨯ NotFoundError: No User found
@documenso/web:dev:     at async getServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:40:18)
@documenso/web:dev:     at async getRequiredServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:51:31)
@documenso/web:dev:     at async AuthenticatedDashboardLayout (layout.tsx:34:22)
@documenso/web:dev:  ⨯ NotFoundError: No User found
@documenso/web:dev:     at async getServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:40:18)
@documenso/web:dev:     at async getRequiredServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:51:31)
@documenso/web:dev:     at async AuthenticatedDashboardLayout (layout.tsx:34:22)
@documenso/web:dev: digest: "2903593014"
@documenso/web:dev:  ⨯ NotFoundError: No User found
@documenso/web:dev:     at async getServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:40:18)
@documenso/web:dev:     at async NotFound (./src/app/not-found.tsx:18:25)
@documenso/web:dev:  ⨯ NotFoundError: No User found
@documenso/web:dev:     at async getServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:40:18)
@documenso/web:dev:     at async NotFound (./src/app/not-found.tsx:18:25)
@documenso/web:dev:  ⨯ NotFoundError: No User found
@documenso/web:dev:     at async getServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:40:18)
@documenso/web:dev:     at async getRequiredServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:51:31)
@documenso/web:dev:     at async AuthenticatedDashboardLayout (layout.tsx:34:22)
@documenso/web:dev:  ⨯ NotFoundError: No User found
@documenso/web:dev:     at async getServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:40:18)
@documenso/web:dev:     at async getRequiredServerComponentSession (../../packages/lib/next-auth/get-server-session.ts:51:31)
@documenso/web:dev:     at async AuthenticatedDashboardLayout (layout.tsx:34:22)
@documenso/web:dev: digest: "2903593014"
```

### Operating System [e.g., Windows 10]

macOS Ventura 13.5.2

### Browser [e.g., Chrome, Firefox]

Chrome

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [x] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey there, could you confirm your `node` and `npm` versions?

In the meantime could you also clear the cookies for localhost within your browser and run `npm run reset:hard && npm run d` 😄

**Comment by myugan** [comment]
Hi @Mythie, thank you for responding so quickly. Here is the version that I'm using.

node v21.3.0
npm 10.2.4

Tried your suggestion but doesn't work either

**Comment by Mythie** [comment]
No worries! We haven't actually done a lot of testing on Node 21 so I'd suggest using whatever tooling you may using node versions and switching down to Node 18.

If you're not currently using any tooling for managing node versions I recommend nvm:

https://github.com/nvm-sh/nvm

**Comment by myugan** [comment]
Okay, perhaps you could add some minimum requirements for a specific version to run the documenso smoothly? It might help other users to use the proper version in the future.

**Comment by Mythie** [comment]
Agreed! We will work on our docs and also work on what might be blocking usage with node 20-21 🙌🏻

**Comment by myugan** [comment]
Thanks, @Mythie! It's working fine on my local machine now. However, I am facing another issue on the server with the docker compose setup inside the **docker** directory. Is it intentionally not working as mentioned that the docker setup is still a work in progress? Therefore, should I expect this setup to not run properly on the server unlike the local setup?

**Comment by myugan** [comment]
Here is the error message when trying to Sign Up when using compose stack
<img width="497" alt="image" src="https://github.com/documenso/documenso/assets/20453528/4de0a3ac-8dcd-49f6-bdc8-403574740365">

**Comment by Mythie** [comment]
Hey there! Which compose file were you using sorry? We have a few improvements to do on the docker side of deploying this 😬

**Comment by myugan** [comment]
I'm using this compose file https://github.com/documenso/documenso/blob/main/docker/compose.yml. However, I encountered an issue which was resolved after figuring out that one environment variable, `NEXT_PRIVATE_DIRECT_DATABASE_URL`, had not been defined. This was causing the database migration to fail, resulting in the following error.

![image](https://github.com/documenso/documenso/assets/20453528/52085a7d-bc74-4c49-8e62-2246edf4dbfa)

**Comment by myugan** [comment]
This issue has been resolved according to my previous comment and suggestions. I hope the clear documentation will be available in the next release.
