### ISSUE TITLE
Ability to disable new signups

### ISSUE THREAD

**Issue by notnavindu** [documenso/documenso#732]
### Improvement Description

I noticed that in the newest version of Documenso it is not possible to disable new signups. However, I remember this feature being available in an older version of Documenso using the `NEXT_PUBLIC_ALLOW_SIGNUP` env variable. 

### Rationale

Having the ability to restrict Sign Ups can be beneficial if you are self hosting Documenso for private organizational usage and prevent outsiders from making accounts

### Proposed Solution

Allowing users to set `NEXT_PUBLIC_ALLOW_SIGNUP` to false to prevent new user signup 

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by catalinpit** [comment]
Hey, @notnavindu! Thanks for opening the issue!

We were planning on doing this. If you want to work this, let me know. 😃

**Comment by notnavindu** [comment]
Hey @catalinpit I would love to! Please assign me :)

**Comment by catalinpit** [comment]
> Hey @catalinpit I would love to! Please assign me :)

Done. Thank you! 👍
