### ISSUE TITLE
Ability to add and manage comments in documents

### ISSUE THREAD

**Issue by ksushant6566** [documenso/documenso#737]
### Feature Description

Currently, users cannot add comments inside documents; hence, any negotiation or discussion has to move off the platform.
This could be solved by adding the ability to add/manage comments like other platforms such as Google Docs and DocuSign. 

### Use Case

Whenever there is confusion/query/change-requests in a document, users would want the ability to do so on the platform itself instead of having to do these separately somewhere else.

### Proposed Solution

Brief: 

* Should be an opt-in feature (document owners can choose to allow comments from recipients).
* All recipients should be able to add comments. (If the owner has opted in)
* Comments by default should only be visible to the author and the owner of the document. 
* The owner can choose to make comments public.
* Author and owner can reply to a comment. (replies to be shown as threads)
* Everyone can reply to a public comment.
* Author and owner can resolve a comment.

### Alternatives (optional)

Maybe this can be done over emails? But still on-platform visibility will still not be possible.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by catalinpit** [comment]
Hey @ksushant6566, thanks for the suggestion! Personally, I like it and I think it makes a lot of sense.

How would you see this working? Having comments under the pdf, like on an article for example, or having comments like Google Docs?

**Comment by Dun-sin** [comment]
> Hey @ksushant6566, thanks for the suggestion! Personally, I like it and I think it makes a lot of sense.
> 
> How would you see this working? Having comments under the pdf, like on an article for example, or having comments like Google Docs?

i think the way google docs works is a good option, because it helps to give context

**Comment by ksushant6566** [comment]
Definitely something like google docs. Users will be able to pinpoint their discussions.

**Comment by ksushant6566** [comment]
I'll be open to building it.

**Comment by catalinpit** [comment]
> I'll be open to building it.

Appreciate the willingness to work on this, but we need a bit of time to think this through since it's quite complex. We need to define the scope of the feature + think about things like revisioning.

**Comment by ksushant6566** [comment]
> > I'll be open to building it.
> 
> Appreciate the willingness to work on this, but we need a bit of time to think this through since it's quite complex. We need to define the scope of the feature + think about things like revisioning.

Understood, lmk if I can help

**Comment by Nisarg-Sha** [comment]
I am also intrested to build this feature if it's get approved I definitely do it.
