### ISSUE TITLE
[🪲 Bug]: Updating profile info without changing anything causes unnecessary database calls

### ISSUE THREAD

**Issue by ashrafchowdury** [documenso/documenso#742]
### Issue Description

Currently, it is possible to update the profile information without actually changing anything. This is causing unnecessary database calls, which can impact the performance of the application.

### Steps to Reproduce

We need to implement a `logic` to ensure that something is modified before sending a request to the database upon clicking the `Update profile` button.

### Expected Behavior

The profile information has to be updated when something is changed on the profile.

### Current Behavior

We can update the profile info without changing anything by clicking the `Update profile button`

### Screenshots (optional)

Here I didn't change anything, but still I can update the profile.

https://github.com/documenso/documenso/assets/87828904/78c3e0cb-6ccc-490e-9c78-e1677a00777c

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome, Edge

### Version [e.g., 2.0.1]

2.0.1

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by ashrafchowdury** [comment]
> Team, if this is approved and you want it to be fixed, Then I can work on this issue.

I appreciate your collaborating mindset @crediblebilal. **But I raised it to work on this issue.**

**Comment by crediblebilal** [comment]
No issues @ashrafchowdury , you can take it. 👍

**Comment by Mythie** [comment]
Hey there, we've gone over this one before and prefer to just leave it clickable. The database/server trip is negligible and lets the UI remain intuitive 😄 

See: #585

**Comment by ashrafchowdury** [comment]
Ohh, I get you @Mythie 💁‍♂️

We can close this issue here.

**Comment by Mythie** [comment]
Chết!
