### ISSUE TITLE
[BUG] Submit Button going out of the box and are not accessible  

### ISSUE THREAD

**Issue by Mohith234** [documenso/documenso#744]
### Issue Description

This issue occurred in the single-player mode when I included more than 2 fields along with the Signature field. 

### Steps to Reproduce

- Go on to the Single Player Mode ([here](https://documenso.com/singleplayer))
- Upload any document
- Add Signature field and 2 other fields (name & email)
- Go to Step 2 ( You will not find any `Go back` and `Continue` Buttons )

### Expected Behavior

- The buttons should be accessible

### Screenshots (optional)

![image](https://github.com/documenso/documenso/assets/88539464/f2d1ecb8-1e85-407c-83f2-5c652a903dbd)

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Brave

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey there, looks like your screen might be tiny. Can I confirm what resolution this is displaying at?

**Comment by 99pswork** [comment]
Hi @Mohith234 ,
I request you to use the scroll bar and go to the bottom of the page.
If it's still not showing please share a recording.
Thanks
https://github.com/documenso/documenso/assets/52522379/0040e7f5-1c1b-4d0d-a21a-38b15b43edb3

**Comment by Mohith234** [comment]
@99pswork Here's the recording 

https://github.com/documenso/documenso/assets/88539464/55ef707a-f184-40f0-91be-3c4a62d96a10

**Comment by dguyen** [comment]
I replicated the issue successfully 👍 

@Mohith234 please go ahead and shoot us a PR for this whenever you want :)
