### ISSUE TITLE
Open file exploer when clicked on the "Add Document" section

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#748]
### Feature Description

As of now only drag and drop option is present in the "Add Document" section. It would be great if there was an option to open a file explorer on click.
<img width="1470" alt="Screenshot 2023-12-09 at 2 02 28 PM" src="https://github.com/documenso/documenso/assets/28510494/b36b57af-d5a8-4d8b-87b1-1031907d5a33">

### Proposed Solution

Add an on-click handler and replicate the same behaviour on drag and drop. 

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mythie** [comment]
Hey there this is already the case, if it isn’t could you let me know what browser you’re using 😬

**Comment by plxity** [comment]
@Mythie I'm using Chrome 119. I'm not able to see a file explorer by clicking on the section.

**Comment by anikdhabal** [comment]
@plxity It's already there.

**Comment by plxity** [comment]
@anikdhabal @Mythie Please find the attached video for reference. The onclick handler is not working in the case when the account is not verified. Even the change of colour to green shade on hover is not happening. So just wanted to confirm if that's the default behaviour we want to keep.

https://github.com/documenso/documenso/assets/28510494/ef833adc-9803-4964-909b-d3be973c94eb

**Comment by suryapts007** [comment]
Hi guys,

I would also like to point out that when the account is not verified, we are not even able to add a PDF even by dragging and dropping. 
@plxity can you verify this, please?

**Comment by Mythie** [comment]
Hi that’s intentional! If an account is verified we want to limit their actions to prevent against spam and abuse  😁

**Comment by plxity** [comment]
If that's intentional, we can show a toast or notification if someone tries to upload the PDF before verification. It would be good in terms of UX. What do you suggest?

**Comment by dephraiim** [comment]
I second that, I got a PR demonstrating a toast for unverified users. 

https://github.com/documenso/documenso/pull/749

**Comment by catalinpit** [comment]
Thanks for signalling this one! That's intentional for unverified accounts like others already said, and we'll try to make that more obvious. It'll be handled in #749.
