### ISSUE TITLE
Show List of Signers in Completed Email

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#75]
Currently, an email is sent to all the signers when signing is completed. 

Showing the list of other signers in the `Completed Email` will be a good enhancement.

**Comment by dephraiim** [comment]
Some people may expect to see the names of the signers in the mail as a way to verify that their signatures have been successfully added to the document although, others may prefer to keep their names private. 

Consider providing an opt-in or opt-out option for users to choose whether they want their names to be displayed in the mail.

**Comment by ElTimuro** [comment]
"Some people may expect to see the names of the signers in the mail" This will be redundant when accounts for receivers are supported. The plan is that when you have a Documenso account (created before or after signing) your documents including receivers will be shown there.
Closing this for now, but if this comes up in userfeedback we'll circle back to this.
