### ISSUE TITLE
[DOC-385] Long Document Names Breaking UI

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#755]
### **Description**

Uploaded documents with very long file names are breaking the UI of the confirm signing dialog

#### Confirm Signing Dialog

![CleanShot 2023-12-11 at 12.06.54@2x.png](https://uploads.linear.app/884f43d5-69da-459d-bc6b-864f16914e0f/5f196ac6-2b59-4c94-a2f1-3b69bc531441/3f8dc93b-25cf-48f0-88ec-115ce16d43f3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg4NGY0M2Q1LTY5ZGEtNDU5ZC1iYzZiLTg2NGYxNjkxNGUwZi81ZjE5NmFjNi0yYjU5LTRjOTQtYTJmMS0zYjY5YmM1MzE0NDEvM2Y4ZGM5M2ItMjVjZi00OGYwLTg4ZWMtMTE1Y2UxNmQ0M2YzIiwiaWF0IjoxNzAyMzAyNDI0LCJleHAiOjE3MDIzODg4MjR9.ZkX5Ntv53QK62BDuD2JSecJDuq4YYXPcBFU6Cj49hrc)

#### Complete Signing Page

![CleanShot 2023-12-11 at 12.14.09@2x.png](https://uploads.linear.app/884f43d5-69da-459d-bc6b-864f16914e0f/58fd3287-795c-48c8-9717-17fd9cb50c3d/9eb4fede-c6ca-4cc5-857d-8bdca467a4e6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg4NGY0M2Q1LTY5ZGEtNDU5ZC1iYzZiLTg2NGYxNjkxNGUwZi81OGZkMzI4Ny03OTVjLTQ4YzgtOTcxNy0xN2ZkOWNiNTBjM2QvOWViNGZlZGUtYzZjYS00Y2M1LTg1N2QtOGJkY2E0NjdhNGU2IiwiaWF0IjoxNzAyMzAyNDI0LCJleHAiOjE3MDIzODg4MjR9.eiQFDKmNUMxIeXPw-OMT5FO9UDzrCUFW8U1Qu57hqcU)

**Proposed Solution**

* Truncate the document name in the dialog to a specific length

### **Alternatives**

* No other alternatives

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-385](https://linear.app/documenso/issue/DOC-385/long-document-names-breaking-ui)</sub>

**Comment by Mohith234** [comment]
I think it would be good if we truncate the name like this `start...end.pdf`, What do you suggest?

I would like to work on this @dephraiim, as no one is assigned.

**Comment by dephraiim** [comment]
`start....pdf` is fine. I will assign this to you
