### ISSUE TITLE
Files with long names is breaking UI

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#76]
Files with long file names are breaking the UI. 

This is a sample screenshot

<img width="546" alt="Screenshot 2023-04-14 at 21 47 54" src="https://user-images.githubusercontent.com/55143799/232160903-4a51ebab-9a16-4f3e-b53b-f1a3d907fac3.png">
<img width="1440" alt="Screenshot 2023-04-14 at 21 48 52" src="https://user-images.githubusercontent.com/55143799/232160911-e6dd4427-2b93-4584-a4b7-46f2c26bdbbc.png">

**Comment by ElTimuro** [comment]
- Low priority.
- We should think about abbreviating everything longer than a context-specific length to "myverylongstri...".
- Should be well fixable with word wrap

**Comment by TheoOliveira** [comment]
Hey guys, can I be assign to this?

**Comment by dephraiim** [comment]
Heyyy @TheoOliviera, it is being worked on at #150.

But you can take a look at this #169

**Comment by Mythie** [comment]
Closed as part of #150 

Thanks everyone!
