### ISSUE TITLE
Using correct error message for name field

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#761]
### Issue Description

If there are fewer than 3 characters entered for the "name" input field, it displays the "Please enter a valid name" error message". This error message is not appropriate in terms of what exactly a "valid name" is. 

### Steps to Reproduce

1. Go to https://documenso.com/
2. Enter the email 
3. The Name field will appear after that, enter fewer than 3 characters. You will see the error message. 

### Expected Behavior

It should be more clear to users what does it mean. The error should be "Please enter more than 3 characters" or on a similar line. This would be a better user experience. 

### Current Behavior

Currently it displays "Please enter a valid name"

### Screenshots (optional)

<img width="358" alt="Screenshot 2023-12-14 at 10 47 58 AM" src="https://github.com/documenso/documenso/assets/28510494/c3bcab92-4849-4282-ab72-9f9fac580fb5">

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by plxity** [comment]
Would like to pick this up, if it gets approved.

**Comment by catalinpit** [comment]
Thanks for reporting this @plxity! I think it's fine for now. You can infer from the context that a name with only a letter is invalid, and a valid name would be something longer. As a result, I'm going to close this for now. Thanks for understanding!
