### ISSUE TITLE
Stacking issue with toast/notification and Header in mobile (CSS)

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#763]
### Issue Description

Currently, there is a stacking issue with the toast and header. 

### Steps to Reproduce

Try to create any toast/notification on mobile.

### Expected Behavior

The toast/notification should be stacked on top of anything in the UI.

### Current Behavior

The toast/notification is behind the header.

### Screenshots (optional)
<img width="335" alt="Screenshot 2023-12-16 at 12 21 48 AM" src="https://github.com/documenso/documenso/assets/28510494/b171e9d9-3ed3-4db6-9692-23552933aa1b">

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by plxity** [comment]
Would love to pick this up if it gets approved.

**Comment by Mythie** [comment]
Can do!
