### ISSUE TITLE
[docs]: change url for cloning

### ISSUE THREAD

**Issue by Dun-sin** [documenso/documenso#779]
### Improvement Description

this is just a minor improvement for the readme, it says this:
![image](https://github.com/documenso/documenso/assets/78784850/e5ef6317-b21b-4095-ae6a-92f93d0bae0f)
i think a better way is this:
```bash
   git clone https://github.com/<your-username>/documenso
```

### Rationale

Some people may make the mistake of copying that and trying to make changes to the actual repo instead of a fork, especially if they aren't super familiar with open source

### Please check the boxes that apply to this improvement suggestion.

- [ ] I have searched the existing issues and improvement suggestions to avoid duplication.
- [ ] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by catalinpit** [comment]
Makes sense. Thanks for the suggestion, @Dun-sin!

**Comment by sadamhussain-m** [comment]
Shall I make changes to the readme file?

**Comment by catalinpit** [comment]
> Shall I make changes to the readme file?

If you wish, you can. Should I assign the issue to you?

**Comment by sadamhussain-m** [comment]
Yes,U can assign me this issue.

**Comment by sadamhussain-m** [comment]
@catalinpit  I had created the PR with the changes.Could you please review it?.
