### ISSUE TITLE
Display the number of documents falling under each status (INBOX, PENDING, COMPLETED, DRAFT)  in mobile view as well

### ISSUE THREAD

**Issue by suryapts007** [documenso/documenso#782]
### Improvement Description

Currently, when we see the dashboard in desktop view, we can see the number of documents falling under each status (INBOX, PENDING, COMPLETED, DRAFT). But we don't see this data in the mobile view/ responsive view. 

I think it will be useful for the user to see these details, even in mobile view.

### Rationale

It will be useful information to see in the dashboard, even for the users using the web app on small devices. 

### Proposed Solution

Display the number of documents under each category for small-screen users as well.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by FatumaA** [comment]
On approval, would like to take this

**Comment by dguyen** [comment]
Sorry for the delay, @FatumaA do you still want to take this?

**Comment by FatumaA** [comment]
Yes

**Comment by dguyen** [comment]
Feel free to go ahead and create a PR for this :)

**Comment by FatumaA** [comment]
> Feel free to go ahead and create a PR for this :)

Done
