### ISSUE TITLE
Overlapping Title box border and Steps div in mobile/responsive view

### ISSUE THREAD

**Issue by suryapts007** [documenso/documenso#783]
### Issue Description

In the mobile and responsive view, when we select the Title input box, it is seen that the green border is partially hidden by the "Steps" div, which does not look good and there should be some separation between them

### Steps to Reproduce

1. Open the web app in mobile view
2. Upload a new pdf
3. Select the Title input box

Now you can see the bottom part of the border being overlapped.

### Expected Behavior

There should be some separation between the title and the steps div.

### Current Behavior

There is no separation between the divs.

### Screenshots (optional)

<img width="326" alt="Screenshot 2023-12-24 at 9 06 51 AM" src="https://github.com/documenso/documenso/assets/77022877/67cef0c8-a73d-4418-8a86-1bd8453b1a4a">

### Operating System [e.g., Windows 10]

Mac

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

119.0.6045.105

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by FatumaA** [comment]
I'd like to try this if approved

**Comment by dguyen** [comment]
@FatumaA the issue owner has requested to work on this issue already (see the bottom of the issue)

**Comment by dguyen** [comment]
Replicated the issue successfully 👍 

@suryapts007 please go ahead and create a PR whenever you want 🙂

**Comment by suryapts007** [comment]
Thanks @dguyen 
Here is the PR  https://github.com/documenso/documenso/pull/785

**Comment by catalinpit** [comment]
Fixed by https://github.com/documenso/documenso/pull/785

Thanks @suryapts007!
