### ISSUE TITLE
Provide option to Singup with Google on signup page

### ISSUE THREAD

**Issue by suryapts007** [documenso/documenso#791]
### Feature Description

Currently, the sign-up page at https://app.documenso.com/signup does not display the option for users to sign up using their Google accounts. This can potentially lead to confusion among new users who may assume that sign-up with Google is not supported on the platform.

### Use Case

**User Expectations:** New users might assume that since they see the Google Sign-In option on the sign-in page, they need to sign up with Google First. Having the Google Sign-Up option on the sign-up page aligns with user expectations.

**Consistent User Experience:** Providing the Google Sign-Up option on both the sign-in and sign-up pages ensures a consistent and intuitive user experience, reducing potential confusion.

**Improved Onboarding:** For users who prefer Google Sign-Up, having the option directly on the sign-up page streamlines the onboarding process and enhances user convenience.

### Proposed Solution

It is suggested to include the Google Sign-Up option on the sign-up page alongside other sign-up method. This will provide a seamless experience for users who might be visiting the site for the first time and are not familiar with the internal workings of Google OAuth.

### Additional Context

This issue is being created based on the discussion between me and @dguyen. The goal is to improve the user experience and avoid potential confusion for new users.
<img width="957" alt="Screenshot 2023-12-28 at 2 40 46 PM" src="https://github.com/documenso/documenso/assets/77022877/17222fb6-f100-4b39-8fa4-425432b4bf59">

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Just letting you know it might take some time for the response from our designer since it's holiday time

**Comment by suryapts007** [comment]
sure, np

**Comment by mittalsam98** [comment]
Hey if this is approved and @suryapts007 is not picking this up, I would love to work on this

**Comment by dguyen** [comment]
Hey @mittalsam98, this is already assigned, it's just pending some stuff 

We're currently waiting for our designer to provide a design since this is one of the first things new users see when they access the app for the first time.

The design might take some time since there's a backlog of other things

**Comment by dguyen** [comment]
Sorry for the delay @suryapts007, it seems like our designer is piled up with things to do.

Feel free to go ahead and implement this and we can review the design at a later date.

**Comment by suryapts007** [comment]
sure!

**Comment by suryapts007** [comment]
@dguyen I have also made some changes in text on the Sing In page, as they made sense in context to the new button added in the Sing Up page.
Screenshots of the final result are attached in the PR description. 
Have a look and do let me know what you guys think about it.
