### ISSUE TITLE
Error: unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by lexcorp** [documenso/documenso#801]
### Issue Description

I'm trying to install documenso on Rocky Linux 9.3, when run command npm run dx, I get this error:

[admin@localhost documenso]$ sudo npm run dx
[sudo] password for admin: 

> dx
> npm i && npm run dx:up && npm run prisma:migrate-dev

> prepare
> husky install

husky - Git hooks installed

changed 1 package, and audited 1558 packages in 8s

350 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (3 moderate, 1 critical)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> dx:up
> docker compose -f docker/compose-services.yml up -d

Error: unknown shorthand flag: 'f' in -f
See 'podman --help'

This is my environment:

[admin@localhost documenso]$ node -v
v18.19.0

[admin@localhost documenso]$ npm -v
10.2.3

[admin@localhost documenso]$ docker -v
podman version 4.6.1

PostgreSQL 14.10 

### Steps to Reproduce

[admin@localhost documenso]$ npm run dx

> dx
> npm i && npm run dx:up && npm run prisma:migrate-dev

> prepare
> husky install

husky - Git hooks installed

up to date, audited 1558 packages in 3s

350 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (3 moderate, 1 critical)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> dx:up
> docker compose -f docker/compose-services.yml up -d

Error: unknown shorthand flag: 'f' in -f
See 'podman --help'

### Expected Behavior

Installation success

### Current Behavior

Installation fails

### Screenshots (optional)

![Captura de pantalla de 2024-01-02 10-58-16](https://github.com/documenso/documenso/assets/5751288/65535965-d3cc-494b-81dd-ca289e9d7a9f)

### Operating System [e.g., Windows 10]

Rocky Linux 9.3

### Browser [e.g., Chrome, Firefox]

Chrome 

### Version [e.g., 2.0.1]

Versión 120.0.6099.129 (Build oficial) (64 bits)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey there, looks like you're using podman rather than docker and or a drop in replacements like Colima/OrbStack. The shorthand `-f` flag is for specifying the file to use for Docker Compose as you can gather from the command.

I'm unsure as to what podman expects but it seems weird to me that they would offer compose support without supporting common shorthand flags.

**Comment by Mythie** [comment]
Closing as this seems to resolved in the other linked issue.
