### ISSUE TITLE
SMS document signing

### ISSUE THREAD

**Issue by kodermax** [documenso/documenso#807]
### Feature Description

SMS document signing functionality allows users to sign documents using a secure SMS-based authentication process. This feature provides a convenient and efficient way for users to verify their identity and sign important documents without the need for additional hardware or software.

### Use Case

A user receives a document that requires their signature. Instead of printing, signing, and scanning the document, the user opts to use the SMS document signing functionality. The user initiates the signing process by entering their mobile phone number and receives a unique code via SMS. After entering the code into the system, the user's identity is verified, and they can proceed to sign the document electronically.

### Proposed Solution

The proposed solution for SMS document signing involves integrating a secure SMS authentication system with the document signing platform. When a user requests to sign a document, the system sends a unique code to the user's mobile phone number. The user then enters this code into the system to verify their identity and gain access to the document for signing. Additionally, the system should ensure that the SMS communication is encrypted and secure to protect sensitive information during the signing process.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by JoeSkills** [comment]
What like OTP

**Comment by JoeSkills** [comment]
So the code is sent to the user's phone and then they type the code in. is that what you mean?

**Comment by JoeSkills** [comment]
I would like to work on your issue, but could you explain it further

**Comment by kodermax** [comment]
The task is to implement SMS signing of documents. The document author selects the signing options, either manual signing or SMS signing, or both options simultaneously. The author can also specify the phone number of the signer so that a link to the document is sent to the phone. Upon receiving the document, the signer chooses the method of signing the document. If they choose to sign via SMS, they receive an SMS code, which they enter for verification. If the code is correct, a stamp is placed on the last page of the PDF document at the bottom, containing the following information: signer's name, phone number, signing date, SMS code, and a note that the document was signed using the documenso service. In addition, in the author's personal account, settings for SMS integration should be provided so that the author can specify the details of the SMS provider who will send SMS to clients.

**Comment by dguyen** [comment]
We've been doing some internal research for a while regarding 2FA sms authentication

There's a few different ways to authenticate via 2FA during the signing process. Some of them are:

- 2FA per field when required
- 2FA prior to being able to see the document
- 2FA at the final step when the user is ready to sign

> The author can also specify the phone number of the signer so that a link to the document is sent to the phone

I'm not sure we want to do this, because it would no longer be considered 2FA as the link contains the token. Instead of email + sms it would be sms + sms.

Could you outline a flow in steps so we can have a more concise understand of the 2FA implementation you're thinking about?
