### ISSUE TITLE
Active state remains even if element is not active in Navbar

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#808]
### Issue Description

Currently the active state remains active even if the element is not active.

### Steps to Reproduce

1. Signin into the application
2. Click on your Icon in Navbar
3. Click outside of the dropdown
4. The active state still remains. (Circe outside your image)

### Expected Behavior

The circle outside the image should only be there when the dropdown is open and shouldn't be there once the dropdown is closed. 

### Current Behavior

https://github.com/documenso/documenso/assets/28510494/d21d7934-197f-415a-a3a6-fac741496628

### Operating System [e.g., Windows 10]

MacOS

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

120.0.6

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by plxity** [comment]
I'll raise the fix for this

**Comment by ameeetgaikwad** [comment]
@plxity are you working on this, or should i take this one?

**Comment by Mythie** [comment]
The circle is based on focus active states, I kind of expect it to be a little funky due to the jumping between stacked contexts (popover).

If you do have a fix it'll be considered but I wouldn't deem this to be a high priority or anything like that 😄

**Comment by dguyen** [comment]
Hey everyone, this component is getting removed very soon and being replaced with something else as part of the teams feature.

Closing this issue.
