### ISSUE TITLE
Field should be dispaled while form is getting submitted

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#810]
### Issue Description

Currently, the input fields don't get disabled while the form is getting submitted, which allows users to update values while the request is being processed

### Steps to Reproduce

1. Login to the application
2. Visit `settings/profile`
3. Click on `Update Profile` CTA and change the value in between

### Expected Behavior

The input fields should be disabled while the request is ongoing

### Current Behavior

The input fields are not disabled while the request is ongoing

### Screenshots (optional)

https://github.com/documenso/documenso/assets/28510494/2384e915-0af0-445c-99c6-bfd2f9d06ed5

### Operating System [e.g., Windows 10]

MacOS

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

120.0.6

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by plxity** [comment]
@catalinpit Would like to know your opinion on this.

**Comment by catalinpit** [comment]
Hey @plxity, thanks for opening this issue! It's a good catch. I agree that the signature pad should be disabled while the form is submitting.

**Comment by hiteshwadhwani** [comment]
Is anyone working on this issue?

**Comment by plxity** [comment]
@hiteshwadhwani Yes, I’m.

**Comment by hiteshwadhwani** [comment]
ok @plxity

**Comment by Mythie** [comment]
This just needs a `<fieldset>` wrapped over it, you can find examples in our other forms 💪

**Comment by plxity** [comment]
@Mythie Thanks for the help. Apologies for delaying it, I was involved with some personal work.

**Comment by plxity** [comment]
@Mythie `fieldset` approach didn't work, I have used a different approach.

**Comment by roae** [comment]
@plxity @Mythie adding `pointer-events-none` class in containerClassName prop could work

**Comment by plxity** [comment]
@roae Agreed, this is a cleaner approach. Thanks for the suggestion. @Mythie Can you please review the changes - #842
