### ISSUE TITLE
Implement User Analytics for Document Signing Service

### ISSUE THREAD

**Issue by kodermax** [documenso/documenso#811]
### Feature Description

Implement analytics reporting and dashboards for both administrators and end users of the document signing service. Provides insights into usage metrics and signature activity.

### Use Case

Administrators can view adoption metrics to gauge growth and feature usage. Data guides decisions about marketing and product improvements.
Admins can diagnose issues by analyzing traffic, load, and turnaround times. Provides visibility into bottlenecks.
Users can view their personal usage statistics and signature history. Allows them to audit their activities.

### Proposed Solution

Build admin dashboard showing real-time aggregate metrics like traffic, load, and key counts.
Implement admin reporting page with filters and export of detailed signature data for offline analysis.
Create endpoints to allow ingestion of analytics data into external admin systems.
Add user dashboard showing their personal usage data and signature history table.
Pipeline analytics data from production DBs into a separate warehouse DB for analysis.

### Additional Context

Follow best practices like data security, aggregation, and rate limiting when handling analytics data.
Make analytics fast and responsive with indexed data, queues, caching and pre-computation.
Use dedicated DB servers for analytics to avoid impacting production workloads.
Instrument analytics features themselves to guide improvement efforts.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by hiteshwadhwani** [comment]
I'm eager to contribute to the development of this exciting feature. could you please provide additional details on the specific steps or guidelines you have in mind for working on this feature?

**Comment by ameeetgaikwad** [comment]
I would like to contribute! @kodermax

**Comment by dguyen** [comment]
Hey, thanks for bringing this up!

**Analytics**

Our application is document signing first, anything else would be add-ons and shouldn't be the focus of the application

Items like this probably should not go into the app directly:

- User cohorts - analyze trends across new vs returning users
- Funnel analysis - identify and optimize drop-off points in the signing flow
- User journeys - understand common paths users take through the signing process
- A/B testing - test variations of the signing flow to optimize conversions
- Funnel chart showing drop off rates during signing flow
- Pie chart showing percentage of completed vs abandoned signings
- Geographical distribution of users
- Drop off rates during signing flow
- Average time to complete signing process
- Most commonly signed document types
- Number of signatures requested vs completed
- Map showing geographical distribution of users

These should be done by a 3rd party service whose primary purpose is to handle things like this.

Internally, we currently use [PostHog](https://posthog.com/) which can handle all of the above and more.

The app has a env variable `NEXT_PUBLIC_POSTHOG_KEY` which is used to initialize the PostHog client if you would like to play around with it.

**Potential additions**

These features can also be done by using an external service, but it would also be nice to view in the current administrator stats page `/admin/stats` where we can already see certain metrics:

- Number of documents signed per day/week/month
- Number of unique users signing documents
- Line chart showing documents signed over time
- Bar chart showing top document types signed

**Current admin stats page (mockup data)**

![image](https://github.com/documenso/documenso/assets/20962767/e53631e0-19df-4813-b047-5080a84b679f)

**Next?**

I think the items in the potential addition section would be good to have directly part of the application.

Any opinions? These are just my thoughts on what we should be focusing on

**Comment by kodermax** [comment]
@dguyen I agree with the suggestion on the /admin/stats page it looks great!
