### ISSUE TITLE
[DOC-362] Using the provided signature of another user

### ISSUE THREAD

**Issue by dephraiim** [documenso/documenso#819]
When a document is sent to multiple signers, the first signer's default signature becomes accessible to other recipients in the same browser.

**Steps to Reproduce:**

1. Register a new account, adding a signature during the signup process.
2. Create a new document.
3. Add three signers to the document including the newly created account, ensuring a name field is assigned to each recipient.
4. Send the document to the recipients.
5. Sign the document using the newly registered account.
6. Attempt to sign the document using the accounts of the other recipients.

**Expected Behavior:**

Each recipient should only have access to their own signature, or empty when they don't have a signature

**Actual Behavior:** 
Upon attempting to sign the document as the other recipients, the default signature of the initial user is accessible and can be used for signing.

<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-362](https://linear.app/documenso/issue/DOC-362/using-the-provided-signature-of-another-user)</sub>

**Comment by Mythie** [comment]
This was dealt with a while back no? 🤔

**Comment by poorna-prakash-sr** [comment]
I can work on this

**Comment by dguyen** [comment]
I can't replicate this

**Comment by dguyen** [comment]
@ketanMehtaa thanks for checking!
