### ISSUE TITLE
Ctrl+K doesn't prevent default browser shortcut from executing

### ISSUE THREAD

**Issue by thisislvca** [documenso/documenso#829]
### Issue Description

The Ctrl+K command on documenso opens the command popup, but also triggers the browser's shortcut correspondent to the same keybindings - which on Chrome by default pulls up the search function on the navigation bar.

In other websites with a similar command popup (such as Vercel) this doesn't happen.

### Steps to Reproduce

[Open the documenso app](https://app.documenso.com) and press Ctrl+K.

### Expected Behavior

The command popup opens without triggering Chrome's shortcut

### Current Behavior

The command popup opens and triggers Chrome's shortcut, which in my case is quick search.

### Operating System [e.g., Windows 10]

Ubuntu 22.04.3 LTS

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

120.0.6099.216 (Official Build) (64-bit) 

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ameeetgaikwad** [comment]
I would like to contribute! Please assign me.

**Comment by aditya-chakraborty** [comment]
I would like to contribute to Documenso! Please assign this to me if possible.

**Comment by thisislvca** [comment]
@ameeetgaikwad @aditya-chakraborty I think the best way to contribute is to just open a PR that solves the issue! I'd do it myself but don't have much time rn haha

**Comment by dguyen** [comment]
I just tested on Chrome/FireFox on Windows10/MacOS but couldn't replicate this.

Is this an Ubuntu only issue? Can someone else test to check?

**Comment by dguyen** [comment]
We also currently have guidelines for taking issues:

https://github.com/documenso/documenso/blob/main/CONTRIBUTING.md#taking-issues

**Comment by thisislvca** [comment]
Bug is present on firefox and chrome. Strange thing is that documenso is the only website with this strange behavior...

**Comment by Mythie** [comment]
Apologies for the mis-step on my behalf here, I hadn't realised that it hadn't been assigned when approving and merging the associated PR. I'll try to do better 😓
