### ISSUE TITLE
Overflow Layout in Searchbar

### ISSUE THREAD

**Issue by Nisarg-Sha** [documenso/documenso#834]
### Additional Context

https://github.com/documenso/documenso/assets/96575158/f8af9c0a-f364-4e7d-b364-5872041ab3a4

### Please check the boxes that apply to this improvement suggestion.

- [ ] I have searched the existing issues and improvement suggestions to avoid duplication.
- [ ] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Nisarg-Sha** [comment]
Can you please assign it to me ?

**Comment by dguyen** [comment]
It looks like the scrollbar is missing for you, I can't seem to replicate this in Chrome MacOS 

![image](https://github.com/documenso/documenso/assets/20962767/66e7af79-b0d9-4c4e-9321-c16699ddf439)

Please go ahead and see if you can find a solution that resolves it for you.

**Comment by Nisarg-Sha** [comment]
When I sign in on my local device it shows a different layout, please correct me if I'm doing anything wrong

On documenso site it shows settings, On my side it shows templates and when I click it, it opens template page.

https://github.com/documenso/documenso/assets/96575158/51700836-2a60-48d7-854f-3f687301a2d5

**Comment by Mythie** [comment]
Reviewing the CSS it should have a scrollbar when applicable based on our overflow classes. Only ways it wouldn't display is either:

- The browser opts to not show it for _reasons_
- The overflow-x-hidden alongside it being pushed off screen is causing it to be cut off

While it probably isn't the latter it would be nice to check, you should be able to do this by toggling the overflow classes in your browsers devtools and then reporting the findings to us 😄
