### ISSUE TITLE
Improve Command Group Distinction

### ISSUE THREAD

**Issue by Gautam-Hegde** [documenso/documenso#836]
### Improvement Description

Enhance Command Group differentiation by introducing a subtle horizontal line for a more polished and streamlined visual appearance.

### Rationale

The addition of a separation line reduces redundancy and offers a clearer visual hierarchy for improved user comprehension.

![dc-enc](https://github.com/documenso/documenso/assets/85569489/2e688020-cfa1-4a44-8eca-a914714ba440)

### Proposed Solution

Include a thin horizontal line at the bottom of each Command Group to visually separate them. This can be achieved by adding a bottom border to the `CommandGroup` component, creating a more polished and organized appearance.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Makes sense to me!

**Comment by Gautam-Hegde** [comment]
Can I work upon this?

**Comment by dguyen** [comment]
Yeah of course! I've assigned it to you :)
