### ISSUE TITLE
Improved Document Dropzone UI

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#840]
### Improvement Description

Currently the document dropzone ui looks like this on hover.

<img width="942" alt="Screenshot 2024-01-17 234237" src="https://github.com/documenso/documenso/assets/75713174/0090e741-1e1c-4ccf-913f-eef1d9602814">

### Rationale

It doesn't look good on hover

### Proposed Solution

<img width="929" alt="Screenshot 2024-01-17 235850" src="https://github.com/documenso/documenso/assets/75713174/91f782da-927d-4036-ad1e-8db007aff5fd">

### Please check the boxes that apply to this improvement suggestion.

- [x] I have searched the existing issues and improvement suggestions to avoid duplication.
- [x] I have provided a clear description of the improvement being suggested.
- [x] I have explained the rationale behind this improvement.
- [x] I have included any relevant technical details or design suggestions.
- [x] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by sumitbishti** [comment]
I would like to take this up please.

**Comment by Mythie** [comment]
This is dependent on screen size and other aspects, if we're going to fix this we should consider how we avoid a bandaid fix so it works across a variety of resolutions.

If you're happy to do this I'm alright with assigning it to you 🙌

**Comment by sumitbishti** [comment]
Yes please, I'll do it. 
What I am going to do is check it for various resolutions and screen sizes and maybe browsers. 
And target the ones which it is not working for.

Anything else that I might be missing?
