### ISSUE TITLE
Security Issue in signing a document as any recipient.

### ISSUE THREAD

**Issue by Aman0802** [documenso/documenso#844]
### Issue Description

For signing any document as a recipient, we need to have the token for the recipient. Once we have the token, we can sign as any recipient. Once I get the token for another recipient I would be able to sign as that user. You might think how will one get the token, but when the documents are being listed on the /documents page, I can easily fetch the token of any other recipient from the network tab and go to /sign/[token] page, paste their token and sign as that specific recipient.

### Steps to Reproduce

Create a document with multiple recipients to sign. On the /documents page, open the network tab and see the recipients in the api call. Copy the token, and redirect to /sign/[token]. You would be able to sign as that recipient.

### Expected Behavior

One should not be able to see the fields and even sign as that recipient, when they come on /sign/[token]. A more secure way needs to be thought of.

### Current Behavior

I can sign as any other recipient and complete the document.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Aman0802** [comment]
I would like to take this up.

**Comment by Mythie** [comment]
/tip 100

Thanks for catching this! Resolved the issue for recipients being able to see tokens in their inbox, owners on the other hand are allowed to copy signing links to send it via other channels when email doesn't work 😄

**Comment by Aman0802** [comment]
Thanks! It amazing working on this!
