### ISSUE TITLE
Create an account deletion button

### ISSUE THREAD

**Issue by Mythie** [documenso/documenso#850]
**Description**

Since we're now starting to receive account deletion requests we should consider how we can reduce our workload by providing users a pain-free way to remove their account.

This should let users delete their data relating to Documenso without needing to contact our support channels.

**Rationale (Why should this be improved?)**

Making this improvement will not only provide a net reduction in support requests moving forward but also reduce an already frustrated users friction with Documenso which may help win them back at a later date.

**Proposed Solution (How will this be improved?)**

- Add a button for account deletion to the profile page.
- Make the button scary and inform the user of the data that will be deleted.
- Delete the users account and associated data upon click (may need a background job) and sign them out of their account.

**Caveats**

- Recipients should probably still retain a copy of documents that they have received since this is data that was sent to them.
- Due to this we could either orphan the document under an archive account e.g. `archived@documenso.com` or recreate the document for each recipient with them as an owner?
- If doing the above we should confirm that it complies with things such as CCPA and the right to be forgotten.

**Comment by dguyen** [comment]
Hey @aditya-chakraborty!

Thanks for offering, but we generally prefer tasks to be done end to end which makes it easier to review and manage
