### ISSUE TITLE
Bug: The days filter for documents doesn't work.

### ISSUE THREAD

**Issue by anikdhabal** [documenso/documenso#852]
### Issue Description

After changing the days value, the number of documents of all statuses doesn't change, and it also shows no result.

https://github.com/documenso/documenso/assets/81948346/b0c5a4a6-596c-48c1-9b8e-8b3e47daa091

### Please check the boxes that apply to this issue report.

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [x] I want to work on creating a PR for this issue if approved

**Comment by anikdhabal** [comment]
I want to work on creating a PR for this issue if approved.

**Comment by dguyen** [comment]
> the number of documents of all statuses doesn't change

Thanks for the catch! I've assigned it to you

> it also shows no result.

I'm assuming this is referring to the fact that there are no results in the table itself, which in this case makes sense since all the documents in the video appear to be older than 30 days (if this video was taken recently)

**Comment by anikdhabal** [comment]
> > the number of documents of all statuses doesn't change
> 
> Thanks for the catch! I've assigned it to you
> 
> > it also shows no result.
> 
> I'm assuming this is referring to the fact that there are no results in the table itself, which in this case makes sense since all the documents in the video appear to be older than 30 days (if this video was taken recently)

Hey @dguyen After testing it recently in production and also in dev, it is working. So, I think it is resolved.

**Comment by dguyen** [comment]
I don't think the issue where the tab numbers are not correct with a "day filter" is resolved

![image](https://github.com/documenso/documenso/assets/20962767/b738b092-e3e3-4ff0-a7b5-6ba4aab40338)

In this example, using the "last 7 days" filter should show the number 0 for every tab since all my documents are older than that
