### ISSUE TITLE
Bug: Completed and Pending status gets incremented twice when Sender is one of the Recipients

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#853]
### Issue Description

When you send a doc to yourself and sign it. Completed gets incremented twice.
When you send a doc to yourself and others, and only you sign it. Pending gets incremented twice.

### Steps to Reproduce

1. send a doc to yourself and sign it.
2. send a doc to yourself and one other, and only you sign it.

### Expected Behavior

Completed and Pending status should not be incremented twice when sender is one of the recipient.

### Current Behavior

Completed and Pending status is gettting incremented twice when sender is one of the recipient.

### Screenshots (optional)

Here T is the sender and E and T are the Recipients. And T has signed the doc.
<img width="926" alt="Screenshot 2024-01-21 230337" src="https://github.com/documenso/documenso/assets/75713174/9a7197fd-d3cd-4a0d-9242-0995634d44ac">

Here E is the sender and the Recipient too. And E has signed the doc.
<img width="931" alt="Screenshot 2024-01-20 222917" src="https://github.com/documenso/documenso/assets/75713174/a5b62bca-5274-4359-803d-4d26e8a838cf">

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by sumitbishti** [comment]
Would like to take this up. 
I have already dig into it and know exactly why this is happening. 
And can fix it up too.

**Comment by dguyen** [comment]
Sure, please go ahead :)
