### ISSUE TITLE
feat: 30 day email digest

### ISSUE THREAD

**Issue by anikdhabal** [documenso/documenso#861]
### Feature Description

Monthly summary emails for Documenso. Should include the number of documents with different statuses. For example, provide the count of completed documents for the last 30 days.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by anikdhabal** [comment]
I want to work on creating a PR for this issue if approved.

**Comment by dguyen** [comment]
Could you please outline the use case and proposed solution so we can have a more in-depth understanding of how this will all work?

This sounds similar to #811 where we would display this data on the dashboard, but this PR would be the act of emailing such data monthly?

**Comment by anikdhabal** [comment]
> Could you please outline the use case and proposed solution so we can have a more in-depth understanding of how this will all work?
> 
> This sounds similar to #811 where we would display this data on the dashboard, but this PR would be the act of emailing such data monthly?

We would like to send a monthly email to users, providing a summary of their activity. This summary will include the number of documents that have been completely signed, the count of documents in draft, and the total in pending status over the last 30 days. Additionally, we will highlight the most signed recipients along with their respective numbers in the email.

**Comment by dguyen** [comment]
Oh this is for users, from my perspective I don't really see this being used for individual users

This would probably be more relevant for teams or organizations

**Comment by dguyen** [comment]
I think it's currently not relevant at the moment, although in the future it may become applicable

Thanks for bringing this up though, it gives some ideas for much later down the line

I'll close the issue for now

**Comment by ElTimuro** [comment]
@dguyen I Agree, these kinds of update are noise very quickly and need to satisfy a very specific need if done right

**Comment by anikdhabal** [comment]
@dguyen @ElTimuro Thanks for your opinion. In the future, I would definitely love to work in this.
