### ISSUE TITLE
Undo option on signing pad not working correctly

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#864]
### Issue Description

On clicking undo icon, it clears the whole canvas instead of removing the recent changes

### Steps to Reproduce

1. https://app.documenso.com/settings/profile
2. Change signature
3. Click on Undo

### Expected Behavior

It should only undo the recent changes

### Current Behavior

It clears the complete canvas

### Screenshots (optional)

https://github.com/documenso/documenso/assets/28510494/c8afad61-bde1-4be4-b81b-b4bba25799a7

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by plxity** [comment]
@Mythie @catalinpit let me know what you folks think about this issue.

**Comment by Gautam-Hegde** [comment]
I think, undo functions normally when a signature stroke happens inside the sign-canvas area unless the user tries to cross over the canvas it behaves like this.

**Comment by Gautam-Hegde** [comment]
> @Gautam-Hegde I don't think so, the UX pattern involved with undo functionality remains the same -- Undo the previous event that happened, so if a stoke happens, undo button should just reverse it when click


https://github.com/documenso/documenso/assets/85569489/b03c3f6f-19f3-4833-82ec-f910b4c0b30e

**Comment by plxity** [comment]
> > @Gautam-Hegde I don't think so, the UX pattern involved with undo functionality remains the same -- Undo the previous event that happened, so if a stoke happens, undo button should just reverse it when click
> 
>  issue.864.mp4

Please watch the video I've attached to the issue. When I log in and navigate to `https://app.documenso.com/settings/profile`, add a stroke to the canvas and click on undo, it shouldn't clear the whole signature on the canvas. Instead, it should just remove the stroke that I just added.

**Comment by Gautam-Hegde** [comment]
> > > @Gautam-Hegde I don't think so, the UX pattern involved with undo functionality remains the same -- Undo the previous event that happened, so if a stoke happens, undo button should just reverse it when click
> > 
> > 
> > issue.864.mp4
> 
> Please watch the video I've attached to the issue. When I log in and navigate to `https://app.documenso.com/settings/profile`, add a stroke to the canvas and click on undo, it shouldn't clear the whole signature on the canvas. Instead, it should just remove the stroke that I just added.

Indeed, the issue exists. I also found an underlying bug where the undo button doesn't appear if the stroke overflows.

https://github.com/documenso/documenso/assets/85569489/0f19d274-8e24-4a8c-97a7-04c57fdfda18

**Comment by dguyen** [comment]
Nice find! 👍
