### ISSUE TITLE
Conflicting z-index between avatar in document list and header

### ISSUE THREAD

**Issue by joselimadev** [documenso/documenso#870]
### Issue Description

The avatar component within the document list has the same z-index value as the header component, causing the avatar to be above the header. When two elements have the same z-index value, the last one takes priority!

### Steps to Reproduce

Access the list of documents with 15 or more items

### Expected Behavior

![image](https://github.com/documenso/documenso/assets/30646629/38bd6dde-619c-4f58-86e2-ec2d038d43bc)

### Current Behavior

![image](https://github.com/documenso/documenso/assets/30646629/e4c2839d-68f3-4e56-ac65-f2bea6fb7aeb)

<img width="1276" alt="Captura de Tela 2024-01-25 às 15 09 22" src="https://github.com/documenso/documenso/assets/30646629/48faa1ab-9397-4537-9b53-535e612d1b26">

I think increasing the header z-index value by 10 (the current one is 50) is ok!

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by joselimadev** [comment]
I want to work on this issue if it gets approved!

**Comment by dguyen** [comment]
Assigned it to you :)
