### ISSUE TITLE
General questions of what Documenso can do

### ISSUE THREAD

**Issue by Tizzzzy** [documenso/documenso#871]
### Feature Description

Hi, huge fan of your work. I have some general questions about this project.
1. Does the system support online drafting of contracts, i.e., without the need for uploading, and provide specific contract templates?
2. Does the system support uploading .docx or .doc files for online modification of contract content?
3. Does the system support marking specific fields in the contract as 'required', and for required fields, must content be filled in to complete the contract drafting?
4. Does the system display modification records, support version comparison, and version recovery?
5. Does the system support downloading either the review or non-review version of a document?
6. Does the system support sending .docx files to an assistant API for analysis?
7. Does the system support selecting specific sentences within a document to trigger AI interpretation?
8. Does the system offer side-by-side AI analysis, and for the specific content given by the analysis, locate the related position in the document?

### Use Case

Online Drafting with Templates: Streamlines the contract creation process, making it faster and more standardized, especially for users without legal expertise.

Uploading and Modifying Documents Online: Allows for easy editing and updating of contracts, making the process more flexible and accessible from different devices and locations.

Marking Required Fields: Ensures that all critical information is included in a contract, reducing the risk of incomplete or legally non-compliant documents.

Modification Records and Version Control: Provides transparency in document changes, facilitates collaboration, and enables users to revert to earlier versions if needed, enhancing document integrity.

Download Options for Review: Offers flexibility in how documents are reviewed and shared, accommodating different stages of the review process.

Integration with Assistant API for Analysis: Leverages AI for advanced document analysis, potentially improving the accuracy and efficiency of contract review and risk assessment.

AI Interpretation of Selected Sentences: Enhances understanding and clarity of specific contractual terms or clauses, especially useful for non-experts.

Side-by-Side AI Analysis: Improves the efficiency of reviewing complex documents by pinpointing relevant sections, saving time and reducing the likelihood of human error.

### Proposed Solution

Online Drafting with Templates:

Technical: Implement a rich text editor (like TinyMCE or CKEditor) with template management. Use a database to store templates.
UI/UX: Offer a user-friendly interface with a selection of templates categorized by contract type. Include a preview and easy-to-use customization tools.

Uploading and Modifying Documents Online:

Technical: Use file handling APIs to upload documents and convert them to an editable format. Integrate with document editing libraries.
UI/UX: Provide a straightforward upload interface. Ensure the document editing tool is intuitive, with familiar text-editing features.

Marking Required Fields:

Technical: Implement form validation logic to identify and enforce filling of required fields.
UI/UX: Clearly highlight required fields, possibly with a different color or an asterisk. Provide real-time feedback when a required field is filled.

Modification Records and Version Control:

Technical: Implement a version control system, like Git. Record changes with timestamps and user IDs.
UI/UX: Display a version history log. Allow users to view differences between versions and revert to previous versions through a simple interface.

Download Options for Review:

Technical: Implement document exporting functionality with options for different formats and versions.
UI/UX: Provide a clear option to select and download either review or non-review versions, with descriptions of each.

Integration with Assistant API for Analysis:

Technical: Use API integration to send documents to an AI-powered assistant for analysis. This may involve natural language processing techniques.
UI/UX: Include an easy-to-use button or command to send documents for analysis, and display the analysis results in an easily digestible format.

AI Interpretation of Selected Sentences:

Technical: Implement text selection functionality and integrate with an AI model capable of understanding and interpreting legal language.
UI/UX: Allow users to simply highlight text and click a button to get an AI interpretation. The response should be displayed in a non-intrusive, easy-to-understand manner.

Side-by-Side AI Analysis:

Technical: Develop a split-screen interface where one side displays the AI analysis and the other the document, with automatic scrolling and highlighting.
UI/UX: Ensure that the split-screen view is responsive and does not clutter the screen. Highlights in the document should correspond clearly to the points made in the AI analysis.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [X] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.
- [X] I want to work on creating a PR for this issue if approved

**Comment by tedspare** [comment]
(2) is related to #893
