### ISSUE TITLE
Layout Shift between views

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#875]
### Issue Description

- The main content area layout jumps when switching a bit between tabs (Documents, Templates)

### Steps to Reproduce

- Just log in and switch between the tabs
- Watch the Logo

### Current Behavior

- Switching between the tabs should only change the content, the header bar should remain static
- The content should be the same within both views

### Screenshots (optional)

https://github.com/documenso/documenso/assets/1309312/7e2d3dd5-aa73-44ad-968b-7a2591c9a330

### Operating System [e.g., Windows 10]

MacOS Ventura 13.3.1

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

20.0.6099.234 (Official Build) (arm64)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by ksushant6566** [comment]
Picking this up :)

**Comment by ksushant6566** [comment]
This seems to be because of the scroll-bar. One tab has it & one doesn't. Raising a PR shortly

**Comment by SharmaTushar1** [comment]
Is this issue resolved? I'm unable to recreate it on my local machine running the latest main branch.

macOS Sonoma 14.2
Browser: Chrome, arc, edge

From what I can see #921 (possible fix) isn't merged yet.
