### ISSUE TITLE
Fix overflow of text on signing pad

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#877]
### Issue Description

Currently, the name is overflowing out of the signature section on landing page.

### Steps to Reproduce

1. Visit https://documenso.com/
2. Type the name on the demo PDF given

### Expected Behavior

Text-wrap should be there

### Current Behavior

Text is overflowing

### Screenshots (optional)

<img width="1024" alt="Screenshot 2024-01-27 at 12 39 23 PM" src="https://github.com/documenso/documenso/assets/28510494/736bec79-a8f8-4a58-99d7-e1e4493c7335">

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Nisarg-Sha** [comment]
Can I Work on this issue ?

**Comment by dguyen** [comment]
I think visually signatures should not wrap, but be scaled down

>  [X] I want to work on creating a PR for this issue if approved

I noticed you checked this @plxity, and also noticed you thumbs upped @Nisarg-Sha's comment

Are agreeing to let @Nisarg-Sha to work on this issue?

**Comment by plxity** [comment]
@dguyen Yes, @Nisarg-Sha can pick it up.

**Comment by plxity** [comment]
@Nisarg-Sha If you are not working on it, I can pick it up. Let me know.

**Comment by ephraimduncan** [comment]
Closing this issue as the signing pad is not currently available on the landing page.
