### ISSUE TITLE
Free document sending limitation bypass

### ISSUE THREAD

**Issue by ashrafchowdury** [documenso/documenso#883]
### Issue Description

I exactly don't know whether it's bug or a feature. The application fails to enforce the restriction on sending only 5 free documents per month effectively. **Users can bypass this limitation by creating new templates and sending documents through them**, without encountering any restrictions regarding their usage quota.

**Despite reaching the 5-document limit, the application allows the user to continue sending additional documents throw templates without any restriction.**

### Steps to Reproduce

1. Log in to the application
2. Crose the limitation of sending 5 documents in the free tire.
3. Then go to the templates page.
4. Create a new template.
5. Send the template document to signers.
6. Then if you want you can delete the template
7. Notice that the application does not display any warnings, errors, or notifications regarding exceeding the free document limit.

### Expected Behavior

The application should enforce the limitation on sending only 5 free documents including template documents also per month per user.

### Current Behavior

The application fails to enforce the free document limitation effectively. Users can easily bypass the restriction by creating new templates and sending documents through them without encountering any restrictions regarding their usage quota.

### Screenshots (optional)

https://github.com/documenso/documenso/assets/87828904/2840abb6-534a-452e-a185-39a4306669c5

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome, Edge

### Version [e.g., 2.0.1]

Latest

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by ashrafchowdury** [comment]
**I would like to work on this issue if it gets approved.**

**Comment by dguyen** [comment]
Thanks @ashrafchowdury! I've assigned it to you :)

**Comment by ashrafchowdury** [comment]
Hay @dguyen, 

To prevent exceeding the limit, I added a server condition that verifies before creating a new document from templates. Additionally, we will disable the 'Use Template' button on the frontend. 

When the 'Use Template' button becomes disabled after reaching the limit, users are not informed of the reason for it. To address this issue, we can add an Alert component to notify the user.

Here is the demo:
![image](https://github.com/documenso/documenso/assets/87828904/32b01fac-7c1f-47be-96dd-901f574ee5d0)

**Comment by dguyen** [comment]
Hey @ashrafchowdury, could you please create a PR so we can have a look?
