### ISSUE TITLE
Add i18n to documenso

### ISSUE THREAD

**Issue by NilsJacobsen** [documenso/documenso#885]
### Feature Description

I heard that some people have already discussed localizing Documenso. As a member of the [inlang](https://inlang.com/) core team, I can share my knowledge if you're interested.

### Use Case

For better expansion, i18n might be beneficial for documenso.

### Proposed Solution

If I would start localizing today, I would go for [ParaglideJS](https://inlang.com/m/gerre34r). It might be the best-performing i18n lib -> [hype video](https://www.youtube.com/live/pTgIx-ucMsY?feature=shared&t=3825)

I would also integrate some kind of quality with CI jobs. Check out [CLI Lint](https://inlang.com/m/2qj2w8pu) and [Lint Rules](https://inlang.com/c/lint-rules).

If you have translators, you can use the [localization editor](https://inlang.com/m/tdozzpar) and as a developer you can use the [ide extension](https://inlang.com/m/r7kp499g).

**But this is all opt-in, you just add a configuration file, so if you want, go with json.**

-> If you want help with the initial setup, let me know.

### Please check the boxes that apply to this feature request.

- [X] I have searched the existing feature requests to make sure this is not a duplicate.
- [X] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by anikdhabal** [comment]
Assign this to me. I've started working on it and hopefully will make a pull request soon.

**Comment by NilsJacobsen** [comment]
@anikdhabal which i18n stack are you using?:)

**Comment by anikdhabal** [comment]
> @anikdhabal which i18n stack are you using?:)

Hey I am using **next-i18next**.

**Comment by NilsJacobsen** [comment]
How far are you in the process? Did you look into ParaglideJS?

**Comment by kodermax** [comment]
@NilsJacobsen will this library allow you to switch between languages without changing the url to /de/en?

**Comment by NilsJacobsen** [comment]
I'm not really sure what you mean @kodermax. For sure you can also use a cookie strategy for i18n. If you discovered a big can you please open an issue https://github.com/opral/monorepo/issues.

**Comment by NilsJacobsen** [comment]
Hey folks, how far along are you with the i18n implementation?

**Comment by ElTimuro** [comment]
- @NilsJacobsen so far didn't start, since there was a lot other other priorities
- We are open to looks at suggestions, though

**Comment by NilsJacobsen** [comment]
Which parts of the repo are planned to be localized? I guess the nextjs apps right?

Then I recommend [paraglide-next](https://inlang.com/m/osslbuzt/paraglide-next-i18n/). It's also recommended by nextjs -> https://nextjs.org/docs/app/building-your-application/routing/internationalization#resources (mentioned as inlang)

**Comment by ElTimuro** [comment]
Yes the apps (website, webapp and docs eventually)

**Comment by opiredev** [comment]
@nabby27 created a $20.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by younes101020** [comment]
Anyone on this ?

**Comment by younes101020** [comment]
since no one answered me I assume that no one is on it, I implement the internationalization for the marketing part and I send the pr tomorrow.
