### ISSUE TITLE
Better UX for showing pricing section in mobile

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#894]
### Describe the improvement you are suggesting in detail

Currently, when we switch from monthly to yearly or vice versa in mobile, the user doesn't get to know what exactly changes because there is no movement or update on the screen. I'm attaching a video for reference. 

I feel we should scroll the user to the pricing section (where the amount is changed) if they switch between the monthly/yearly tabs. 

https://github.com/documenso/documenso/assets/28510494/7ea6d892-b754-4559-88d8-284dc155bd47

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
@goutham-documenso thoughts on the flow for this?

**Comment by plxity** [comment]
@goutham-documenso We can stack cards as the user scrolls. This could be a good solution as well.

**Comment by ElTimuro** [comment]
Please keep in that that ar least 1 more (if not more) pricing Tiers will be added soon while implementing

**Comment by dguyen** [comment]
@goutham-documenso the switch sticky sounds good, can you please provide a design?

**Comment by goutham-documenso** [comment]
@dguyen I'll share the design shortly.

**Comment by goutham-documenso** [comment]
Here's the design
https://www.figma.com/file/2UpmlfgunLLbbyMImsTB3e/Pricing-page---mobile?type=design&node-id=0%3A922&mode=design&t=pP79PtdZBF7QfLuZ-1

@dguyen

**Comment by dguyen** [comment]
@plxity are you good with implementing the above design for mobile?

**Comment by JuanSebastianM** [comment]
Hey there! 

I know @plxity already mentioned in the issue description that he'd like to work on this but since it's been 1 month since the last comment, I'd like to know if I can work on it.

**Comment by dguyen** [comment]
@JuanSebastianM, sure! I've reassigned it to you
