### ISSUE TITLE
Unable to send document 

### ISSUE THREAD

**Issue by tedspare** [documenso/documenso#895]
### Issue Description

After adding recipients, fields, and a subject line and body, the "Send" button spins for about 10s before an error message:

`TRPCClientError: We were unable to send this document. Please try again later.` (from [trpc/server/document-router](https://github.com/documenso/documenso/blob/27d8098511e4d62f01f1ad403ead38ee88b47616/packages/trpc/server/document-router/router.ts#L239))

### Steps to Reproduce

Upload a document, add a signee, add signature fields, add a subject line and body, click send.

### Expected Behavior

Document sends successfully

### Current Behavior

Document fails to send

### Screenshots (optional)

<img width="532" alt="image" src="https://github.com/documenso/documenso/assets/36117635/7d2e82af-0837-40fb-8ab8-108e4e6e9fad">

### Operating System [e.g., Windows 10]

MacOS

### Browser [e.g., Chrome, Firefox]

Arc

### Version [e.g., 2.0.1]

Not sure (web)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Hello! Could you please provide some information on how you are running the app?

Are you running it locally via `npm run dev`, or using something like Vercel/GitPod/other?

Could you also paste the log (not from the browser, but from the server) when the error occurs if possible?
