### ISSUE TITLE
Layout shifts when tab changes

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#901]
### Issue Description

Layout shift happens when you change tabs on `https://app.documenso.com/documents`

### Steps to Reproduce

1. Login to App
2. Go to Documents
3. Switch between any tabs to filter the documents based on status

### Expected Behavior

Layout shifts should not happen.

### Screenshots (optional)

https://github.com/documenso/documenso/assets/28510494/38d9eb88-c5fd-47a5-9484-a627cac90562

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
It's expected to shift around as data is generally different between the tabs.

Please feel free to look into reducing layout shift when not required though :)
