### ISSUE TITLE
[Improvement] Better UI and UX for marketing footer

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#902]
### Describe the improvement you are suggesting in detail

Something like this, where everything is in center
<img width="928" alt="Screenshot 2024-02-03 232730" src="https://github.com/documenso/documenso/assets/75713174/48cffbfd-8172-4635-839e-42f5279a26c4">

OR this
<img width="926" alt="Screenshot 2024-02-03 233151" src="https://github.com/documenso/documenso/assets/75713174/15a89ddb-72d3-45c3-b633-a97748cc75b3">

### Additional Information & Alternatives (optional)

currently it looks like this
<img width="947" alt="image" src="https://github.com/documenso/documenso/assets/75713174/b0a27a1a-847b-4b76-bf5f-7d60630616cf">

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Thanks for looking into areas where we can improve designs, but we're currently not looking to have any significant design changes besides UI or UX issues.
