### ISSUE TITLE
Unable to re-attach document in singleplayer mode

### ISSUE THREAD

**Issue by prajwalkulkarni** [documenso/documenso#903]
### Issue Description

I recently wanted to get my rent receipts signed by the landlord, so I headed over to single-player mode to start the signing process. I accidentally uploaded the wrong file and realized it after some time. I wanted to re-upload the correct document but there wasn't an easy way to do it. I had to navigate back and forth to start the process afresh, which is not very intuitive. 

### Steps to Reproduce

1. Navigate to single-player mode (https://documenso.com/singleplayer)
2. Upload any document
3. Try removing and reuploading a new document without clicking on the back/forth button on the browser navbar. 

### Expected Behavior

We should be able to re-upload the document once any document is uploaded. The "Go back" button can be rendered as "Reupload" or something similar once the document is uploaded. Currently, it is unresponsive on step 1.
In addition, the progress bar is 50% complete simply by navigating to single-player mode and without having to upload any document. I feel the progress bar should update to 50% or any number after the user adds a document. I might be wrong here, but I'm just thinking out loud.

### Current Behavior

Currently, there is no simple way to remove and add a new document, and the "Go back" button is unresponsive in Step 1.

### Operating System [e.g., Windows 10]

Windows 11

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

Version 121.0.6167.140 (Official Build) (64-bit)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
> We should be able to re-upload the document once any document is uploaded. The "Go back" button can be rendered as "Reupload" or something similar once the document is uploaded. Currently, it is unresponsive on step 1.

Makes sense, I've assigned it to you :)

> In addition, the progress bar is 50% complete simply by navigating to single-player mode and without having to upload any document. I feel the progress bar should update to 50% or any number after the user adds a document. I might be wrong here, but I'm just thinking out loud.

I think it's fine currently, since if it's the other way the final step interaction would be strange where it's 1/2 until the user clicks submit
