### ISSUE TITLE
[Improvement] Blog Page is not responsive in mobile

### ISSUE THREAD

**Issue by rajesh-1252** [documenso/documenso#904]
### Describe the improvement you are suggesting in detail

1. "In mobile screens, the text is cut off at the right side in the blog preview."
2. "Here is the link to the affected page: https://documenso.com/blog"
![image](https://github.com/documenso/documenso/assets/71485855/40296198-8e03-4e09-8778-031084fa955e)

It has to look like this
![image](https://github.com/documenso/documenso/assets/71485855/7321a890-9d8c-48d4-b985-f50a7b2e1d9b)

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [ ] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Thanks for finding this, assigned it to you :)
