### ISSUE TITLE
[Bug] Documents can be sent with no fields at all to sign

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#908]
### Issue Description

Currently we can send documents having no fields (date, name, signature, email) to get signed.

### Steps to Reproduce

Upload a doc
enter title and email
do not select any fields, hit continue
it will be sent to the recipient with no fields

### Expected Behavior

the doc to be sent should have at least one field(signature) 

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by ElTimuro** [comment]
Yes, this behavior is not correct/ wanted. A solution we already discussed internally:
Allowing documents with no fields, but forcing the user to place one during signing (with optional fields like date, etc.)

@Mythie let me know if we should do this ourselves our accept contributions
@sumitbishti would you be interested in working on this if we accept contributions on this? Thanks for reporting this so far :)

**Comment by sumitbishti** [comment]
Yes, I would be interested in working on this for sure.

**Comment by ElTimuro** [comment]
@Mythie afaik we are not internally working on this, right? Should have take submissions for this?

**Comment by ElTimuro** [comment]
Adding to internal board for visibility, since i want to keep and eye on this
