### ISSUE TITLE
[Bug] Document title can be kept empty

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#909]
### Issue Description

The document title, which is not supposed to be empty, can be submitted as empty if a space character is entered into the title field.

### Expected Behavior

Title shouldn't be empty

### Screenshots (optional)

<img width="821" alt="Screenshot 2024-02-05 232808" src="https://github.com/documenso/documenso/assets/75713174/926ad345-e01d-42ec-8be7-c992856872c4">

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
Thanks for the catch, I've assigned it to you @sumitbishti :)

**Comment by sumitbishti** [comment]
Thanks @dguyen. Will submit a PR soon.
