### ISSUE TITLE
Render.com install failed

### ISSUE THREAD

**Issue by dougkeiller** [documenso/documenso#931]
### Issue Description

Deploy failed for f72b669: feat: restrict app access for unverified users (#835)
Exited with status 1 while building your code. Check your deploy logs for more information.

Feb 14, 12:43 PM - 12:48 PM
PST

INFO==> Cloning from https://github.com/documenso/documenso
INFO==> Checking out commit f72b669f67354284e22085f9478aceb1075c0cf1 in branch main
INFO==> Using Node version 18.17.0 via environment variable NODE_VERSION
INFO==> Docs on specifying a Node version: https://render.com/docs/node-version
INFO==> Running build command 'npm i && npm run build:web'...
INFO
INFO> prepare
INFO> husky install
INFO
INFOhusky - Git hooks installed
INFO
INFOadded 1545 packages, and audited 1561 packages in 45s
INFO
INFO360 packages are looking for funding
INFO  run `npm fund` for details
INFO
CRITICAL9 vulnerabilities (5 moderate, 4 critical)
INFO
INFOTo address issues that do not require attention, run:
INFO  npm audit fix
INFO
INFOTo address all issues possible (including breaking changes), run:
INFO  npm audit fix --force
INFO
INFOSome issues need review, and may require choosing
INFOa different dependency.
INFO
INFORun `npm audit` for details.
INFO
INFO> build:web
INFO> turbo run build --filter=@documenso/web
INFO
INFOTurborepo did not find the correct binary for your platform.
INFOWe will attempt to install it now.
INFOInstallation has succeeded.
INFO• Packages in scope: @documenso/web
INFO• Running build in 1 packages
INFO• Remote caching disabled
INFO@documenso/prisma:build: cache miss, executing 0896a41ae6a3b58e
INFO@documenso/prisma:build: 
INFO@documenso/prisma:build: > @documenso/prisma@1.0.0 build
INFO@documenso/prisma:build: > prisma generate
INFO@documenso/prisma:build: 
INFO@documenso/prisma:build: Prisma schema loaded from schema.prisma
INFO@documenso/prisma:build: 
INFO@documenso/prisma:build: ✔ Generated Prisma Client (v5.4.2) to ./../../node_modules/@prisma/client in 356ms
INFO@documenso/prisma:build: 
INFO@documenso/prisma:build: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
INFO@documenso/prisma:build: ```
INFO@documenso/prisma:build: import { PrismaClient } from '@prisma/client'
INFO@documenso/prisma:build: const prisma = new PrismaClient()
INFO@documenso/prisma:build: ```
INFO@documenso/prisma:build: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
INFO@documenso/prisma:build: ```
INFO@documenso/prisma:build: import { PrismaClient } from '@prisma/client/edge'
INFO@documenso/prisma:build: const prisma = new PrismaClient()
INFO@documenso/prisma:build: ```
INFO@documenso/prisma:build: 
INFO@documenso/prisma:build: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
INFO@documenso/prisma:build: 
INFO@documenso/web:build: cache miss, executing 434a4722220f042a
INFO@documenso/web:build: 
INFO@documenso/web:build: > @documenso/web@1.2.3 build
INFO@documenso/web:build: > next build
INFO@documenso/web:build: 
INFO@documenso/web:build: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
INFO@documenso/web:build:    ▲ Next.js 14.0.3
INFO@documenso/web:build:    - Experiments (use at your own risk):
INFO@documenso/web:build:      · outputFileTracingRoot
INFO@documenso/web:build: 
INFO@documenso/web:build:    Creating an optimized production build ...
INFO@documenso/web:build:  ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
INFO@documenso/web:build: Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (328kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build: <w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (127kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
INFO@documenso/web:build:  ✓ Compiled successfully
INFO@documenso/web:build:    Linting and checking validity of types ...
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/app/(dashboard)/admin/nav.tsx
WARNING@documenso/web:build: 3:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/app/(dashboard)/admin/users/data-table-users.tsx
WARNING@documenso/web:build: 61:6  Warning: React Hook useEffect has missing dependencies: 'perPage' and 'updateSearchParams'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/app/(dashboard)/documents/data-table-title.tsx
WARNING@documenso/web:build: 8:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/app/(dashboard)/templates/data-table-title.tsx
WARNING@documenso/web:build: 5:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/app/(share)/share/[slug]/page.tsx
WARNING@documenso/web:build: 1:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/components/(dashboard)/avatar/stack-avatars.tsx
WARNING@documenso/web:build: 5:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/components/branding/logo.tsx
WARNING@documenso/web:build: 1:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/components/formatter/template-type.tsx
WARNING@documenso/web:build: 1:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
WARNING@documenso/web:build: 6:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/components/ui/background.tsx
WARNING@documenso/web:build: 1:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: ./src/providers/next-theme.tsx
WARNING@documenso/web:build: 6:1  Warning: All imports in the declaration are only used as types. Use `import type`.  @typescript-eslint/consistent-type-imports
INFO@documenso/web:build: 
INFO@documenso/web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
INFO@documenso/web:build:    Collecting page data ...
INFO@documenso/web:build:  ⚠ Using edge runtime on a page currently disables static generation for that page
ERROR@documenso/web:build: Error: Missing DOCUMENSO_ENCRYPTION_KEY or DOCUMENSO_ENCRYPTION_SECONDARY_KEY keys
INFO@documenso/web:build:     at 29145 (/opt/render/project/src/apps/web/.next/server/chunks/8789.js:1:18009)
INFO@documenso/web:build:     at t (/opt/render/project/src/apps/web/.next/server/webpack-runtime.js:1:143)
INFO@documenso/web:build:     at 13542 (/opt/render/project/src/apps/web/.next/server/chunks/8789.js:1:18675)
INFO@documenso/web:build:     at t (/opt/render/project/src/apps/web/.next/server/webpack-runtime.js:1:143)
INFO@documenso/web:build:     at 71919 (/opt/render/project/src/apps/web/.next/server/app/(dashboard)/settings/password/page.js:1:12704)
INFO@documenso/web:build:     at Function.t (/opt/render/project/src/apps/web/.next/server/webpack-runtime.js:1:143)
INFO@documenso/web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
INFO@documenso/web:build:     at async collectGenerateParams (/opt/render/project/src/node_modules/next/dist/build/utils.js:884:17)
INFO@documenso/web:build: 
ERROR@documenso/web:build: > Build error occurred
ERROR@documenso/web:build: Error: Failed to collect page data for /settings/password
INFO@documenso/web:build:     at /opt/render/project/src/node_modules/next/dist/build/utils.js:1217:15
INFO@documenso/web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
ERROR@documenso/web:build:   type: 'Error'
INFO@documenso/web:build: }
ERROR@documenso/web:build: npm ERR! Lifecycle script `build` failed with error: 
ERROR@documenso/web:build: npm ERR! Error: command failed 
ERROR@documenso/web:build: npm ERR!   in workspace: @documenso/web@1.2.3 
ERROR@documenso/web:build: npm ERR!   at location: /opt/render/project/src/apps/web 
ERROR@documenso/web:build: ERROR: command finished with error: command (/opt/render/project/src/apps/web) npm run build exited (1)
INFO@documenso/web#build: command (/opt/render/project/src/apps/web) npm run build exited (1)
INFO
INFO Tasks:    1 successful, 2 total
INFOCached:    0 cached, 2 total
INFO  Time:    1m30.092s 
INFOFailed:    @documenso/web#build
INFO
ERROR ERROR  run failed: command  exited (1)
INFO==> Build failed 😞
INFO==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys

### Screenshots (optional)

![image](https://github.com/documenso/documenso/assets/128188043/1281a9eb-5c2a-4fa2-9758-ca7f0490e541)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey thanks for flagging this! As part of our recent changes we've introduced some new environment variables which weren't also added to the corresponding `render.yaml` file.

Please feel free to add them and let us know how you go 😄

**Comment by dougkeiller** [comment]
> Hey thanks for flagging this! As part of our recent changes we've introduced some new environment variables which weren't also added to the corresponding `render.yaml` file.
> 
> Please feel free to add them and let us know how you go 😄

Hi Mythie,

Thanks for responding so quickly!

How do I find the changes and add to render.yaml?

Or better for you guys to update the Render.com template and then I'll try again?

**Comment by ephraimduncan** [comment]
Hi, @dougkeiller 

The render template has been updated.

I'll close this now
