### ISSUE TITLE
Add users in paid $30 plan

### ISSUE THREAD

**Issue by dougkeiller** [documenso/documenso#933]
Hi,

I am a paid (monthly) user. How do I add users, so they can create and send documents to me for signing?

Thanks, Doug

**Comment by Mythie** [comment]
Hey Doug!

We just tagged a release with the teams feature, it will be rolling out within the next couple of days after we finish a tiny bit more testing.

As a user on the $30 plan you will be able to create a team and invite members at no extra cost, keep your eyes peeled 🙌🏻

**Comment by dguyen** [comment]
Hey @dougkeiller! We've released teams now, please let us know if there are any issues or questions :)

You should be able to access it when clicking the dropdown top right of the page

![image](https://github.com/documenso/documenso/assets/20962767/f0ae6de3-d70d-43b0-8e74-70737afacc73)

**Comment by dougkeiller** [comment]
great!

so for $30 I can add other users?

Doug Keiller
***@***.***
(310) 633-7714

**Comment by dguyen** [comment]
@dougkeiller you can create a team and invite users to become team members.

These team members can send unlimited documents from the team. 

Please note that any documents sent from a team will be seen by other team members.

**Comment by dougkeiller** [comment]
Hi Guys,

Testing it out.

Admin who sends docs for signature cannot see where in the process the doc
is. Eg 2 signers: who has signed so far? who is pending?

Need better visibility into steps to complete signing.

Doug Keiller
***@***.***
(310) 633-7714

**Comment by dguyen** [comment]
Hi @dougkeiller 

There are currently two ways to see the progress for a given document:

1. On the documents page, you can hover over the recipient to see the current state of each recipient

![image](https://github.com/documenso/documenso/assets/20962767/eebf4506-6b5b-455e-bdc8-59ad73dba32c)

2. Clicking the document title in the table will take you to a dedicated page where you can see a full overview of the document

![image](https://github.com/documenso/documenso/assets/20962767/ae6658a8-d8a8-4347-882f-06a8cac04f50)
