### ISSUE TITLE
[Bug] Profile Dropdown Panel is not scrollable

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#942]
### Issue Description

Neither it is scrollable thorugh mouse nor through arrow keys. 
Although i am able to navigate to the items, but the items doesn't scroll into view.

You can see the currently selected item is the Team with the team url "/sume" at the bottom left of the screen. But it is not in the view.
<img width="937" alt="image" src="https://github.com/documenso/documenso/assets/75713174/585c8c1a-a0cf-4100-97ad-ce67a319b562">

### Steps to Reproduce

Just create a lot of teams until you are not able to see them on the screen.
Then try to scroll or navigate to the item not in the view.

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by dguyen** [comment]
I think setting a max height on the teams section with a scrollbar when overflowing would be the solution, what do you think?

**Comment by sumitbishti** [comment]
> I think setting a max height on the teams section with a scrollbar when overflowing would be the solution, what do you think?

Yeah i have done just that.
