### ISSUE TITLE
[Improvement] Add a differentiator to the teams in Profile Dropdown

### ISSUE THREAD

**Issue by sumitbishti** [documenso/documenso#943]
### Describe the improvement you are suggesting in detail

If we allow to create multiple teams with the same name. Then how are we supposed to differentiate btw them in the profile dropdown?

<img width="937" alt="image" src="https://github.com/documenso/documenso/assets/75713174/906b1010-cb66-4997-a4c3-c3ee3501fe10">

### Additional Information & Alternatives (optional)

We should either have unique team names
or
We should also show the team url in a team item box in dropdown. 
something like this:
```
sum (owner)
localhost:3000/t/sume
``` 
```
sum (owner)
localhost:3000/t/notsume
```

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by dguyen** [comment]
Oh, we had a design for this I think. I just forgot to implement it.

When you hover over the element, it should change the team role to the team url with a fade in/out animation.

**Comment by sumitbishti** [comment]
Ok let me implement it then

**Comment by sumitbishti** [comment]
> Oh, we had a design for this I think. I just forgot to implement it.
> 
> When you hover over the element, it should change the team role to the team url with a fade in/out animation.

Should fade in/out be just for the team url or the complete item?

**Comment by dguyen** [comment]
Probably just the team url
