### ISSUE TITLE
Unable to activated billing / subscriptions in Dashboard

### ISSUE THREAD

**Issue by dwinurhadia** [documenso/documenso#948]
### Issue Description

Dear Team,
I've to try to setup Documenso with Subscritions features
But when i check in the dashboard, there is only Free Plan, nothing show monthly or yearly plan features
I already add to the STRIPE in `.env `with test API keys

How i can enable that features?

### Screenshots (optional)

<img width="1010" alt="image" src="https://github.com/documenso/documenso/assets/19340965/7260a2aa-e51c-40aa-b7d1-46724a1b54e3">

### Operating System [e.g., Windows 10]

Ubuntu 22.04

### Browser [e.g., Chrome, Firefox]

Chrome

### Version [e.g., 2.0.1]

latest v1.4.0

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
Hey there, billing is under our enterprise featureset. Could I ask for more information as to what you're trying to do? 😄

**Comment by dwinurhadia** [comment]
Hi @Mythie 
is that possible to enable in self-hosted instalations?

**Comment by Mythie** [comment]
It is possible to enable but it's not something we support without an enterprise license, thus it's not as straightforward as general _free_ self-hosting

**Comment by dwinurhadia** [comment]
Well, thank you so much @Mythie
