### ISSUE TITLE
feat: ability to add team member as a signer

### ISSUE THREAD

**Issue by anikdhabal** [documenso/documenso#949]
### Feature Description

- I think it would be nice if we provide the ability to choose team members as signers. Display a dialog to select team members as signers in the 'Add Signer' section.

 Or
 
- Autofill the signer input with team members details during. Now it depends on the user whom to keep and whom to remove.

This feature provides additional functionality on top of the current behavior and is only for team signing.

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.
- [X] I want to work on creating a PR for this issue if approved

**Comment by anikdhabal** [comment]
If you approve the idea, please suggest which one you think would be cool.

**Comment by dguyen** [comment]
Going to close this for now as this idea should be merged in with this other issue once we're ready for it in the future:

https://github.com/documenso/documenso/issues/924

To clarify, we'll probably end up with an autocomplete system where saved contacts and team members pop up.
