### ISSUE TITLE
[DOC-234] Simple Electronic Signature (SES) - eIDAS Level 1 Compliance

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#95]
<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-234](https://linear.app/documenso/issue/DOC-234/simple-electronic-signature-ses-eidas-level-1-compliance)</sub>

**Comment by racso-dev** [comment]
Is this feature available in the self-hosted community version? Also is level 2 compliance planned?
