### ISSUE TITLE
Show close icon on notification in mobile

### ISSUE THREAD

**Issue by plxity** [documenso/documenso#965]
### Issue Description

We display a close icon on notifications on hover, but for mobile and tablet category devices, there is no hover state. In such cases, we should show the close icon by default.

### Steps to Reproduce

Perform any action that displays notifications and view it on mobile. Please check the video I've uploaded for reference as well. 

### Expected Behavior

The close icon should be displayed always on mobile devices.

### Current Behavior

Only on focus it is getting displayed.

### Screenshots (optional)

https://github.com/documenso/documenso/assets/28510494/580fd9a0-b73a-485d-a087-85a26d479295

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by Mythie** [comment]
On mobile they're swipe to dismiss instead afaik 😄 

Adding a close icon would likely not net a good result either since the touch target would be so small it would be easy to miss and/or accidentally dismiss something you were reading.

**Comment by plxity** [comment]
Alright, then maybe we should not show the close icon on the focus state in mobile, we can do display: none if it's mobile, just a thought. What do you think?

**Comment by dguyen** [comment]
Swipe up to dismiss doesn't work for me on iOS mobile

>  In such cases, we should show the close icon by default.

Lets make it always show on mobile only for now

**Comment by ameeetgaikwad** [comment]
@plxity if you are not working on this, would like to take this one!

**Comment by plxity** [comment]
@ameeetgaikwad I'm working on it

**Comment by plxity** [comment]
@rohit-saluja that's good. but you should've not done it. I already said i'm working on it in background. Please take care of it next time.

**Comment by Mythie** [comment]
So to confirm, @plxity do you wish to continue on this PR? Rohit's solution is correct but since it was assigned to you we're happy to close it off and let you raise yours instead 😄 

Apologies for the confusion @rohit-saluja issues raised here get assigned to avoid any double work and hurt feelings 😸

**Comment by plxity** [comment]
@Mythie We can go ahead with the PR, no worries :)

**Comment by Mythie** [comment]
Cheers Apoorv! 
![thank-you-stronk](https://github.com/documenso/documenso/assets/13398220/7fa9ca0e-b899-4b0c-9d16-632493490355)
