### ISSUE TITLE
Enhance Delete Account Dialog

### ISSUE THREAD

**Issue by Gautam-Hegde** [documenso/documenso#998]
### Describe the improvement you are suggesting in detail

- The current delete account dialog lacks an extra confirmation step, increasing the risk of accidental deletions(2FA disabled accounts). To enhance security and prevent such incidents, I suggest incorporating a type-in username similar to GitHub's
- Layer of friction, ensuring that users are intentionally deleting their accounts.
(user retention👀)

![chore](https://github.com/documenso/documenso/assets/85569489/2fc13ecf-ab13-44d6-b7bf-8f982e698fd9)

### Additional Information & Alternatives (optional)

This can be particularly beneficial in cases where users may be impulsively attempting to delete their accounts without fully evaluating the consequences.

### Do you want to work on this improvement?

Yes

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Mythie** [comment]
Looks good, lets do it!
